
/*
*
* Copyright (c) 2012 OPCIONES EMPRESARIALES DEL NORESTE S.A. DE C.V. S.F.P / CONDESE S.C.
* Avenida Delfines s/n Entre Marlin y Tiburon, La Paz, BCS Mexico CP 23090.
*
* Clase de definicion de constantes de errores en servicios
*
*/

package net.izel.framework.util.sg;

import java.util.HashMap;

public class Errores { 

	/*OK*/
	public static final long OK = 0;

	/*ERROR INESPERADO EN ALTA SEGURO GLOBAL*/
	public static final long EI_ALTA_SEGURO_GLOBAL = 1;

	/*CAMPO %s REQUERIDO*/
	public static final long CAPTURE_CAMPOS_REQUERIDOS = 2;

	/*ESTADO SEGURO ALTA NO EXISTE VERIFIQUE CONFIGURACION*/
	public static final long EDO_SEG_ALTA_NO_EX = 3;

	/*ERROR INESPERADO EN ALTA SEGURO*/
	public static final long EI_ALTA_SEGURO = 4;

	/*ERROR EN LA CONFIGURACION DE ESTADOS DE TRANSACCIONES*/
	public static final long ERR_CONF_EDO_TRX = 5;

	/*EL COSTO DEL SEGURO NO ESTA DEFINIDO*/
	public static final long ASG_COSTO_NO_EX = 6;

	/*NO EXISTE ASEGURADORA*/
	public static final long ERR_ASEGURADORA_NO_EX = 7;

	/*ERROR INESPERADO AL CREAR TRANSACCION*/
	public static final long EI_CREAR_TRX = 8;

	/*ERROR AL CREAR TRANSACCION CAMPOS %s REQUERIDOS*/
	public static final long TRX_CREAR_CAMPO_REQUERIDO = 9;

	/*EMPRESA REQUERIDA PARA DAR DE ALTA BENEFICIARIOS*/
	public static final long AB_EMPRESA_REQUERIDA = 10;

	/*CAMPO %s REQUERIDOS PARA ALTA DE BENEFICIARIOS*/
	public static final long AB_CAMPO_REQUERIDO = 11;

	/*ERROR INESPERADO EN EL METODO VALIDA BENEFICIARIOS*/
	public static final long EI_VAL_ALTA_BENEF = 12;

	/*LA LISTA DE BENEFICIARIOS ESTA VACIA*/
	public static final long AB_LISTA_VACIA = 13;

	/*VERIFIQUE PORCENTAJE DE BENEFICIARIOS*/
	public static final long ERROR_PORC_BENEFICIARIOS = 14;

	/*ERROR INESPERADO EN ALTA BENEFICIARIOS*/
	public static final long EI_ALTA_BENEFICIARIOS = 15;

	/*EL ASEGURADO NO PUEDE SER BENEFICIARIO*/
	public static final long AB_ASEGURADO_BENEFICIARIO = 16;

	/*CAMPO %s REQUERIDOS PARA CONSULTAR PRODUCTO*/
	public static final long CP_CAMPO_REQUERIDO = 18;

	/*ERROR INESPERADO AL CONSULTAR PRODUCTO*/
	public static final long EI_CONSULTA_PRODUCTO = 19;

	/*PRODUCTO NO EXISTE*/
	public static final long PRODUCTO_NO_EXISTE = 20;

	/*EL PRODUCTO NO EXISTE CON EL ESTADO DE OPERACION SOLICITADO*/
	public static final long CLAVE_ESTADO_PRODUCTO_INCORRECTA = 21;

	/*EL PRODUCTO NO EXISTE CON EL ESTATUS DEL REGISTRO SOLICITADO*/
	public static final long CLAVE_ESTATUS_PRODUCTO_INCORRECTA = 22;

	/*CAMPO %s REQUERIDOS PARA OBTENER COBROS ADICIONALES*/
	public static final long OCA_CAMPO_REQUERIDO = 23;

	/*ERROR INESPERADO AL OBTENER COSTOS*/
	public static final long EI_OBTENER_COSTOS = 24;

	/*ERROR EN EL WS ALTA SEGURO*/
	public static final long EWS_ALTA_SEGURO = 25;

	/*CAMPO %s REQUERIDOS PARA ACTIVAR SEGURO*/
	public static final long ACT_SEG_CAMPO_REQUERIDO = 26;

	/*ERROR INESPERADO AL ACTIVAR SEGURO*/
	public static final long EI_ACTIVAR_SEGURO = 27;

	/*ERROR EN LA CONFIGURACION DE CONCETOS DE TRANSACCION*/
	public static final long ERR_CONF_CON_TRX = 28;

	/*ERROR EN LA CONFIGURACION OPERACIONES*/
	public static final long ERR_CONF_EDO_OPE = 29;

	/*EL SEGURO YA ESTA VIGENTE*/
	public static final long ACTSEG_SEGURO_ACTIVO = 30;

	/*EL SEGURO NO TIENE EL ESTADO REQUERIDO DE ALTA*/
	public static final long PAGSEG_ESTADO_ALTA_REQUERIDO = 31;

	/*ERROR AL PAGAR SEGURO EL CONCEPTO MONTO TOTAL SEGURO NO EXISTE*/
	public static final long PAGSEG_NO_EXISTE_CONCEPTO_MTO_TOTAL_SEGURO = 32;

	/*MONTO PAGADO DIFERENTE AL MONTO TOTAL DEL SEGURO*/
	public static final long PAGSEG_MTO_PAG_MTO_TOTAL = 33;

	/*MONTO PAGADO DIFERENTE AL DESGLOSE DE CONCEPTOS*/
	public static final long PAGSEG_MTO_PAG_CONCEPTO = 34;

	/*ERROR INESPERADO AL PAGAR SEGURO*/
	public static final long EI_PAGAR_SEGURO = 35;

	/*ERROR INESPERADO EN VENTA SEGURO*/
	public static final long EI_VENTA_SEGURO = 36;

	/*ERROR INESPERADO AL ACTUALIZAR DATOS SEGURO POR CLAVE*/
	public static final long EI_ACTUALIZA_DATOS_SEGURO_CLAVE = 37;

	/*CAMPO %REQUERIDO PARA CONSULTAR DATOS DE SEGURO*/
	public static final long CDS_CAMPO_REQUERIDO = 38;

	/*EL CONCEPTO NO EXISTE EN DATOS SEGURO*/
	public static final long CDS_CONCEPTO_NO_EXISTE = 39;

	/*ERROR INESPERADO AL CONSULTAR DATOS SEGURO*/
	public static final long EI_CONSULTA_DATOS_SEGURO = 40;

	/*CAMPO %REQUERIDO PARA LISTADO PRODUCTO POR CATEGORIAS*/
	public static final long LPC_CAMPO_REQUERIDO = 41;

	/*ERROT INESPERADO LISTADO PRODUCTO CATEGORIAS*/
	public static final long EI_LISTADO_PRODUCTO_CATEGORIAS = 42;

	/*ERROR INESPERADO EN EL WS AL CONSULTAR PRODUCTO*/
	public static final long EI_WS_CONSULTA_PRODUCTO = 43;

	/*ERROR INESPERADO AL OBTENER CONTEXTO*/
	public static final long EI_OBTENER_CONTEXTO = 44;

	/*CAMPO %REQUERIDO PARA OBTENER EL LISTADO DE COSTOS DE PRODUCTOS*/
	public static final long LC_CAMPO_REQUERIDO = 45;

	/*VERIFIQUE PRODUCTO SIN CONFIGURACION DE COBERTURAS Y COSTOS*/
	public static final long LC_COSTO_VACIO = 46;

	/*ERROR INESPERADO EN LISTADO COSTO*/
	public static final long EI_LISTADO_COSTO = 47;

	/*DOMICILIO VACIO, VERIFIQUE INFORMACION EN EL MODULO DE CLIENTES*/
	public static final long DOM_VACIO_BEN = 48;

	/*EL SEGURO NO EXISTE*/
	public static final long ACTSEG_SEGURO_ID_NO_EX = 49;

	/*VERIFIQUE CATALOGOS ESTADO VIGENTE NO EXISTE*/
	public static final long ACTSEG_ESTADO_VIGENTE = 50;

	/*EL SOLICITANTE NO TIENE LA EDAD PERMITIDA*/
	public static final long EDAD_ASEGURADO_INCORRECTA = 51;

	/*LA SUMA ASEGURADA TOTAL DE TODOS LOS SEGUROS DE LA PERSONA EXCEDE DE LO PERMITIDO POR EL PRODUCTO*/
	public static final long SUMA_ASEGURADA_EXCEDE = 52;

	/*ERROR INESPERADO EN VALIDACIONES DE PRODUCTO*/
	public static final long EI_VALIDACIONES_PRODUCTO = 53;

	/*LA EDAD DEL BENEFICIARIO ES INCORRECTA*/
	public static final long EDAD_BENEFICIARIO_INCORRECTA = 54;

	/*ERROR INESPERADO EN EL WS CREAR PRODUCTO*/
	public static final long EI_WS_CREAR_PRODUCTO = 55;

	/*CAMPOS %REQUERIDOS PARA CREAR PRODUCTO DE SEGURO*/
	public static final long CRP_CAMPO_REQUERIDO = 56;

	/*LA CLAVE CAPTURADA PARA EL PRODUCTO YA EXISTE*/
	public static final long CRP_CLAVE_EXISTE = 57;

	/*ERROR INESPERADO AL CREAR PRODUCTO*/
	public static final long EI_CREAR_PRODUCTO = 58;
	
	/*CAMPO REQUERIDO PARA CONSULTAR MAESTRO DE SEGURO*/
	public static final long CMS_CAMPO_REQUERIDO = 59;
	
	/*CAMPO REQUERIDO PARA CONSULTAR MAESTRO DE SEGURO*/
	public static final long CMS_SEGURO_NO_EXISTE = 60;
	
	/*ERROR INESPERADO AL CONSULTAR MAESTRO SEGURO*/
	public static final long EI_CONSULTA_MAESTRO_SEGURO = 61;
	
	/*ERROR INESPERADO EN EL WS CONSULTAR MAESTRO SEGURO*/
	public static final long EI_CONSULTA_WS_MAESTRO_SEGURO = 62;
	
	/*ERROR AL PAGAR SEGURO EL CONCEPTO MONTO SEGURO NO EXISTE*/
	public static final long PAGSEG_NO_EXISTE_CONCEPTO_MTO_SEGURO = 63;
	
	/*VERIFIQUE NUMERO DE BENEFICIARIOS SE REQUIEREN MAS A LOS CAPTURADOS*/
	public static final long ERROR_NO_BENEFICIARIOS_MIN = 64;
	
	/*VERIFIQUE NUMERO DE BENEFICIARIOS SE EXCEDEN A LOS REQUERIDOS*/
	public static final long ERROR_NO_BENEFICIARIOS_MAX = 65;
	
	/*CAMPO %s REQUERIDOS PARA CANCELAR SEGURO*/
	public static final long CAN_SEG_CAMPO_REQUERIDO = 66;

	/*EL SEGURO NO EXISTE*/
	public static final long CANSEG_SEGURO_ID_NO_EX = 67;

	/*VERIFIQUE CATALOGOS ESTADO CANCELADO NO EXISTE*/
	public static final long CANSEG_ESTADO_CANCELADO = 68;

	/*EL SEGURO YA ESTA CANCELADO*/
	public static final long CANSEG_SEGURO_CANCELADO = 69;

	/*ERROR INESPERADO AL CANCELAR SEGURO*/
	public static final long EI_CANCELAR_SEGURO = 70;
	
	/*PROVEEDOR DE RECURSOS NO ES EMPLEADO*/
	public static final long PRO_REC_NO_EMPLEADO = 71;

	/*PROVEEDOR DE RECURSOS NO CUENTA CON EL PARENTESCO PERMITIDO*/
	public static final long PRO_REC_PARENTESCO = 72;

	/*PROVEEDOR DE RECURSOS REQUERIDO*/
	public static final long PRO_REC_REQUERIDO = 73;

	/*PRODUCTO SEGURO REQUERIDO*/
	public static final long PRODUCTO_SEGURO_REQUERIDO = 74;

	/*EL PRODUCTO SELECCIONADO NO ES INTERNO*/
	public static final long PRODUCTO_NO_INTERNO = 75;

	/*EL PRODUCTO SELECCIONADO NO ES GRATUITO*/
	public static final long PRODUCTO_NO_GRATUITO = 76;

	/*EL PRODUCTO SELECCIONADO NO PERMITIDO PARA EL PROVEEDOR DE RECURSOS*/
	public static final long PRODUCTO_NO_PERMITIDO_PROV_REC = 77;

	/*ACTUALICE CONCEPTO NUMERO SOLICITANTE DE LA PERSONA*/
	public static final long ACTUALICE_NUM_SOL = 78;

	/*PERSONA SIN CUENTAS QUE CUMPLAN CON LA VIGENCIA*/
	public static final long PERSONA_SIN_CUENTAS = 79;

	/*CUENTA NO VIGENTE PARA PROGRAMA DE SEGURO GRATUITO*/
	public static final long CTA_NO_VIGENTE_PROGRAMA = 80;

	/*CUENTA CON TODOS LOS SEGUROS GRATUITOS ADQUIRIDOS*/
	public static final long CTA_TODOS_SEGUROS_GRATUITOS = 81;

	/*ERROR INESPERADO EN CONSULTA SEGUROS POR CLAVE CONCEPTO*/
	public static final long EI_CONSULTA_SEGUROS_CLAVE_CONCEPTO = 82;
	
	/*ACTUALICE EL NUMERO DE NOMINA EN EL MODULO DE CLIENTES*/
	public static final long ACTUALICE_NUMERO_EMPLEADO_CLIENTES = 83;
	
	/*ERROR INESPERADO AL ENVIAR CORREOS*/
	public static final long EI_ENVIAR_CORREOS = 84;

	/*ERROR EN LA CONFIGURACION DE CORREOS A ENVIAR*/
	public static final long ERR_CONFIGURACION_CORREOS = 85;

	/*LA EMPRESA DEL EMPLEADO NO EXISTE*/
	public static final long EMPRESA_EMPLEADO_NO_EXISTE = 86;

	/*ERROR INESPERADO EN EL WS VALIDAR INFORMACION SEGURO*/
	public static final long EI_WS_VALIDAR_INFORMACION_SEGURO = 87;

	/*ERROR INESPERADO EN EL WS OBTENER SEGUROS POR CLAVE CONCEPTO*/
	public static final long EI_WS_OBTENER_SEGUROS_POR_CLAVE_CONCEPTO = 88;

	/*ERROR INESPERADO EN EL WS OBTENER_SEGURO_GRATUITO*/
	public static final long EI_WS_OBTENER_SEGURO_GRATUITO = 89;
	
	/*ERROR INESPERADO AL ACTUALIZAR MESES DE COBERTURA*/
	public static final long EI_ACTUALIZAR_MESES_COBERTURA = 90;

	/*CAMPO %s REQUERIDOS PARA ACTUALIZAR MESES DE COBERTURA*/
	public static final long AMC_CAMPO_REQUERIDO = 91;

	/*PERSONA ASEGURADA REQUERIDA*/
	public static final long PERSONA_ASEGURADA_REQUIERA = 92;
	
	/*ERROR INESPERADO WS ACTIVAR SEGURO*/
	public static final long EI_WS_ACTIVAR_SEGURO = 93;
	
	/*PROVEEDOR DE RECURSOS NO ESTA REGISTRADO EN RECURSOS HUMANOS*/
	public static final long PROV_REC_NO_RH = 94;
	
	/*ERROR INESPERADO EN EL WS OBTENER SEGUROS POR CUENTA*/
	public static final long EI_WS_OBTENER_SEGUROS_POR_CUENTA = 95;
	

	public static HashMap<Long, String> descError = new HashMap<Long, String>();

	static {
		descError.put(OK,"OK");
		descError.put(EI_ALTA_SEGURO_GLOBAL,"ERROR INESPERADO EN ALTA SEGURO GLOBAL");
		descError.put(CAPTURE_CAMPOS_REQUERIDOS,"CAMPO %s REQUERIDO");
		descError.put(EDO_SEG_ALTA_NO_EX,"ESTADO SEGURO ALTA NO EXISTE VERIFIQUE CONFIGURACION");
		descError.put(EI_ALTA_SEGURO,"ERROR INESPERADO EN ALTA SEGURO");
		descError.put(ERR_CONF_EDO_TRX,"ERROR EN LA CONFIGURACION DE ESTADOS DE TRANSACCIONES");
		descError.put(ASG_COSTO_NO_EX,"EL COSTO DEL SEGURO NO ESTA DEFINIDO");
		descError.put(ERR_ASEGURADORA_NO_EX,"NO EXISTE ASEGURADORA");
		descError.put(EI_CREAR_TRX,"ERROR INESPERADO AL CREAR TRANSACCION");
		descError.put(TRX_CREAR_CAMPO_REQUERIDO,"ERROR AL CREAR TRANSACCION CAMPOS %s REQUERIDOS");
		descError.put(AB_EMPRESA_REQUERIDA,"EMPRESA REQUERIDA PARA DAR DE ALTA BENEFICIARIOS");
		descError.put(AB_CAMPO_REQUERIDO,"CAMPO %s REQUERIDOS PARA ALTA DE BENEFICIARIOS");
		descError.put(EI_VAL_ALTA_BENEF,"ERROR INESPERADO EN EL METODO VALIDA BENEFICIARIOS");
		descError.put(AB_LISTA_VACIA,"LA LISTA DE BENEFICIARIOS ESTA VACIA");
		descError.put(ERROR_PORC_BENEFICIARIOS,"VERIFIQUE PORCENTAJE DE BENEFICIARIOS");
		descError.put(EI_ALTA_BENEFICIARIOS,"ERROR INESPERADO EN ALTA BENEFICIARIOS");
		descError.put(AB_ASEGURADO_BENEFICIARIO,"EL ASEGURADO NO PUEDE SER BENEFICIARIO");
		descError.put(CP_CAMPO_REQUERIDO,"CAMPO %s REQUERIDOS PARA CONSULTAR PRODUCTO");
		descError.put(EI_CONSULTA_PRODUCTO,"ERROR INESPERADO AL CONSULTAR PRODUCTO");
		descError.put(PRODUCTO_NO_EXISTE,"PRODUCTO NO EXISTE");
		descError.put(CLAVE_ESTADO_PRODUCTO_INCORRECTA,"EL PRODUCTO NO EXISTE CON EL ESTADO DE OPERACION SOLICITADO");
		descError.put(CLAVE_ESTATUS_PRODUCTO_INCORRECTA,"EL PRODUCTO NO EXISTE CON EL ESTATUS DEL REGISTRO SOLICITADO");
		descError.put(OCA_CAMPO_REQUERIDO,"CAMPO %s REQUERIDOS PARA OBTENER COBROS ADICIONALES");
		descError.put(EI_OBTENER_COSTOS,"ERROR INESPERADO AL OBTENER COSTOS");
		descError.put(EWS_ALTA_SEGURO,"ERROR EN EL WS ALTA SEGURO");
		descError.put(ACT_SEG_CAMPO_REQUERIDO,"CAMPO %s REQUERIDOS PARA ACTIVAR SEGURO");
		descError.put(EI_ACTIVAR_SEGURO,"ERROR INESPERADO AL ACTIVAR SEGURO");
		descError.put(ERR_CONF_CON_TRX,"ERROR EN LA CONFIGURACION DE CONCETOS DE TRANSACCION");
		descError.put(ERR_CONF_EDO_OPE,"ERROR EN LA CONFIGURACION OPERACIONES");
		descError.put(ACTSEG_SEGURO_ACTIVO,"EL SEGURO YA ESTA VIGENTE");
		descError.put(PAGSEG_ESTADO_ALTA_REQUERIDO,"EL SEGURO NO TIENE EL ESTADO REQUERIDO DE ALTA");
		descError.put(PAGSEG_NO_EXISTE_CONCEPTO_MTO_TOTAL_SEGURO,"ERROR AL PAGAR SEGURO EL CONCEPTO MONTO TOTAL SEGURO NO EXISTE");
		descError.put(PAGSEG_MTO_PAG_MTO_TOTAL,"MONTO PAGADO DIFERENTE AL MONTO TOTAL DEL SEGURO");
		descError.put(PAGSEG_MTO_PAG_CONCEPTO,"MONTO PAGADO DIFERENTE AL DESGLOSE DE CONCEPTOS");
		descError.put(EI_PAGAR_SEGURO,"ERROR INESPERADO AL PAGAR SEGURO");
		descError.put(EI_VENTA_SEGURO,"ERROR INESPERADO EN VENTA SEGURO");
		descError.put(EI_ACTUALIZA_DATOS_SEGURO_CLAVE,"ERROR INESPERADO AL ACTUALIZAR DATOS SEGURO POR CLAVE");
		descError.put(CDS_CAMPO_REQUERIDO,"CAMPO %REQUERIDO PARA CONSULTAR DATOS DE SEGURO");
		descError.put(CDS_CONCEPTO_NO_EXISTE,"EL CONCEPTO NO EXISTE EN DATOS SEGURO");
		descError.put(EI_CONSULTA_DATOS_SEGURO,"ERROR INESPERADO AL CONSULTAR DATOS SEGURO");
		descError.put(LPC_CAMPO_REQUERIDO,"CAMPO %REQUERIDO PARA LISTADO PRODUCTO POR CATEGORIAS");
		descError.put(EI_LISTADO_PRODUCTO_CATEGORIAS,"ERROT INESPERADO LISTADO PRODUCTO CATEGORIAS");
		descError.put(EI_WS_CONSULTA_PRODUCTO,"ERROR INESPERADO EN EL WS AL CONSULTAR PRODUCTO");
		descError.put(EI_OBTENER_CONTEXTO,"ERROR INESPERADO AL OBTENER CONTEXTO");
		descError.put(LC_CAMPO_REQUERIDO,"CAMPO %REQUERIDO PARA OBTENER EL LISTADO DE COSTOS DE PRODUCTOS");
		descError.put(LC_COSTO_VACIO,"VERIFIQUE PRODUCTO SIN CONFIGURACION DE COBERTURAS Y COSTOS");
		descError.put(EI_LISTADO_COSTO,"ERROR INESPERADO EN LISTADO COSTO");
		descError.put(DOM_VACIO_BEN,"DOMICILIO VACIO, VERIFIQUE INFORMACION EN EL MODULO DE CLIENTES");
		descError.put(ACTSEG_SEGURO_ID_NO_EX,"EL SEGURO NO EXISTE");
		descError.put(ACTSEG_ESTADO_VIGENTE,"VERIFIQUE CATALOGOS ESTADO VIGENTE NO EXISTE");
		descError.put(EDAD_ASEGURADO_INCORRECTA,"EL SOLICITANTE NO TIENE LA EDAD PERMITIDA");
		descError.put(SUMA_ASEGURADA_EXCEDE,"LA SUMA ASEGURADA TOTAL DE TODOS LOS SEGUROS DE LA PERSONA EXCEDE DE LO PERMITIDO POR EL PRODUCTO");
		descError.put(EI_VALIDACIONES_PRODUCTO,"ERROR INESPERADO EN VALIDACIONES DE PRODUCTO");
		descError.put(EDAD_BENEFICIARIO_INCORRECTA,"LA EDAD DEL BENEFICIARIO ES INCORRECTA");
		descError.put(EI_WS_CREAR_PRODUCTO,"ERROR INESPERADO EN EL WS CREAR PRODUCTO");
		descError.put(CRP_CAMPO_REQUERIDO,"CAMPOS %REQUERIDOS PARA CREAR PRODUCTO DE SEGURO");
		descError.put(CRP_CLAVE_EXISTE,"LA CLAVE CAPTURADA PARA EL PRODUCTO YA EXISTE");
		descError.put(EI_CREAR_PRODUCTO,"ERROR INESPERADO AL CREAR PRODUCTO");
		descError.put(CMS_CAMPO_REQUERIDO,"AMPO REQUERIDO PARA CONSULTAR MAESTRO DE SEGURO");
		descError.put(CMS_SEGURO_NO_EXISTE,"CAMPO REQUERIDO PARA CONSULTAR MAESTRO DE SEGURO");
		descError.put(EI_CONSULTA_MAESTRO_SEGURO,"ERROR INESPERADO AL CONSULTAR MAESTRO SEGURO");
		descError.put(EI_CONSULTA_WS_MAESTRO_SEGURO,"ERROR INESPERADO EN EL WS CONSULTAR MAESTRO SEGURO");
		descError.put(PAGSEG_NO_EXISTE_CONCEPTO_MTO_SEGURO,"ERROR AL PAGAR SEGURO EL CONCEPTO MONTO SEGURO NO EXISTE");
		descError.put(ERROR_NO_BENEFICIARIOS_MIN,"VERIFIQUE NUMERO DE BENEFICIARIOS SE REQUIEREN MAS A LOS CAPTURADOS");
		descError.put(ERROR_NO_BENEFICIARIOS_MAX,"VERIFIQUE NUMERO DE BENEFICIARIOS SE EXCEDEN A LOS REQUERIDOS");
		descError.put(CAN_SEG_CAMPO_REQUERIDO,"CAMPO %s REQUERIDOS PARA CANCELAR SEGURO");
		descError.put(CANSEG_SEGURO_ID_NO_EX,"EL SEGURO NO EXISTE");
		descError.put(CANSEG_ESTADO_CANCELADO,"VERIFIQUE CATALOGOS ESTADO CANCELADO NO EXISTE");
		descError.put(CANSEG_SEGURO_CANCELADO,"EL SEGURO YA ESTA CANCELADO");
		descError.put(EI_CANCELAR_SEGURO,"ERROR INESPERADO AL CANCELAR SEGURO");
		descError.put(PRO_REC_NO_EMPLEADO,"PROVEEDOR DE RECURSOS NO ES EMPLEADO");
		descError.put(PRO_REC_PARENTESCO,"PROVEEDOR DE RECURSOS NO CUENTA CON EL PARENTESCO PERMITIDO");
		descError.put(PRO_REC_REQUERIDO,"PROVEEDOR DE RECURSOS REQUERIDO");
		descError.put(PRODUCTO_SEGURO_REQUERIDO,"PRODUCTO SEGURO REQUERIDO");
		descError.put(PRODUCTO_NO_INTERNO,"EL PRODUCTO SELECCIONADO NO ES INTERNO");
		descError.put(PRODUCTO_NO_GRATUITO,"EL PRODUCTO SELECCIONADO NO ES GRATUITO");
		descError.put(PRODUCTO_NO_PERMITIDO_PROV_REC,"EL PRODUCTO SELECCIONADO NO PERMITIDO PARA EL PROVEEDOR DE RECURSOS");
		descError.put(ACTUALICE_NUM_SOL,"ACTUALICE CONCEPTO NUMERO SOLICITANTE DE LA PERSONA");
		descError.put(PERSONA_SIN_CUENTAS,"PERSONA SIN CUENTAS QUE CUMPLAN CON LA VIGENCIA");
		descError.put(CTA_NO_VIGENTE_PROGRAMA,"CUENTA NO VIGENTE PARA PROGRAMA DE SEGURO GRATUITO");
		descError.put(CTA_TODOS_SEGUROS_GRATUITOS,"CUENTA CON TODOS LOS SEGUROS GRATUITOS ADQUIRIDOS");
		descError.put(EI_CONSULTA_SEGUROS_CLAVE_CONCEPTO,"ERROR INESPERADO EN CONSULTA SEGUROS POR CLAVE CONCEPTO");
		descError.put(ACTUALICE_NUMERO_EMPLEADO_CLIENTES,"ACTUALICE EL NUMERO DE NOMINA EN EL MODULO DE CLIENTES");
		descError.put(EI_ENVIAR_CORREOS,"ERROR INESPERADO AL ENVIAR CORREOS");
		descError.put(ERR_CONFIGURACION_CORREOS,"ERROR EN LA CONFIGURACION DE CORREOS A ENVIAR");
		descError.put(EMPRESA_EMPLEADO_NO_EXISTE,"LA EMPRESA DEL EMPLEADO NO EXISTE");
		descError.put(EI_WS_VALIDAR_INFORMACION_SEGURO,"ERROR INESPERADO EN EL WS VALIDAR INFORMACION SEGURO");
		descError.put(EI_WS_OBTENER_SEGUROS_POR_CLAVE_CONCEPTO,"ERROR INESPERADO EN EL WS OBTENER SEGUROS POR CLAVE CONCEPTO");
		descError.put(EI_WS_OBTENER_SEGURO_GRATUITO,"ERROR INESPERADO EN EL WS OBTENER_SEGURO_GRATUITO");
		descError.put(EI_ACTUALIZAR_MESES_COBERTURA,"ERROR INESPERADO AL ACTUALIZAR MESES DE COBERTURA");
		descError.put(AMC_CAMPO_REQUERIDO,"CAMPO %s REQUERIDOS PARA ACTUALIZAR MESES DE COBERTURA");
		descError.put(PERSONA_ASEGURADA_REQUIERA,"PERSONA ASEGURADA REQUERIDA");
		descError.put(EI_WS_ACTIVAR_SEGURO,"ERROR INESPERADO WS ACTIVAR SEGURO");
		descError.put(PROV_REC_NO_RH,"PROVEEDOR DE RECURSOS NO ESTA REGISTRADO EN RECURSOS HUMANOS");
		descError.put(EI_WS_OBTENER_SEGUROS_POR_CUENTA,"ERROR INESPERADO EN EL WS OBTENER SEGUROS POR CUENTA");
		
	}

}

