package net.giro.co.beans;


/**
 * CBCorrelativoId generated by MyEclipse Persistence Tools
 */
//@Embeddable
public class CorrelativoId implements java.io.Serializable {

	// Fields

	private static final long serialVersionUID = 6336855080122372299L;

	private Long codigoEmpresa;
	private String nombreTabla;

	// Constructors

	/** default constructor */
	public CorrelativoId() {
	}

	/** full constructor */
	public CorrelativoId(Long codigoEmpresa, String nombreTabla) {
		this.codigoEmpresa = codigoEmpresa;
		this.nombreTabla = nombreTabla;
	}

	// Property accessors

	//@Column(name = "C_CODEMP", unique = false, nullable = false, insertable = true, updatable = true, length = 3)
	public Long getCodigoEmpresa() {
		return this.codigoEmpresa;
	}

	public void setCodigoEmpresa(Long codigoEmpresa) {
		this.codigoEmpresa = codigoEmpresa;
	}

	//@Column(name = "C_NOMTAB", unique = false, nullable = false, insertable = true, updatable = true, length = 15)
	public String getNombreTabla() {
		return this.nombreTabla;
	}

	public void setNombreTabla(String nombreTabla) {
		this.nombreTabla = nombreTabla;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CorrelativoId))
			return false;
		CorrelativoId castOther = (CorrelativoId) other;

		return ((this.getCodigoEmpresa() == castOther.getCodigoEmpresa()) || (this
				.getCodigoEmpresa() != null
				&& castOther.getCodigoEmpresa() != null && this.getCodigoEmpresa().equals(
				castOther.getCodigoEmpresa())))
				&& ((this.getNombreTabla() == castOther.getNombreTabla()) || (this
						.getNombreTabla() != null
						&& castOther.getNombreTabla() != null && this.getNombreTabla()
						.equals(castOther.getNombreTabla())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodigoEmpresa() == null ? 0 : this.getCodigoEmpresa().hashCode());
		result = 37 * result
				+ (getNombreTabla() == null ? 0 : this.getNombreTabla().hashCode());
		return result;
	}

}