package net.izel.ws.seg.menueliminar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-03-01T17:24:02.067-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://menuEliminar.seg.ws.izel.net/", name = "MenuEliminarIfz")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MenuEliminarIfz {

    @WebResult(name = "MenuEliminarResponse", targetNamespace = "http://menuEliminar.seg.ws.izel.net/", partName = "parameters")
    @WebMethod
    public MenuEliminarResponse guardar(
        @WebParam(partName = "parameters", name = "MenuEliminarRequest", targetNamespace = "http://menuEliminar.seg.ws.izel.net/")
        MenuEliminarRequest parameters
    );
}
