package net.izel.ws.seg.consultausuarios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-03-24T10:17:18.531-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://consultaUsuarios.seg.ws.izel.net/", name = "ConsultaUsuariosIfz")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ConsultaUsuariosIfz {

    @WebResult(name = "ConsultaUsuariosResponse", targetNamespace = "http://consultaUsuarios.seg.ws.izel.net/", partName = "parameters")
    @WebMethod
    public ConsultaUsuariosResponse procesar(
        @WebParam(partName = "parameters", name = "ConsultaUsuariosRequest", targetNamespace = "http://consultaUsuarios.seg.ws.izel.net/")
        ConsultaUsuariosRequest parameters
    );
}
