package net.izel.ws.seg.rolmenueliminar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-03-01T08:53:38.585-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://rolMenuEliminar.seg.ws.izel.net/", name = "RolMenuEliminarIfz")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RolMenuEliminarIfz {

    @WebResult(name = "RolMenuEliminarResponse", targetNamespace = "http://rolMenuEliminar.seg.ws.izel.net/", partName = "parameters")
    @WebMethod
    public RolMenuEliminarResponse guardar(
        @WebParam(partName = "parameters", name = "RolMenuEliminarRequest", targetNamespace = "http://rolMenuEliminar.seg.ws.izel.net/")
        RolMenuEliminarRequest parameters
    );
}
