package net.izel.ws.seg.rolmenueliminar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-03-01T08:53:38.645-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "RolMenuEliminarIfzService", 
                  wsdlLocation = "http://localhost:17081/esb/seguridad/rol-menu-eliminar?wsdl",
                  targetNamespace = "http://rolMenuEliminar.seg.ws.izel.net/") 
public class RolMenuEliminarIfzService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://rolMenuEliminar.seg.ws.izel.net/", "RolMenuEliminarIfzService");
    public final static QName RolMenuEliminarIfzPort = new QName("http://rolMenuEliminar.seg.ws.izel.net/", "RolMenuEliminarIfzPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:17081/esb/seguridad/rol-menu-eliminar?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RolMenuEliminarIfzService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:17081/esb/seguridad/rol-menu-eliminar?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RolMenuEliminarIfzService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RolMenuEliminarIfzService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RolMenuEliminarIfzService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RolMenuEliminarIfzService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RolMenuEliminarIfzService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RolMenuEliminarIfzService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RolMenuEliminarIfz
     */
    @WebEndpoint(name = "RolMenuEliminarIfzPort")
    public RolMenuEliminarIfz getRolMenuEliminarIfzPort() {
        return super.getPort(RolMenuEliminarIfzPort, RolMenuEliminarIfz.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RolMenuEliminarIfz
     */
    @WebEndpoint(name = "RolMenuEliminarIfzPort")
    public RolMenuEliminarIfz getRolMenuEliminarIfzPort(WebServiceFeature... features) {
        return super.getPort(RolMenuEliminarIfzPort, RolMenuEliminarIfz.class, features);
    }

}
