package net.izel.ws.seg.rolguardar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-03-01T08:50:43.135-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://rolGuardar.seg.ws.izel.net/", name = "RolGuardarIfz")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RolGuardarIfz {

    @WebResult(name = "RolGuardarResponse", targetNamespace = "http://rolGuardar.seg.ws.izel.net/", partName = "parameters")
    @WebMethod
    public RolGuardarResponse guardar(
        @WebParam(partName = "parameters", name = "RolGuardarRequest", targetNamespace = "http://rolGuardar.seg.ws.izel.net/")
        RolGuardarRequest parameters
    );
}
