//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.02 at 08:56:37 PM MDT 
//

@XmlSchema(
		namespace="http://www.sat.gob.mx/Pagos", 
		elementFormDefault=XmlNsForm.QUALIFIED,
		xmlns={
				@XmlNs(namespaceURI = "http://www.sat.gob.mx/Pagos", prefix = "pago10")})
package net.giro.cxc.FEv33.complementos.pagos10;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;
