package net.izel.ws.seg.rolbuscar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-02-28T23:07:28.427-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "RolBuscarIfzService", 
                  wsdlLocation = "http://localhost:17081/esb/seguridad/rol-buscar?wsdl",
                  targetNamespace = "http://rolBuscar.seg.ws.izel.net/") 
public class RolBuscarIfzService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://rolBuscar.seg.ws.izel.net/", "RolBuscarIfzService");
    public final static QName RolBuscarIfzPort = new QName("http://rolBuscar.seg.ws.izel.net/", "RolBuscarIfzPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:17081/esb/seguridad/rol-buscar?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RolBuscarIfzService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:17081/esb/seguridad/rol-buscar?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RolBuscarIfzService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RolBuscarIfzService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RolBuscarIfzService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RolBuscarIfzService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RolBuscarIfzService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RolBuscarIfzService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RolBuscarIfz
     */
    @WebEndpoint(name = "RolBuscarIfzPort")
    public RolBuscarIfz getRolBuscarIfzPort() {
        return super.getPort(RolBuscarIfzPort, RolBuscarIfz.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RolBuscarIfz
     */
    @WebEndpoint(name = "RolBuscarIfzPort")
    public RolBuscarIfz getRolBuscarIfzPort(WebServiceFeature... features) {
        return super.getPort(RolBuscarIfzPort, RolBuscarIfz.class, features);
    }

}
