package net.izel.ws.seg.pantallamodificar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-03-01T22:48:24.902-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "PantallaModificarIfzService", 
                  wsdlLocation = "http://localhost:17081/esb/seguridad/pantalla-modificar?wsdl",
                  targetNamespace = "http://pantallaModificar.seg.ws.izel.net/") 
public class PantallaModificarIfzService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://pantallaModificar.seg.ws.izel.net/", "PantallaModificarIfzService");
    public final static QName PantallaModificarIfzPort = new QName("http://pantallaModificar.seg.ws.izel.net/", "PantallaModificarIfzPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:17081/esb/seguridad/pantalla-modificar?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PantallaModificarIfzService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:17081/esb/seguridad/pantalla-modificar?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PantallaModificarIfzService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PantallaModificarIfzService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PantallaModificarIfzService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PantallaModificarIfzService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PantallaModificarIfzService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PantallaModificarIfzService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PantallaModificarIfz
     */
    @WebEndpoint(name = "PantallaModificarIfzPort")
    public PantallaModificarIfz getPantallaModificarIfzPort() {
        return super.getPort(PantallaModificarIfzPort, PantallaModificarIfz.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PantallaModificarIfz
     */
    @WebEndpoint(name = "PantallaModificarIfzPort")
    public PantallaModificarIfz getPantallaModificarIfzPort(WebServiceFeature... features) {
        return super.getPort(PantallaModificarIfzPort, PantallaModificarIfz.class, features);
    }

}
