package net.izel.ws.seg.menuloginbuscar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-02-28T17:08:54.055-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://menuLoginBuscar.seg.ws.izel.net/", name = "MenuLoginBuscarIfz")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MenuLoginBuscarIfz {

    @WebResult(name = "MenuLoginBuscarResponse", targetNamespace = "http://menuLoginBuscar.seg.ws.izel.net/", partName = "parameters")
    @WebMethod
    public MenuLoginBuscarResponse procesar(
        @WebParam(partName = "parameters", name = "MenuLoginBuscarRequest", targetNamespace = "http://menuLoginBuscar.seg.ws.izel.net/")
        MenuLoginBuscarRequest parameters
    );
}
