
/*
*
* Copyright (c) 2012 OPCIONES EMPRESARIALES DEL NORESTE S.A. DE C.V. S.F.P / CONDESE S.C.
* Avenida Delfines s/n Entre Marlin y Tiburon, La Paz, BCS Mexico CP 23090.
*
* Clase de definicion de constantes de errores en servicios
*
*/

package net.izel.framework.util.cl;

import java.util.HashMap;

public class Errores { 

	/*LA PERSONA YA ESTA REGISTRADA O TIENE UN HOMONIMO.DESEA CONTINUAR?*/
	public static final long PERSONA_RESGISTRADA_HOMONIMO = 1;

	/*PRIMERO BUSQUE Y SELECCIONE UNA PERSONA NATURAL*/
	public static final long PRIMERO_SELECCIONE_PERSONA_NAT = 2;

	/*LA PERSONA SELECCIONADA YA TIENE UN CONYUGE VINCULADO, SELECCIONAR OTRA*/
	public static final long PERSONA_TIENE_CONYUGE_VINCULADO = 3;

	/*EL NEGOCIO YA ESTA REGISTRADO O TIENE UN HOMONIMO, DESEA CONTINUAR?*/
	public static final long NEGOCIO_REGISTRADO_HOMONIMO = 4;

	/*VERIFIQUE,LA PERSONA A QUIEN SE LE ESTA ASOCIANDO CONYUGE ES LA MISMA PERSONA QUE EL CONYUGE SELECCIONADO*/
	public static final long CONYUGUE_ES_EL_MISMO = 5;

	/*PRIMERO BUSQUE Y SELECCIONE UN NEGOCIO*/
	public static final long PRIMERO_SELECCIONE_NEGOCIO = 6;

	/*PRIMERO BUSQUE Y SELECCIONE LA ENTIDAD QUE DESEA DAR DE BAJA*/
	public static final long SELECCIONE_ENTIDAD_BAJA = 7;

	/*CAMPO %s REQUERIDO*/
	public static final long CAPTURE_CAMPOS_REQUERIDOS = 8;

	/*VERIFIQUE, LA SECUENCIA DE LAS FECHAS CAPTURADAS ESTAN INVERTIDAS*/
	public static final long FECHAS_INVERTIDAS = 9;

	/*VERIFIQUE, LA ESTRUCTURA DEL CORREO ES INVALIDA*/
	public static final long CORREO_INVALIDO = 10;

	/*VERIFIQUE, LA PERSONA SELECCIONADA TIENE ESTATUS BAJA*/
	public static final long PERSONA_ESTATUS_BAJA = 11;

	/*VERIFIQUE, DEBE SELECCIONAR UN CRITERIO DEL LISTADO DE TIPO DE BUSQUEDA*/
	public static final long SELECCIONE_TIPO_BUSQUEDA = 12;

	/*PRIMERO BUSQUE Y SELECCIONE UN APODERADO*/
	public static final long PRIMERO_SELECCIONE_PAPODERADO = 13;

	/*REGISTRO YA HA SIDO DADO DE BAJA*/
	public static final long REGISTRO_DADO_BAJA = 14;

	/*Â“DESEA DAR DE BAJA EL REGISTRO*/
	public static final long DESEA_DAR_BAJA = 15;

	/*VERIFIQUE EL CAMPO FECHA DESDE SELECCIONO UNA FECHA MAYOR AL DIA ACTUAL.*/
	public static final long FECHA_DESDE_INCORRECTA = 16;

	/*PRIMERO BUSQUE Y SELECCIONE UNA PERSONA JURIDICA*/
	public static final long PRIMERO_SELECCIONE_PERSONA_JUR = 17;

	/*EL GRUPO SOLIDARIO YA ESTA REGISTRADO O TIENE UN HOMONIMO, DESEA CONTINUAR?*/
	public static final long GRUPOSOLIDARIO_REGISTRADO_HOMONIMO = 18;

	/*PRIMERO BUSQUE Y SELECCIONE UN GRUPO SOLIDARIO*/
	public static final long PRIMERO_SELECCIONE_GRUPOSOLIDARIO = 19;

	/*ERROR AL CREAR PERSONA NATURAL*/
	public static final long ERROR_CREAR_PERSONA = 20;

	/*VERIFIQUE, NO DEBE SELECCIONAR A LA MISMA PERSONA QUE SE LE ESTA ASOCIANDO EL VINCULADO.*/
	public static final long MISMA_PERSONA_VINCULADO = 21;

	/*LA ENTIDAD SELECCIONADA  COMO PERSONA  REFERENCIA  Y LA ENTIDAD A QUIEN SE LE ESTA REGISTRANDO LA PERSONA REFERENCIA  SON LA MISMA, SELECCIONAR OTRA*/
	public static final long PERSONA_REF_IGUAL_ENTIDAD_REF = 22;

	/*EL REGISTRO QUE DESEA DAR DE BAJA ES EL UNICO ACTIVO QUE HAY, NO ES POSIBLE REALIZAR LA BAJA*/
	public static final long UNICO_REG_ACTIVO_INBORABLE = 23;

	/*NO HA SELECCIONADO A QUIEN CORRESPONDEN LOS TELEFONOS*/
	public static final long TELEFONOS_NO_PERTENECEN = 24;

	/*CERO RESULTADOS*/
	public static final long CERO_RESULTADOS = 25;

	/*NO HA SELECCIONADO A QUIEN CORRESPONDEN LOS COREOS ELECTRONICOS*/
	public static final long CORREOS_NO_PERTENECEN = 26;

	/*NO HA SELECCIONADO A QUIEN CORRESPONDEN LOS CONTACTOS*/
	public static final long CONTACTOS_NO_PERTENECEN = 27;

	/*NO HA SELECCIONADO A QUIEN CORRESPONDEN LOS OTRAS VINCULACIONES*/
	public static final long VINCULACIONES_NO_PERTENECEN = 28;

	/*NO HA SELECCIONADO A QUIEN CORRESPONDEN LOS DOMICILIOS*/
	public static final long DOMICILIOS_NO_PERTENECEN = 29;

	/*NO HA SELECCIONADO A QUIEN CORRESPONDEN LAS RELACIONES A NIVEL DEL GRUPO ECONOMICO*/
	public static final long RELACIONES_NO_PERTENECEN = 30;

	/*NO HA SELECCIONADO A QUIEN CORRESPONDEN LAS IDENTIFICACIONES*/
	public static final long IDENTIFICACIONES_NO_PERTENECEN = 31;

	/*VERIFICAR, IDENTIFICACION DUPLICADA. */
	public static final long IDENTIFICACION_DUPLICADA = 32;

	/*VERIFIQUE EL CAMPO FECHA NACIMIENTO SELECCIONO UNA FECHA MAYOR AL DIA ACTUAL.*/
	public static final long FECHA_NACIMIENTO_INCORRECTA = 33;

	/*VERIFIQUE, DEBE CAPTURAR UN VALOR DE BUSQUEDA DE POR LO MENOS 2 CARACTERES*/
	public static final long VALOR_BUSQUEDA_INCORRECTO = 34;

	/*NO ENCONTRO UN REGISTRO ACTIVO PARA REASIGNARLO COMO PRINCIPAL*/
	public static final long REG_ACTIVO_INEXISTENTE_REASIGNARLO = 35;

	/*VERIFIQUE LA ENTIDAD YA TIENE REGISTRADO  ESTE CORREO ELECTRONICO, CAPTURE OTRO*/
	public static final long CORREO_DUPLICADO_ENTIDAD = 36;

	/*VERIFIQUE LA ENTIDAD YA TIENE REGISTRADO  ESTE DOMICILIO, CAPTURE OTRO*/
	public static final long DOMICILIO_DUPLICADO_ENTIDAD = 37;

	/*VERIFIQUE LA ENTIDAD YA TIENE REGISTRADO  ESTE TELEFONO, CAPTURE OTRO*/
	public static final long TELEFONO_DUPLICADO_ENTIDAD = 38;

	/*VERIFIQUE LA ENTIDAD YA TIENE REGISTRADO  ESTE CONTACTO CAPTURE OTRO*/
	public static final long CONTACTO_DUPLICADO_ENTIDAD = 39;

	/*VERIFIQUE LA ENTIDAD YA TIENE REGISTRADO  ESTE BENEFICIARIO CAPTURE OTRO*/
	public static final long BENEFICIARIO_DUPLICADO_ENTIDAD = 40;

	/*VERIFIQUE LA ENTIDAD YA TIENE REGISTRADO  ESTE FAMILIAR CAPTURE OTRO*/
	public static final long FAMILIAR_DUPLICADO_ENTIDAD = 41;

	/*VERIFIQUE LA ENTIDAD YA TIENE REGISTRADO  ESTE OTRO VINCULADO  CAPTURE OTRO*/
	public static final long VINCULADO_DUPLICADO_ENTIDAD = 42;

	/*VERIFIQUE LA ENTIDAD YA TIENE REGISTRADO  ESTE APODERADO  CAPTURE OTRO*/
	public static final long APODERADO_DUPLICADO_ENTIDAD = 43;

	/*VERIFIQUE LA ENTIDAD YA TIENE REGISTRADO  ESTE FUNCIONARIO  CAPTURE OTRO*/
	public static final long FUNCIONARIO_DUPLICADO_ENTIDAD = 44;

	/*VERIFIQUE LA ENTIDAD YA TIENE REGISTRADO  ESTE INTEGRANTE  CAPTURE OTRO*/
	public static final long INTEGRANTE_DUPLICADO_ENTIDAD = 45;

	/*NO HA SELECCIONADO LA ENTIDAD A QUIEN CORRESPONDEN LOS NEGOCIOS*/
	public static final long NEGOCIOS_SIN_IDENTIDAD = 46;

	/*ERROR INESPERADO %s*/
	public static final long ERROR_INESPERADO = 47;

	/*VERIFIQUE, NO HA SELECCIONADO UN DOMICILIO*/
	public static final long DOMICILIO_NO_SELECCIONADO = 48;

	/*VERIFIQUE, NO HA SELECCIONADO UN TELEFONO*/
	public static final long TELEFONO_NO_SELECCIONADO = 49;

	/*VERIFIQUE, NO HA SELECCIONADO UN CORREO ELECTRONICO*/
	public static final long CORREO_NO_SELECCIONADO = 50;

	/*VERIFIQUE, NO HA SELECCIONADO UN NEGOCIO*/
	public static final long NEGOCIO_NO_SELECCIONADO = 51;

	/*VERIFIQUE, NO HA SELECCIONADO EL REGISTRO-PERMISO*/
	public static final long REGISTRO_PERMISO_NO_SELECCIONADO = 52;

	/*VERIFIQUE, NO HA SELECCIONADO UN CONTACTO*/
	public static final long CONTACTO_NO_SELECCIONADO = 53;

	/*NO HA SELECCIONADO A QUIEN CORRESPONDEN LOS BENEFICIARIOS*/
	public static final long SELECCIONE_CORRESPONDENCIA_BENEFICIARIOS = 54;

	/*NO HA SELECCIONADO A QUIEN CORRESPONDEN LOS FAMILIARES*/
	public static final long SELECCIONE_CORRESPONDENCIA_FAMILIARES = 55;

	/*NO HA SELECCIONADO A QUIEN CORRESPONDEN LOS FUNCIONARIOS*/
	public static final long SELECCIONE_CORRESPONDENCIA_FUNCIONARIO = 56;

	/*VERIFIQUE, EL PORCENTAJE DEBE ESTAR EN EL RANGO DE 1-100*/
	public static final long PORCENTAJE_FUERA_RANGO = 57;

	/*VERIFIQUE, NO HA SELECCIONADO UN BENEFICIARIO*/
	public static final long SELECCIONE_BENEFICIARIO = 58;

	/*VERIFIQUE, NO HA SELECCIONADO UN FAMILIAR*/
	public static final long SELECCIONE_FAMILIAR = 59;

	/*NO HA SELECCIONADO A QUIEN CORRESPONDEN LOS INTEGRANTES DEL GRUPO SOLIDARIO*/
	public static final long SELECCIONE_INTEGRANTES_GRUPO_SOL = 60;

	/*VERIFIQUE, NO HA SELECCIONADO UN OTRO VINCULO*/
	public static final long SELECCIONAR_OTRO_VINCULO = 61;

	/*INDIQUE LA PROPIEDAD A CONSULTAR*/
	public static final long PROPIEDAD_CONSULTAR = 62;

	/*VERIFIQUE EL CAMPO FECHA HASTA  SELECCIONO UNA FECHA MENOR AL DIA ACTUAL.*/
	public static final long FECHA_HASTA_INCORRECTA = 63;

	/*VERIFIQUE, NO HA SELECCIONADO UN APODERADO*/
	public static final long SELECCIONE_APODERADO = 64;

	/*PRIMERO BUSQUE Y SELECCIONE A QUIEN PERTENECEN LOS PODERES*/
	public static final long SELECCIONE_PERTENENCIA_PODERES = 65;

	/*LA ENTIDAD ASIGNADA NO EXISTE*/
	public static final long ENTIDAD_ASIGNADA_NO_EXISTE = 66;

	/*VERIFIQUE, NO HA SELECCIONADO EL PODER*/
	public static final long PODER_NO_SELECCIONADO = 67;

	/*VERIFIQUE, NO HA SELECCIONADO LA IDENTIFICACION*/
	public static final long IDENTIFICACION_NO_SELECCIONADA = 68;

	/*VERIFIQUE EL CAMPO FECHA CONSTITUCION SELECCIONO UNA FECHA MAYOR AL DIA ACTUAL.*/
	public static final long FECHA_CONSTITUCION_INCORRECTA = 69;

	/*VERIFIQUE, EL TOTAL DE LAS ACCIONES DE LOS FUNCIONARIOS REGISTRADOS Y EL ACTUAL NO DEBEN REBASAR EL 100%*/
	public static final long ACCIONES_FUNCIONARIOS_SOBREPASAN = 70;

	/*VERIFIQUE, NO HA SELECCIONADO UN FUNCIONARIO*/
	public static final long PRIMERO_SELECCIONE_FUNCIONARIO = 71;

	/*VERIFIQUE, NO HA SELECCIONADO UN INTEGRANTE*/
	public static final long PRIMERO_SELECCIONE_INTEGRANTE = 72;

	/*LA BUSQUEDA DE PERSONAS NATURALES NO REGRESO RESULTADOS*/
	public static final long BUSQUEDA_PN_SIN_RESULTADOS = 73;

	/*SE ENCONTRO ERROR EN LA INFORMACION INGRESADA PARA LA PERSONA*/
	public static final long ERROR_VALIDAR_INFORMACION_PERSONA = 74;

	/*SE GENERO ERROR AL VALIDAR HOMONIMIA*/
	public static final long ERROR_VALIDAR_HOMONIMIA_PERSONA = 75;

	/*EL DATO DE LA ENTIDAD O EL TIPO DE ENTIDAD ESTAN VACIOS.*/
	public static final long FALLO_VALIDAR_DATOS_ENTIDAD_TIPOENTIDAD = 76;

	/*SE ENERO UN ERROR AL VALIDAR DATOS DEL CONYUGE*/
	public static final long ERROR_VALIDAR_CONYUGE = 77;

	/*GENERO ERROR AL VALIDAR DATOS DE NACIMIENTO*/
	public static final long ERROR_VALIDAR_DATOS_NACIMIENTO = 78;

	/*GENERO ERROR AL VALIDAR DATOS DE ESTADO CIVIL*/
	public static final long ERROR_VALIDAR_DATOS_EDOCIVIL = 79;

	/*GENERO ERROR AL VALIDAR LOS DATOS DE GRADO DE INSTRUCCION DE LA PERSONA*/
	public static final long ERROR_VALIDAR_DATOS_GRADOINSTRUCCION = 80;

	/*GENERO ERROR AL VALIDAR DATOS DE LA OCUPACION DE LA PERSONA*/
	public static final long ERROR_VALIDAR_DATOS_OCUPACION = 81;

	/*GENERO ERROR AL VALIDAR DATOS EMPRESARIALES DE LA PERSONA*/
	public static final long ERROR_VALIDAR_DATOS_EMPRESARIALES = 82;

	/*GENERO ERROR AL VALIDAR DATOS DE RESIDENCIA*/
	public static final long ERROR_VALIDAR_DATOS_RESIDENCIA = 83;

	/*GENERO ERROR AL VALIDAR DATOS DEL GIRO DEL NEGOCIO*/
	public static final long ERROR_VALIDAR_DATOS_GIRONEGOCIO = 84;

	/*GENERO ERROR AL VALIDAR DATOS DEL ENTE REGULADOR*/
	public static final long ERROR_VALIDAR_DATOS_ENTEREGULADOR = 85;

	/*GENERO ERROR AL GUARDA LOS DATOS MODIFICADOS DE LA PERSONA*/
	public static final long ERROR_MODIFICAR_PERSONA = 86;

	/*LA BUSQUEDA DE DOMICILIOS NO REGRESO RESULTADOS*/
	public static final long BUSQUEDA_DOMICILIOS_SIN_RESULTADOS = 87;

	/*GENERO UN ERROR LA BUSQUEDA DE DOMICILIOS*/
	public static final long ERROR_BUSCAR_DOMICILIOS = 88;

	/*GENERO ERROR AL VALIDAR LOS DATOS DEL DOMICILIO*/
	public static final long ERROR_VALIDAR_DATOS_DOMICILIOS = 89;

	/*GENERO ERROR AL CREAR UN NUEVO DOMICILIO*/
	public static final long ERROR_CREAR_DOMICILIO = 90;

	/*GENERO ERROR AL REVISAR EL ESTATUS DE LA PERSONA*/
	public static final long ERROR_REVISA_ESTATUS_ENTIDAD = 91;

	/*GENERO ERROR AL MODIFICAR EL DOMICILIO DEL CLIENTE*/
	public static final long ERROR_MODIFICAR_DOMICILIO = 92;

	/*GENERO ERROR AL VALIDAR DATOS PARA BAJA DE CLIENTE*/
	public static final long ERROR_VALIDAR_DATOS_BAJA = 93;

	/*GENERO ERROR AL BUSCAR LOS DOMICILIOS ACTIVOS DEL CLIENTE*/
	public static final long ERROR_CONTADOR_DOMICILIOS_ACTIVOS = 94;

	/*no encontro un domicilio activo para reasignarlo como principal*/
	public static final long DOMICILIO_ACTIVO_NO_ENCONTRADO = 95;

	/*GENERO ERROR AL VALIDAR LOS DATOS DE DESCRIPCION DE LA ENTIDAD*/
	public static final long FALLO_VALIDAR_DATOS_DESCRIPCION_ENTIDAD = 96;

	/*NO SE ENCONTRO LA DESCRIPCION*/
	public static final long ERROR_DESCRIPCION_ENTIDAD_NOENCONTRADA = 97;

	/*GENERO UN ERROR AL ELIMINAR EL DOMICILIO DE LA PERSONA*/
	public static final long ERROR_ELIMINAR_DOMICILIO = 98;

	/*GENERO UN ERROR AL ELIMINAR PERSONA*/
	public static final long ERROR_ELIMINAR_PERSONA = 99;

	/*GENERO ERROR AL VALIDAR LOS DATOS DEL TELEFONO*/
	public static final long ERROR_VALIDAR_DATOS_TELEFONO = 100;

	/*GENERO ERROR AL CREAR UN NUEVO TELEFONO*/
	public static final long ERROR_CREAR_TELEFONO = 101;

	/*LA BUSQUEDA DE TELEFONOS NO REGRESO RESULTADOS*/
	public static final long BUSQUEDA_TELEFONOS_SIN_RESULTADOS = 102;

	/*GENERO UN ERROR LA BUSQUEDA DE TELEFONOS*/
	public static final long ERROR_BUSCAR_TELEFONOS = 103;

	/*GENERO UN ERROR AL GUARDAR LOS DATOS MODIFICADOS DEL TELEFONO DE LA PERSONA*/
	public static final long ERROR_MODIFICAR_TELEFONO = 104;

	/*PRIMERO BUSQUE Y SELECCIONE EL TELEFONO*/
	public static final long PRIMERO_SELECCIONE_TELEFONO = 105;

	/*GENERO ERROR AL ELIMINAR EL TELEFONO DE LA PERSONA*/
	public static final long ERROR_ELIMINAR_TELEFONO = 106;

	/*NO SE ENCONTRO UN TELEFONO ACTIVO PARA REASIGNARLO COMO PRINCIPAL*/
	public static final long TELEFONO_ACTIVO_NO_ENCONTRADO = 107;

	/*PRIMERO BUSQUE Y SELECCIONE UN DOMICILIO*/
	public static final long PRIMERO_SELECCIONE_DOMICILIO = 108;

	/*LA BUSQUEDA DE CORREOS ELECTRONICOS NO REGRESO RESULTADOS*/
	public static final long BUSQUEDA_CORREOS_SIN_RESULTADOS = 109;

	/*GENERO ERROR LA BUSQUEDA DE CORREOS ELECTRONICOS*/
	public static final long ERROR_BUSCAR_CORREOS = 110;

	/*GENERO ERROR AL CREAR UN NUEVO CORREO ELECTRONICO*/
	public static final long ERROR_CREAR_CORREO = 111;

	/*GENERO ERROR AL VALIDAR LOS DATOS DEL CORREO ELECTRONICO*/
	public static final long ERROR_VALIDAR_DATOS_CORREO = 112;

	/*GENERO ERROR AL GUARDAR LOS DATOS MODIFICADOS DEL CORREO ELECTRONICO*/
	public static final long ERROR_MODIFICAR_CORREO = 113;

	/*GENERO ERROR AL ELIMINAR EL CORREO ELECTRONICO DE LA PERSONA*/
	public static final long ERROR_ELIMINAR_CORREO = 114;

	/*NO SE ENCONTRO UN CORREO ELECTRONICO ACTIVO PARA REASIGNARLO COMO PRINCIPAL*/
	public static final long CORREO_ACTIVO_NO_ENCONTRADO = 115;

	/*GENERO ERROR AL BUSCAR LOS DOMICILIOS ACTIVOS DE LA PERSONA*/
	public static final long ERROR_CONTADOR_CORREOS_ACTIVOS = 116;

	/*PRIMERO BUSQUE Y SELECCIONE UN CORREO ELECTRONICO*/
	public static final long PRIMERO_SELECCIONE_CORREO = 117;

	/*GENERO ERROR AL VALIDAR HOMONIMIA DEL NEGOCIO*/
	public static final long ERROR_VALIDAR_HOMONIMIA_NEGOCIO = 118;

	/*GENERO ERROR AL CREAR UN NUEVO NEGOCIO*/
	public static final long ERROR_CREAR_NEGOCIO = 119;

	/*SE ENCONTRO ERROR EN LA INFORMACION INGRESADA PARA EL NEGOCIO*/
	public static final long ERROR_VALIDAR_INFORMACION_NEGOCIO = 120;

	/*GENERO ERROR AL BUSCAR LOS NEGOCIOS ACTIVOS DE LA PERSONA*/
	public static final long ERROR_CONTADOR_NEGOCIOS_ACTIVOS = 121;

	/*GENERO ERROR AL BUSCAR LOS TELEFONOS ACTIVOS DE LA PERSONA*/
	public static final long ERROR_CONTADOR_TELEFONOS_ACTIVOS = 122;

	/*GENERO ERROR AL ELIMINAR EL NEGOCIO DE LA PERSONA*/
	public static final long ERROR_ELIMINAR_NEGOCIO = 123;

	/*GENERO ERROR AL GUARDAR LOS DATOS MODIFICADOS DEL NEGOCIO */
	public static final long ERROR_MODIFICAR_NEGOCIO = 124;

	/*LA BUSQUEDA DE NEGOCIOS NO REGRESO RESULTADOS*/
	public static final long BUSQUEDA_NEGOCIOS_SIN_RESULTADOS = 125;

	/*GENERO ERROR LA BUSQUEDA DE NEGOCIOS*/
	public static final long ERROR_BUSCAR_NEGOCIOS = 126;

	/*GENERO ERROR AL VALIDAR DATOS DE LA IDENTIFICACION*/
	public static final long ERROR_VALIDAR_DATOS_IDENTIFICACION = 127;

	/*GENERO ERROR AL CREAR UN NUEVO REGISTRO - PERMISO DEL NEGOCIO*/
	public static final long ERROR_CREAR_REGISTRO_PERMISO = 128;

	/*GENERO ERROR AL GUARDAR LOS DATOS MODIFICADOS DEL REGISTRO - PERMISO DEL NEGOCIO*/
	public static final long ERROR_MODIFICAR_REGISTRO_PERMISO = 129;

	/*GENERO ERROR AL VALIDAR DATOS DEL REGISTRO - PERMISO DEL NEGOCIO*/
	public static final long ERROR_VALIDAR_DATOS_REGISTRO_PERMISO = 130;

	/*LA BUSQUEDA DE REGISTROS - PERMISOS NO REGRESO RESULTADOS*/
	public static final long BUSQUEDA_REGISTRO_PERMISO_SIN_RESULTADOS = 131;

	/*SELECCIONE PRIMERO EL REGISTRO - PERMISO */
	public static final long PRIMERO_SELECCIONE_REGISTRO_PERMISO = 132;

	/*GENERO ERROR AL ELIMINAR LA IDENTIFICACION*/
	public static final long ERROR_ELIMINAR_IDENTIFICACION = 133;

	/*GENERO ERROR AL BUSCAR LAS IDENTIFICACIONES ACTIVAS*/
	public static final long ERROR_CONTADOR_IDENTIFICACIONES_ACTIVOS = 134;

	/*NO SE ENCONTRO UNA IDENTIFICACION ACTIVA PARA REASIGNAR*/
	public static final long IDENTIFICACION_ACTIVO_NO_ENCONTRADO = 135;

	/*LA BUSQUEDA DE IDENTIFICACIONES NO REGRESO RESULTADOS*/
	public static final long BUSQUEDA_IDENTIFICACIONES_SIN_RESULTADOS = 136;

	/*GENERO ERROR AL BUSCAR IDENTIFICACIONES*/
	public static final long ERROR_BUSCAR_IDENTIFICACIONES = 137;

	/*GENERO ERROR AL VALIDAR DATOS DEL CONTACTO*/
	public static final long ERROR_VALIDAR_DATOS_CONTACTO = 138;

	/*GENERO ERROR AL DAR DE ALTA UN NUEVO CONTACTO*/
	public static final long ERROR_CREAR_CONTACTO = 139;

	/*GENERO ERROR AL VALIDAR QUE NO EXISTA OTRO CONTACTO CON EL MISMO TIPO DE VINCULACION*/
	public static final long ERROR_VALIDAR_DUPLICIDAD_VINCULACION = 140;

	/*VERIFIQUE, LA PERSONA A QUIEN SE LE ESTA ASOCIANDO ESTE CONTACTO ES EL MISMO.*/
	public static final long CONTACTO_ES_EL_MISMO = 141;

	/*LA BUSQUEDA DE CONTACTOS NO REGRESO RESULTADOS*/
	public static final long BUSQUEDA_CONTACTOS_SIN_RESULTADOS = 142;

	/*GENERO ERROR AL BUSCAR VINCULACIONES*/
	public static final long ERROR_BUSCAR_VINCULACIONES = 143;

	/*LA BUSQUEDA DE VINCULACIONES NO GENERO RESULTADOS*/
	public static final long BUSQUEDA_VINCULACIONES_SIN_RESULTADOS = 144;

	/*SELECCIONE PRIMERO EL CONTACTO*/
	public static final long PRIMERO_SELECCIONE_CONTACTO = 145;

	/*GENERO ERROR AL MODIFICAR EL CONTACTO*/
	public static final long ERROR_MODIFICAR_CONTACTO = 146;

	/*GENERO ERROR AL BUSCAR LAS VINCULACIONES ACTIVAS*/
	public static final long ERROR_CONTADOR_VINCULACIONES_ACTIVOS = 147;

	/*GENERO ERROR AL ELIMINAR LA VINCULACION*/
	public static final long ERROR_ELIMINAR_VINCULACION = 148;

	/*GENERE ERROR AL MODIFICAR EL BENEFICIARIO*/
	public static final long ERROR_MODIFICAR_BENEFICIARIO = 149;

	/*SELECCIONE PRIMERO EL BENEFICIARIO*/
	public static final long PRIMERO_SELECCIONE_BENEFICIARIO = 150;

	/*LA BUSQUEDA DE BENEFICIARIOS NO GENERO RESULTADOS*/
	public static final long BUSQUEDA_BENEFICIARIOS_SIN_RESULTADOS = 151;

	/*GENERO ERROR AL DAR DE ALTA UN NUEVO BENEFICIARIO*/
	public static final long ERROR_CREAR_BENEFICIARIO = 152;

	/*GENERO ERROR AL VALIDAR DATOS DEL FAMILIAR*/
	public static final long ERROR_VALIDAR_DATOS_FAMILIAR = 153;

	/*GENERO ERROR AL VALIDAR DATOS DEL BENEFICIARIO*/
	public static final long ERROR_VALIDAR_DATOS_BENEFICIARIO = 154;

	/*VERIFIQUE, LA PERSONA A QUIEN SE LE ESTA ASOCIANDO EL BENEFICIARIO, POR QUE SON LA MISMA PERSONA*/
	public static final long BENEFICIARIO_ES_EL_MISMO = 155;

	/*VERIFIQUE, LA PERSONA A QUIEN SE LE ESTA ASOCIANDO EL FAMILIAR, SON LA MISMA PERSONA*/
	public static final long FAMILIAR_ES_EL_MISMO = 156;

	/*GENERO ERROR AL DAR DE ALTA UN NUEVO FAMILIAR*/
	public static final long ERROR_CREAR_FAMILIAR = 157;

	/*GENERO ERROR AL MODIFICAR EL FAMILIAR*/
	public static final long ERROR_MODIFICAR_FAMILIAR = 158;

	/*LA BUSQUEDA DE FAMILIARES NO GENERO RESULTADOS*/
	public static final long BUSQUEDA_FAMILIAR_SIN_RESULTADOS = 159;

	/*SELECCIONE PRIMERO AL FAMILIAR*/
	public static final long PRIMERO_SELECCIONE_FAMILIAR = 160;

	/*GENERO ERROR AL VALIDAR DATOS DEL OTRO VINCULO*/
	public static final long ERROR_VALIDAR_DATOS_OTRO_VINCULO = 161;

	/*GENERO ERROR AL DAR DE ALTA UN NUEVO OTRO VINCULO*/
	public static final long ERROR_CREAR_OTRO_VINCULO = 162;

	/*VERIFIQUE, LA PERSONA A QUIEN SE LE ESTA ASOCIANDO EL OTRO VINCULO*/
	public static final long OTRO_VINCULO_ES_EL_MISMO = 163;

	/*LA BUSQUEDA DE OTROS VINCULOS NO GENERO RESULTADOS*/
	public static final long BUSQUEDA_OTROS_VINCULOS_SIN_RESULTADOS = 164;

	/*SELECCIONE PRIMERO EL OTRO VINCULO*/
	public static final long PRIMERO_SELECCIONE_OTRO_VINCULO = 165;

	/*GENERO ERROR AL MODIFICAR EL OTRO VINCULO*/
	public static final long ERROR_MODIFICAR_OTRO_VINCULO = 166;

	/*VERIFIQUE LA ENTIDAD YA TIENE REGISTRADO  ESTA VINCULACION, CAPTURE OTRO*/
	public static final long VINCULACION_DUPLICADO_ENTIDAD = 167;

	/*LA BUSQUEDA DE APODERADOS NO REGRESO RESULTADOS*/
	public static final long BUSQUEDA_APODERADO_SIN_RESULTADOS = 168;

	/*SELECCIONE PRIMERO AL APODERADO*/
	public static final long PRIMERO_SELECCIONE_APODERADO = 169;

	/*GENERO ERROR AL DAR DE ALTA UN NUEVO APODERADO*/
	public static final long ERROR_CREAR_APODERADO = 170;

	/*GENERO ERROR AL MODIFICAR APODERADO*/
	public static final long ERROR_MODIFICAR_APODERADO = 171;

	/*VERIFIQUE, LA PERSONA A QUIEN SE LE ESTA ASOCIANDO EL APODERADO ES LA MISMA*/
	public static final long APODERADO_ES_EL_MISMO = 172;

	/*GENERO ERROR AL VALIDAR DATOS DEL APODERADO*/
	public static final long ERROR_VALIDAR_DATOS_APODERADO = 173;

	/*GENERO ERROR AL VALIDAR DATOS DEL PODER*/
	public static final long ERROR_VALIDAR_DATOS_PODER = 174;

	/*GENERO ERROR AL DAR DE ALTA UN NUEVO PODER*/
	public static final long ERROR_CREAR_PODER = 175;

	/*GENERO ERROR AL ELIMINAR EL PODER*/
	public static final long ERROR_ELIMINAR_PODER = 176;

	/*GENERO ERROR AL MODIFICAR EL PODER*/
	public static final long ERROR_MODIFICAR_PODER = 177;

	/*SELECCIONE PRIMERO EL PODER*/
	public static final long PRIMERO_SELECCIONE_PODER = 178;

	/*LA BUSQUEDA DE PODERES NO REGRESO RESULTADOS*/
	public static final long BUSQUEDA_PODER_SIN_RESULTADOS = 179;

	/*GENERO ERROR AL BUSCAR PODERES*/
	public static final long ERROR_BUSCAR_PODER = 180;

	/*GENERO ERROR AL VALIDAR DATOS PARA GENERAR EL LISTADO*/
	public static final long FALLO_VALIDAR_LISTADO = 181;

	/*GENERO ERROR AL VALIDAR LOS DATOS PARA GENERAR EL LISTADO DE PODERES*/
	public static final long FALLO_VALIDAR_LISTADO_PODERES = 182;

	/*GENERO ERROR AL VALIDAR LOS DATOS PARA GENERAR EL LISTADO*/
	public static final long ERROR_VALIDAR_LISTADO_GRUPO_ECONOMICO = 183;

	/*LA BUSQUEDA DE GRUPO ECONOMICO NO REGRESO RESULTADOS*/
	public static final long BUSQUEDA_GRUPO_ECONOMICO_SIN_RESULTADOS = 184;

	/*GENERO ERROR AL BUSCAR DATOS DEL GRUPO ECONOMICO*/
	public static final long ERROR_BUSCAR_GRUPO_ECONOMICO = 185;

	/*GENERO ERROR AL VALIDAR DATOS DEL FUNCIONARIO*/
	public static final long ERROR_VALIDAR_DATOS_FUNCIONARIO = 186;

	/*VERIFIQUE, LA PERSONA A QUIEN SE LE ESTA ASOCIANDO EL FUNCIONARIO ES LA MISMA PERSONA*/
	public static final long FUNCIONARIO_ES_EL_MISMO = 187;

	/*GENERO ERROR AL DAR DE ALTA UN NUEVO FUNCIONARIO*/
	public static final long ERROR_CREAR_FUNCIONARIO = 188;

	/*GENERO ERROR AL DAR DE ALTA UN NUEVO INTEGRANTE*/
	public static final long ERROR_CREAR_INTEGRANTE = 189;

	/*VERIFIQUE, LA PERSONA A QUIEN SE LE ESTA ASOCIANDO EL INTEGRANTE SON LA MISMA PERSONA*/
	public static final long INTEGRANTE_ES_EL_MISMO = 190;

	/*GENERO ERROR AL VALIDAR LOS DATOS DEL INTEGRANTE*/
	public static final long ERROR_VALIDAR_DATOS_INTEGRANTE = 191;

	/*GENERO ERROR AL MODIFICAR EL FUNCIONARIO*/
	public static final long ERROR_MODIFICAR_FUNCIONARIO = 192;

	/*GENERO ERROR AL MODIFICAR EL INTEGRANTE*/
	public static final long ERROR_MODIFICAR_INTEGRANTE = 193;

	/*LA BUSQUEDA DE INTEGRANTES NO REGRESO RESULTADOS*/
	public static final long BUSQUEDA_INTEGRANTE_SIN_RESULTADOS = 194;

	/*la busqueda de FUNCIONARIOS no regreso resultaDOS*/
	public static final long BUSQUEDA_FUNCIONARIO_SIN_RESULTADOS = 195;

	/*GENRO ERROR AL DAR DE ALTA UNA PERSONA JURIDICA*/
	public static final long ERROR_CREAR_PERSONA_JURIDICA = 196;

	/*GENERO ERROR EN LA INFORMACION INGRESADA PARA LA PERSONA JURIDICA*/
	public static final long ERROR_VALIDAR_INFORMACION_PERSONA_JURIDICA = 197;

	/*GENERO UN ERROR AL ACTUALIZAR LOS DATOS DE LA PERSONA JURIDICA*/
	public static final long ERROR_ACTUALIZAR_PERSONA_JURIDICA = 198;

	/*GENERO UN ERROR AL VALIDAR LOS DATOS DE ENTIDAD EXTERNA*/
	public static final long ERROR_VALIDAR_DATOS_ENTIDAD_EXTERNA = 199;

	/*SE ENCONTRO ERROR AL VALIDAR LA HOMONIMIA DE LA PERSONA JURIDICA*/
	public static final long ERROR_VALIDAR_HOMONIMIA_PERSONA_JURIDICA = 200;

	/*GENERO UN ERROR AL ACTUALIZAR LOS DATOS DE LA PERSONA NATURAL*/
	public static final long ERROR_ACTUALIZAR_PERSONA_NATURAL = 201;

	/*GENERO UN ERROR AL BUSCAR DATOS DE LA PERSONA JURIDICA*/
	public static final long ERROR_BUSCAR_PERSONA_JURIDICA = 202;

	/*GENERO UN ERROR AL BUSCAR DATOS DE LA PERSONA NATURAL*/
	public static final long ERROR_BUSCAR_PERSONA_NATURAL = 203;

	/*GENERO UN ERROR AL BUSCAR PERSONAS*/
	public static final long ERROR_BUSCAR_PERSONAS = 204;

	/*GENERO ERROR AL MODIFICAR LA PERSONA JURIDICA*/
	public static final long ERROR_MODIFICAR_PERSONA_JURIDICA = 205;

	/*LA BUSQUEDA DE PERSONAS JURIDICAS NO REGRESO RESULTADOS*/
	public static final long BUSQUEDA_PJ_SIN_RESULTADOS = 206;

	/*LA BUSQUEDA DE LA PERSONA NO REGRESO RESULTADOS*/
	public static final long BUSQUEDA_PERSONA_SIN_RESULTADOS = 207;

	/*GENERO ERROR AL MODIFICAR EL GRUPO SOLIDARIO*/
	public static final long ERROR_MODIFICAR_PERSONA_GRUPO_SOLIDARIO = 208;

	/*LA BUSQUEDA DE GRUPOS SOLIDARIOS NO REGRESO RESULTADOS*/
	public static final long BUSQUEDA_GRUPO_SOLIDARIO_SIN_RESULTADOS = 209;

	/*PRIMERO SELECCIONE EL GRUPO SOLIDARIO*/
	public static final long PRIMERO_SELECCIONE_PERSONA_GRUPO_SOLIDARIO = 210;

	/*GENERO ERROR AL DAR DE ALTA UN NUEVO GRUPO SOLIDARIO*/
	public static final long ERROR_CREAR_PERSONA_GRUPO_SOLIDARIO = 211;

	/*GENERO UN ERROR AL ACTUALIZAR LOS DATOS DEL GRUPO SOLIDARIO*/
	public static final long ERROR_ACTUALIZAR_PERSONA_GRUPO_SOLIDARIO = 212;

	/*GENERO UN ERROR AL VALIDAR LA HOMONIMIA DEL GRUPO SOLIDARIO*/
	public static final long ERROR_VALIDAR_HOMONIMIA_PERSONA_GRUPO_SOLIDARIO = 213;

	/*GENERO ERROR AL VALIDAR LOS DATOS DEL GRUPO SOLIDARIO*/
	public static final long ERROR_VALIDAR_INFORMACION_PERSONA_GRUPO_SOLIDARIO = 214;

	/*GENERO UN ERROR AL BUSCAR GRUPO SOLIDARIO*/
	public static final long ERROR_BUSCAR_PERSONA_GRUPO_SOLIDARIO = 215;

	/*BUSQUEDA_NO_GENERO_RESULTADOS*/
	public static final long BUSQUEDA_NO_GENERO_RESULTADOS = 216;

	/*ERROR_CREAR_IDENTIFICACION*/
	public static final long ERROR_CREAR_IDENTIFICACION = 217;

	/*ERROR_MODIFICAR_IDENTIFICACION*/
	public static final long ERROR_MODIFICAR_IDENTIFICACION = 218;

	/*Verifique, No ha seleccionado el cliente a quien actualizara sus datos actuales.*/
	public static final long SELECCIONE_CLIENTE = 219;

	/*verifique, la entidad ya tiene registrado  este nombre capture otro*/
	public static final long otro_nombre = 220;

	/*Seleccionar el tipo de cliente.*/
	public static final long SIN_TIPO_CLIENTE = 220;

	/*Verifique, el nombre esta siendo utilizado por el cliente numero: ####, Desea continuar?*/
	public static final long duplicidad_nombre = 221;

	/*CAMPO_GRADO_INSTRUCCION_INCORRECTO*/
	public static final long CAMPO_GRADO_INSTRUCCION_INCORRECTO = 222;

	/*CAMPO_OFICIO_PROFESION_INCORRECTO*/
	public static final long CAMPO_OFICIO_PROFESION_INCORRECTO = 223;

	/*CAMPO_LUGAR_NACIMIENTO_VACIO*/
	public static final long CAMPO_LUGAR_NACIMIENTO_VACIO = 224;

	/*CAMPO_PAIS_NACIMIENTO_INCORRECTO*/
	public static final long CAMPO_PAIS_NACIMIENTO_INCORRECTO = 225;

	/*CAMPO_ESTADO_CIVIL_INCORRECTO*/
	public static final long CAMPO_ESTADO_CIVIL_INCORRECTO = 226;

	/*CAMPO_GIRO_NEGOCIO_INCORRECTO*/
	public static final long CAMPO_GIRO_NEGOCIO_INCORRECTO = 227;

	/*CAMPO_OCUPACION_INCORRECTO*/
	public static final long CAMPO_OCUPACION_INCORRECTO = 228;

	/*CAMPO_ENTIDAD_EXTERNA_VACIO*/
	public static final long CAMPO_ENTIDAD_EXTERNA_VACIO = 229;

	/*CAMPO_PAIS_RESIDENCIA_INCORRECTO*/
	public static final long CAMPO_PAIS_RESIDENCIA_INCORRECTO = 231;

	/*CAMPO_CLIENTE_EMPRESARIAL_INCORRECTO*/
	public static final long CAMPO_CLIENTE_EMPRESARIAL_INCORRECTO = 232;

	/*CAMPO_ENTE_REGULADOR_INCORRECTO*/
	public static final long CAMPO_ENTE_REGULADOR_INCORRECTO = 233;

	/*CAMPO_FECHA_NACIMIENTO_VACIA*/
	public static final long CAMPO_FECHA_NACIMIENTO_VACIA = 234;

	/*No tiene identificacion principal*/
	public static final long SIN_IDENTIFICACION_PPAL = 235;

	/*Verifique, genero invalido (F = femenino o M=masculino)*/
	public static final long GENERO_INVALIDO = 236;

	/*ERROR_VALIDAR_IDENTIFICACION_PRINCIPAL*/
	public static final long ERROR_VALIDAR_IDENTIFICACION_PRINCIPAL = 237;

	/*El nombre que esta capturando ya esta registrado o tiene un homonimo, desea continuar?*/
	public static final long NOMBRE_DUPLICADO = 238;

	/*ERROR_BUSCAR_IDENTIFICACION_PRINCIPAL*/
	public static final long ERROR_BUSCAR_IDENTIFICACION_PRINCIPAL = 239;

	/*ERROR_ACTUALIZAR_DATOS_ACTIVIDAD_ECONOMICA*/
	public static final long ERROR_ACTUALIZAR_DATOS_ACTIVIDAD_ECONOMICA = 240;

	/*ERROR_ACTUALIZAR_DATOS_REGISTRALES_NOTARIALES*/
	public static final long ERROR_ACTUALIZAR_DATOS_REGISTRALES_NOTARIALES = 241;

	/*ERROR_ACTUALIZAR_DATOS_RESIDENCIA*/
	public static final long ERROR_ACTUALIZAR_DATOS_RESIDENCIA = 242;

	/*ERROR_ACTUALIZAR_DATOS_ENTE_REGULADOR*/
	public static final long ERROR_ACTUALIZAR_DATOS_ENTE_REGULADOR = 243;

	/*ERROR_ACTUALIZAR_DATOS_EMPRESARIALES*/
	public static final long ERROR_ACTUALIZAR_DATOS_EMPRESARIALES = 244;

	/*ERROR_ACTUALIZAR_DATOS_ENTIDAD_EXTRANJERA*/
	public static final long ERROR_ACTUALIZAR_DATOS_ENTIDAD_EXTRANJERA = 245;

	/*ERROR_ACTUALIZAR_CONYUGE*/
	public static final long ERROR_ACTUALIZAR_CONYUGE = 246;

	/*ERROR_ACTUALIZAR_DATOS_NACIMIENTO*/
	public static final long ERROR_ACTUALIZAR_DATOS_NACIMIENTO = 247;

	/*ERROR_ACTUALIZAR_ESTADO_CIVIL*/
	public static final long ERROR_ACTUALIZAR_ESTADO_CIVIL = 248;

	/*ERROR_ACTUALIZAR_OCUPACION*/
	public static final long ERROR_ACTUALIZAR_OCUPACION = 249;

	/*ERROR_ACTUALIZAR_GRADO_INSTRUCCION*/
	public static final long ERROR_ACTUALIZAR_GRADO_INSTRUCCION = 250;

	/*Verifique, el total del porcentaje de los beneficiarios registrados y el actual no deben rebasar el 100%*/
	public static final long PORCENTAJE_BENEFICIO_EXCEDIDO = 251;

	/*CAMPO_BUSQUEDA_UNICO*/
	public static final long CAMPO_BUSQUEDA_UNICO = 252;

	/*ERROR_CONECTAR_WS*/
	public static final long ERROR_CONECTAR_WS = 253;

	/*ERROR_CONSUMIR_WS*/
	public static final long ERROR_CONSUMIR_WS = 254;

	/*ERROR_CREAR_GRUPO*/
	public static final long ERROR_CREAR_GRUPO = 255;

	/*VERIFIQUE LA ENTIDAD, YA TIENE REGISTRADO ESTE AVAL, CAPTURE OTRO*/
	public static final long AVAL_DUPLICADO_ENTIDAD = 256;

	/*VERIFIQUE LA ENTIDAD, YA TIENE REGISTRADO ESTE GARANTE, CAPTURE OTRO*/
	public static final long GARANTE_DUPLICADO_ENTIDAD = 257;

	/*ERROR_PROCESAR_XML*/
	public static final long ERROR_PROCESAR_XML = 258;

	/*GENERO ERROR AL DAR DE ALTA UN NUEVO AVAL*/
	public static final long ERROR_CREAR_AVAL = 261;

	/*ERROR EL VINCULADO ES LA MISMA PERSONA*/
	public static final long ERROR_AVAL_ES_EL_MISMO = 262;

	/*ERROR AL VALIDAR LOS DATOS DEL AVAL*/
	public static final long ERROR_VALIDAR_DATOS_AVAL = 263;

	/*ERROR AL VALIDAR LOS DATOS DEL GARANTE*/
	public static final long ERROR_VALIDAR_DATOS_GARANTE = 264;

	/*ERROR EL GARANTE ES LA MISMA PERSONA*/
	public static final long ERROR_GARANTE_ES_EL_MISMO = 265;

	/*EROR AL CREAR GARANTE*/
	public static final long ERROR_CREAR_GARANTE = 266;

	/*ERROR LA PERSONA VINCULADA ESTA DADA DE BAJA*/
	public static final long ERROR_PERSONA_VINCULADA_INACTIVA = 267;

	/*ERROR AL OBTENER EL LISTADO DE LOS VINCULADOS*/
	public static final long ERROR_OBTENER_LISTADO_VINCULADOS = 268;

	/*ERROR AL DAR DE BAJA AVAL*/
	public static final long ERROR_BAJA_AVAL = 269;

	/*ERROR AL DAR DE BAJA EL GARANTE*/
	public static final long ERROR_BAJA_GARANTE = 270;

	/*ERROR AL OBTENER LOS DATOS DE LA PERSONA*/
	public static final long ERROR_OBTENER_DATOS_MAESTROPERSONA = 271;

	/*ERROR AL OBTENER DATOS DEL DOMICILIO PRINCIPAL*/
	public static final long ERROR_OBTENER_DATOS_DOMICILIO_PPAL = 272;

	/*ERROR AL OBTENER TIPO IDENTIFICACION*/
	public static final long ERROR_OBTENER_TIPO_IDENTIFICACION = 273;

	/*ERROR EN CONSULTA IDENTIFICACION PRINCIPAL PERSONA*/
	public static final long ERR_CONSULTA_IDE_PPAL_PERSONA = 274;

	/*SELECCIONE PERSONA*/
	public static final long SELECCIONE_PERSONA = 275;

	/*USUARIO SIN EMPRESA ASIGNADA*/
	public static final long USUARIO_SIN_EMPRESA_ASIG = 276;

	/*ERROR VALIDAR PRESTAMOS PERSONAS*/
	public static final long ERR_VALIDAR_PRESTAMOS_PERSONAS = 277;

	/*ERROR EN PRESTAMOS PERSONAS*/
	public static final long ERR_PRESTAMOS_PERSONAS = 278;

	/*ERROR EN VALIDA CONSULTA DATOS PERSONA*/
	public static final long ERR_VALIDA_CONS_DATOS_PERSONAS = 279;

	/*CLAVE DEL CONCEPTO VACIA*/
	public static final long CVE_CONCEPTO_VACIA = 280;

	/*CLAVE DEL CONCEPTO NO EXISTE*/
	public static final long CVE_CONCEPTO_NO_EX = 281;

	/*EL CONCEPTO NO EXISTE*/
	public static final long CONCEPTO_NO_EX = 282;

	/*ERROR EN CONSULTA DATOS PERSONA*/
	public static final long ERR_CONSULTA_DATOS_PERSONA = 283;

	/*NO EXISTE CLIENTE*/
	public static final long NO_EX_CLIENTE = 284;

	/*VALOR DEL CONCEPTO VACIO*/
	public static final long VALOR_CONCEPTO_VACIO = 285;

	/*ERROR EN ACTUALIZA DATOS PERSONA*/
	public static final long ERR_ACTUALIZA_DATOS_PERSONA = 286;

	/*EL NEGOCIO ESTA ASOCIADO A UNA SOLICITUD*/
	public static final long NEGOCIO_ESTA_ASOCIADO_A_SOLICITUD = 287;

	/*ERROR EXISTE ASOCIACION  A UN PRESTAMO*/
	public static final long ERROR_ENTIDAD_ASOCIADA_PRESTAMO = 288;

	/*ERROR EXISTE ASOCIACION A UNA GARANTIA*/
	public static final long ERROR_ENTIDAD_ASOCIADA_GARANTIAS = 289;

	/*ERROR EXISTE ASOCIACION  A UNA SOLICITUD*/
	public static final long ERROR_ENTIDAD_ASOCIADA_SOLICITUD = 290;

	/*EROR AL CREAR  CENTRO DE TRABAJO*/
	public static final long ERROR_CREAR_CENTRO_TRABAJO = 291;

	/*ERROR AL VALIDAR DATOS DEL CENTRO DE TRABAJO*/
	public static final long ERROR_VALIDAR_DATOS_CENTRO_TRABAJO = 292;

	/*ERROR AL BUSCAR DATOS NEGOCIO*/
	public static final long ERROR_BUSCAR_DATOS_NEGOCIO = 293;

	/*EL CENTRO DE TRABAJO NO EXISTE*/
	public static final long CENTRO_TRABAJO_NO_EXISTE = 294;

	/*ERROR AL MODIFICAR CENTRO TRABAJO*/
	public static final long ERROR_MODIFICAR_CENTRO_TRABAJO = 295;

	/*GENERO ERROR AL BUSCAR LOS CENTROS DE TRABAJO ACTIVOS DE LA PERSONA*/
	public static final long ERROR_CONTADOR_CENTROS_TRABAJO_ACTIVOS = 296;

	/*CENTRO DE TRABAJO ESTA ASOCIADO A UNA SOLICITUD*/
	public static final long CENTRO_DE_TRABAJO_ESTA_ASOCIADO_A_SOLICITUD = 297;

	/*ERROR AL DAR DE BAJA CENTRO TRABAJO*/
	public static final long ERROR_BAJA_CENTRO_TRABAJO = 298;

	/*BUSQUEDA CENTRO DE TRABAJO SIN RESULTADOS*/
	public static final long BUSQUEDA_CENTRO_TRABAJO_SIN_RESULTADOS = 299;

	/*SELECCIONE UN CENTRO DE TRABAJO*/
	public static final long SELECCIONE_CENTRO_TRABAJO = 300;

	/*ERROR AL BUSCAR CENTRO TRABAJO*/
	public static final long ERROR_BUSQUEDA_CENTRO_TRABAJO = 301;

	/*ERROR_BORRAR_PERSONA_ES_TITULAR_SOLICITUD*/
	public static final long ERROR_BORRAR_PERSONA_ES_TITULAR_SOLICITUD = 302;

	/*ERROR_BORRAR_PERSONA_ES_TITULAR_PRESTAMO*/
	public static final long ERROR_BORRAR_PERSONA_ES_TITULAR_PRESTAMO = 303;

	/*ERROR_BORRAR_PERSONA_ES_TITULAR_CUENTA_AHORRO*/
	public static final long ERROR_BORRAR_PERSONA_ES_TITULAR_CUENTA_AHORRO = 304;

	/*ERROR_BORRAR_PERSONA_ES_PROPIETARIO_GARANTIA*/
	public static final long ERROR_BORRAR_PERSONA_ES_PROPIETARIO_GARANTIA = 305;

	/*ERROR_BORRAR_PERSONA_ES_PROPIETARIO_DACION_PAGO*/
	public static final long ERROR_BORRAR_PERSONA_ES_PROPIETARIO_DACION_PAGO = 306;

	/*ERROR_BORRAR_PERSONA_ES_CONYUGE*/
	public static final long ERROR_BORRAR_PERSONA_ES_CONYUGE = 307;
	
	/*CONCEPTO DE OPERACION NO EXISTE AL ACTUALIZAR DATOS DE PERSONA*/
	public static final long CON_OP_NO_EX_ACT_DATOS_PERSONA = 308;

	/*ERROR INESPERADO AL ACTUALIZAR DATOS DE PERSONA*/
	public static final long EI_ACTUALIZAR_DATOS_PERSONA = 309;

	/*SELECCIONE CONCEPTO DE OPERACIONA PARA ACTUALIZAR DATOS PERSONA*/
	public static final long SEL_CONCEPTO_OP_ACT_DATOS_PERSONA = 310;

	/*ERROR INESPERADO AL VALIDAR INFORMACION PARA ACTUALIZAS DATOS PERSONA*/
	public static final long EI_VALIDAR_ACTUALIZA_DATOS_PERSONA = 311;

	/*ERROR AL OBTENER IDENTIFICACION PERSONA ID VACIO*/
	public static final long ERR_VALIDAR_OBTIENE_TIPO_IDENTIFICACION_TIPO_PERSONA_PERSONA_ID_VACIO = 312;

	/*ERROR AL OBTENER IDENTIFICACION CVE DEL TIPO IDENTIFICACION VACIO*/
	public static final long ERR_VALIDAR_OBTIENE_TIPO_IDENTIFICACION_TIPO_PERSONA_CLAVE_ID_VACIO = 313;

	/*ERROR AL OBTENER IDENTIFICACION TIPO PERSONA VACIO*/
	public static final long ERR_VALIDAR_OBTIENE_TIPO_IDENTIFICACION_TIPO_PERSONA_VACIO = 314;
	
	/*ERROR AL OBTENER IDENTIFICACION EMPRESA VACIA*/
	public static final long ERR_VALIDAR_OBTIENE_TIPO_IDENTIFICACION_TIPO_PERSONA_EMPRESA_ID_VACIO = 315;

	/*ERROR INESPERADO AL OBTENER IDENTIFICACION POR TIPO PERSONA*/
	public static final long EI_VALIDAR_OBTIENE_TIPO_IDENTIFICACION_TIPO_PERSONA = 316;

	/*TIPO IDENTIFICACION DADA DE BAJA*/
	public static final long TIPO_IDENTIFICACION_DADA_BAJA = 317;

	/*ERROR INESPERADO EN OBTIENE TIPO IDENTIFICACION POR TIPO PERSONA*/
	public static final long EI_OBTIENE_TIPO_IDENTIFICACION_TIPO_PERSONA = 318;

	/*ERROR AL VALIDAR BUSQUEDA DE PERSONA POR CONCEPTO VALOR NO ESPECIFICADO*/
	public static final long ERR_VAL_BUS_PERSONA_X_CONCEPTO_VALOR_VACIO = 319;

	/*ERROR INESPERADO AL VALIDAR BUSQUEDA DE PERSONA POR CONCEPTO*/
	public static final long EI_VALIDAR_BUSQUEDA_PERSONA_X_CONCEPTO = 320;
	
	/*ERROR INESPERADO EN BUSCAR PERSONA POR CONCEPTO*/
	public static final long EI_BUSCAR_PERSONA_CONCEPTO = 321;
	
	/*Regla %s*/
	public static final long REGLA_NEGOCIO = 322;
	
	/*CAPTURE NOMBRE */
	public static final long CAPTURE_NOMBRE = 323;

	/*ERROR INESPERADO AL BUSCAR PERSONA POR NOMBRE*/
	public static final long EI_BUSCAR_PERSONA_POR_NOMBRE = 324;

	/*ERROR INESPERADO EN ACTUALIZA PRESTAMOS*/
	public static final long EI_ACTUALIZA_PRESTAMOS_PERSONAS = 325;
	
	/*CENTRO DE TRABAJO YA EXISTE*/
	public static final long YA_EXISTE_CT = 326;
	
	/*EL DUENO ES LA MISMA PERSONA SELECCIONADA*/
	public static final long ERR_DUENO_MISMO_CLIENTE = 327;
	
	/*CAMPO ENTIDAD FEDERATIVA REQUERIDO*/
	public static final long ERR_ENT_FED_REQ = 328;
	
	/*FORMATO INVALIDO DE  IDENTIFICACION*/
	public static final long FORMATO_INVALIDO = 329;
	
	/*EL NUMERO DE NOMINA YA ESTÁ ASIGNADO A OTRA PERSONA EN EL CENTRO DE TRABAJO*/
	public static final long NUM_EMPLEADO_EXISTE = 330;

	/*ERROR INESPERADO AL VALIDAR NUMERO DE NOMINA*/
	public static final long EI_VALIDAR_NUMERO_EMPLEADO = 331;


	public static HashMap<Long, String> descError = new HashMap<Long, String>();

	static {
		
		descError.put(ERR_ENT_FED_REQ,"CAMPO ENTIDAD FEDERATIVA REQUERIDO");
		descError.put(PERSONA_RESGISTRADA_HOMONIMO,"LA PERSONA YA ESTA REGISTRADA O TIENE UN HOMONIMO.DESEA CONTINUAR?");
		descError.put(PRIMERO_SELECCIONE_PERSONA_NAT,"PRIMERO BUSQUE Y SELECCIONE UNA PERSONA NATURAL");
		descError.put(PERSONA_TIENE_CONYUGE_VINCULADO,"LA PERSONA SELECCIONADA YA TIENE UN CONYUGE VINCULADO, SELECCIONAR OTRA");
		descError.put(NEGOCIO_REGISTRADO_HOMONIMO,"EL NEGOCIO YA ESTA REGISTRADO O TIENE UN HOMONIMO, DESEA CONTINUAR?");
		descError.put(CONYUGUE_ES_EL_MISMO,"VERIFIQUE,LA PERSONA A QUIEN SE LE ESTA ASOCIANDO CONYUGE ES LA MISMA PERSONA QUE EL CONYUGE SELECCIONADO");
		descError.put(PRIMERO_SELECCIONE_NEGOCIO,"PRIMERO BUSQUE Y SELECCIONE UN NEGOCIO");
		descError.put(SELECCIONE_ENTIDAD_BAJA,"PRIMERO BUSQUE Y SELECCIONE LA ENTIDAD QUE DESEA DAR DE BAJA");
		descError.put(CAPTURE_CAMPOS_REQUERIDOS,"CAMPO %s REQUERIDO");
		descError.put(FECHAS_INVERTIDAS,"VERIFIQUE, LA SECUENCIA DE LAS FECHAS CAPTURADAS ESTAN INVERTIDAS");
		descError.put(CORREO_INVALIDO,"VERIFIQUE, LA ESTRUCTURA DEL CORREO ES INVALIDA");
		descError.put(PERSONA_ESTATUS_BAJA,"VERIFIQUE, LA PERSONA SELECCIONADA TIENE ESTATUS BAJA");
		descError.put(SELECCIONE_TIPO_BUSQUEDA,"VERIFIQUE, DEBE SELECCIONAR UN CRITERIO DEL LISTADO DE TIPO DE BUSQUEDA");
		descError.put(PRIMERO_SELECCIONE_PAPODERADO,"PRIMERO BUSQUE Y SELECCIONE UN APODERADO");
		descError.put(REGISTRO_DADO_BAJA,"REGISTRO YA HA SIDO DADO DE BAJA");
		descError.put(DESEA_DAR_BAJA,"Â“DESEA DAR DE BAJA EL REGISTRO");
		descError.put(FECHA_DESDE_INCORRECTA,"VERIFIQUE EL CAMPO FECHA DESDE SELECCIONO UNA FECHA MAYOR AL DIA ACTUAL.");
		descError.put(PRIMERO_SELECCIONE_PERSONA_JUR,"PRIMERO BUSQUE Y SELECCIONE UNA PERSONA JURIDICA");
		descError.put(GRUPOSOLIDARIO_REGISTRADO_HOMONIMO,"EL GRUPO SOLIDARIO YA ESTA REGISTRADO O TIENE UN HOMONIMO, DESEA CONTINUAR?");
		descError.put(PRIMERO_SELECCIONE_GRUPOSOLIDARIO,"PRIMERO BUSQUE Y SELECCIONE UN GRUPO SOLIDARIO");
		descError.put(ERROR_CREAR_PERSONA,"ERROR AL CREAR PERSONA NATURAL");
		descError.put(MISMA_PERSONA_VINCULADO,"VERIFIQUE, NO DEBE SELECCIONAR A LA MISMA PERSONA QUE SE LE ESTA ASOCIANDO EL VINCULADO.");
		descError.put(PERSONA_REF_IGUAL_ENTIDAD_REF,"LA ENTIDAD SELECCIONADA  COMO PERSONA  REFERENCIA  Y LA ENTIDAD A QUIEN SE LE ESTA REGISTRANDO LA PERSONA REFERENCIA  SON LA MISMA, SELECCIONAR OTRA");
		descError.put(UNICO_REG_ACTIVO_INBORABLE,"EL REGISTRO QUE DESEA DAR DE BAJA ES EL UNICO ACTIVO QUE HAY, NO ES POSIBLE REALIZAR LA BAJA");
		descError.put(TELEFONOS_NO_PERTENECEN,"NO HA SELECCIONADO A QUIEN CORRESPONDEN LOS TELEFONOS");
		descError.put(CERO_RESULTADOS,"CERO RESULTADOS");
		descError.put(CORREOS_NO_PERTENECEN,"NO HA SELECCIONADO A QUIEN CORRESPONDEN LOS COREOS ELECTRONICOS");
		descError.put(CONTACTOS_NO_PERTENECEN,"NO HA SELECCIONADO A QUIEN CORRESPONDEN LOS CONTACTOS");
		descError.put(VINCULACIONES_NO_PERTENECEN,"NO HA SELECCIONADO A QUIEN CORRESPONDEN LOS OTRAS VINCULACIONES");
		descError.put(DOMICILIOS_NO_PERTENECEN,"NO HA SELECCIONADO A QUIEN CORRESPONDEN LOS DOMICILIOS");
		descError.put(RELACIONES_NO_PERTENECEN,"NO HA SELECCIONADO A QUIEN CORRESPONDEN LAS RELACIONES A NIVEL DEL GRUPO ECONOMICO");
		descError.put(IDENTIFICACIONES_NO_PERTENECEN,"NO HA SELECCIONADO A QUIEN CORRESPONDEN LAS IDENTIFICACIONES");
		descError.put(IDENTIFICACION_DUPLICADA,"VERIFICAR, IDENTIFICACION DUPLICADA.");
		descError.put(FECHA_NACIMIENTO_INCORRECTA,"VERIFIQUE EL CAMPO FECHA NACIMIENTO SELECCIONO UNA FECHA MAYOR AL DIA ACTUAL.");
		descError.put(VALOR_BUSQUEDA_INCORRECTO,"VERIFIQUE, DEBE CAPTURAR UN VALOR DE BUSQUEDA DE POR LO MENOS 2 CARACTERES");
		descError.put(REG_ACTIVO_INEXISTENTE_REASIGNARLO,"NO ENCONTRO UN REGISTRO ACTIVO PARA REASIGNARLO COMO PRINCIPAL");
		descError.put(CORREO_DUPLICADO_ENTIDAD,"VERIFIQUE LA ENTIDAD YA TIENE REGISTRADO  ESTE CORREO ELECTRONICO, CAPTURE OTRO");
		descError.put(DOMICILIO_DUPLICADO_ENTIDAD,"VERIFIQUE LA ENTIDAD YA TIENE REGISTRADO  ESTE DOMICILIO, CAPTURE OTRO");
		descError.put(TELEFONO_DUPLICADO_ENTIDAD,"VERIFIQUE LA ENTIDAD YA TIENE REGISTRADO  ESTE TELEFONO, CAPTURE OTRO");
		descError.put(CONTACTO_DUPLICADO_ENTIDAD,"VERIFIQUE LA ENTIDAD YA TIENE REGISTRADO  ESTE CONTACTO CAPTURE OTRO");
		descError.put(BENEFICIARIO_DUPLICADO_ENTIDAD,"VERIFIQUE LA ENTIDAD YA TIENE REGISTRADO  ESTE BENEFICIARIO CAPTURE OTRO");
		descError.put(FAMILIAR_DUPLICADO_ENTIDAD,"VERIFIQUE LA ENTIDAD YA TIENE REGISTRADO  ESTE FAMILIAR CAPTURE OTRO");
		descError.put(VINCULADO_DUPLICADO_ENTIDAD,"VERIFIQUE LA ENTIDAD YA TIENE REGISTRADO  ESTE OTRO VINCULADO  CAPTURE OTRO");
		descError.put(APODERADO_DUPLICADO_ENTIDAD,"VERIFIQUE LA ENTIDAD YA TIENE REGISTRADO  ESTE APODERADO  CAPTURE OTRO");
		descError.put(FUNCIONARIO_DUPLICADO_ENTIDAD,"VERIFIQUE LA ENTIDAD YA TIENE REGISTRADO  ESTE FUNCIONARIO  CAPTURE OTRO");
		descError.put(INTEGRANTE_DUPLICADO_ENTIDAD,"VERIFIQUE LA ENTIDAD YA TIENE REGISTRADO  ESTE INTEGRANTE  CAPTURE OTRO");
		descError.put(NEGOCIOS_SIN_IDENTIDAD,"NO HA SELECCIONADO LA ENTIDAD A QUIEN CORRESPONDEN LOS NEGOCIOS");
		descError.put(ERROR_INESPERADO,"ERROR INESPERADO %s");
		descError.put(DOMICILIO_NO_SELECCIONADO,"VERIFIQUE, NO HA SELECCIONADO UN DOMICILIO");
		descError.put(TELEFONO_NO_SELECCIONADO,"VERIFIQUE, NO HA SELECCIONADO UN TELEFONO");
		descError.put(CORREO_NO_SELECCIONADO,"VERIFIQUE, NO HA SELECCIONADO UN CORREO ELECTRONICO");
		descError.put(NEGOCIO_NO_SELECCIONADO,"VERIFIQUE, NO HA SELECCIONADO UN NEGOCIO");
		descError.put(REGISTRO_PERMISO_NO_SELECCIONADO,"VERIFIQUE, NO HA SELECCIONADO EL REGISTRO-PERMISO");
		descError.put(CONTACTO_NO_SELECCIONADO,"VERIFIQUE, NO HA SELECCIONADO UN CONTACTO");
		descError.put(SELECCIONE_CORRESPONDENCIA_BENEFICIARIOS,"NO HA SELECCIONADO A QUIEN CORRESPONDEN LOS BENEFICIARIOS");
		descError.put(SELECCIONE_CORRESPONDENCIA_FAMILIARES,"NO HA SELECCIONADO A QUIEN CORRESPONDEN LOS FAMILIARES");
		descError.put(SELECCIONE_CORRESPONDENCIA_FUNCIONARIO,"NO HA SELECCIONADO A QUIEN CORRESPONDEN LOS FUNCIONARIOS");
		descError.put(PORCENTAJE_FUERA_RANGO,"VERIFIQUE, EL PORCENTAJE DEBE ESTAR EN EL RANGO DE 1-100");
		descError.put(SELECCIONE_BENEFICIARIO,"VERIFIQUE, NO HA SELECCIONADO UN BENEFICIARIO");
		descError.put(SELECCIONE_FAMILIAR,"VERIFIQUE, NO HA SELECCIONADO UN FAMILIAR");
		descError.put(SELECCIONE_INTEGRANTES_GRUPO_SOL,"NO HA SELECCIONADO A QUIEN CORRESPONDEN LOS INTEGRANTES DEL GRUPO SOLIDARIO");
		descError.put(SELECCIONAR_OTRO_VINCULO,"VERIFIQUE, NO HA SELECCIONADO UN OTRO VINCULO");
		descError.put(PROPIEDAD_CONSULTAR,"INDIQUE LA PROPIEDAD A CONSULTAR");
		descError.put(FECHA_HASTA_INCORRECTA,"VERIFIQUE EL CAMPO FECHA HASTA  SELECCIONO UNA FECHA MENOR AL DIA ACTUAL.");
		descError.put(SELECCIONE_APODERADO,"VERIFIQUE, NO HA SELECCIONADO UN APODERADO");
		descError.put(SELECCIONE_PERTENENCIA_PODERES,"PRIMERO BUSQUE Y SELECCIONE A QUIEN PERTENECEN LOS PODERES");
		descError.put(ENTIDAD_ASIGNADA_NO_EXISTE,"LA ENTIDAD ASIGNADA NO EXISTE");
		descError.put(PODER_NO_SELECCIONADO,"VERIFIQUE, NO HA SELECCIONADO EL PODER");
		descError.put(IDENTIFICACION_NO_SELECCIONADA,"VERIFIQUE, NO HA SELECCIONADO LA IDENTIFICACION");
		descError.put(FECHA_CONSTITUCION_INCORRECTA,"VERIFIQUE EL CAMPO FECHA CONSTITUCION SELECCIONO UNA FECHA MAYOR AL DIA ACTUAL.");
		descError.put(ACCIONES_FUNCIONARIOS_SOBREPASAN,"VERIFIQUE, EL TOTAL DE LAS ACCIONES DE LOS FUNCIONARIOS REGISTRADOS Y EL ACTUAL NO DEBEN REBASAR EL 100%");
		descError.put(PRIMERO_SELECCIONE_FUNCIONARIO,"VERIFIQUE, NO HA SELECCIONADO UN FUNCIONARIO");
		descError.put(PRIMERO_SELECCIONE_INTEGRANTE,"VERIFIQUE, NO HA SELECCIONADO UN INTEGRANTE");
		descError.put(BUSQUEDA_PN_SIN_RESULTADOS,"LA BUSQUEDA DE PERSONAS NATURALES NO REGRESO RESULTADOS");
		descError.put(ERROR_VALIDAR_INFORMACION_PERSONA,"SE ENCONTRO ERROR EN LA INFORMACION INGRESADA PARA LA PERSONA");
		descError.put(ERROR_VALIDAR_HOMONIMIA_PERSONA,"SE GENERO ERROR AL VALIDAR HOMONIMIA");
		descError.put(FALLO_VALIDAR_DATOS_ENTIDAD_TIPOENTIDAD,"EL DATO DE LA ENTIDAD O EL TIPO DE ENTIDAD ESTAN VACIOS.");
		descError.put(ERROR_VALIDAR_CONYUGE,"SE ENERO UN ERROR AL VALIDAR DATOS DEL CONYUGE");
		descError.put(ERROR_VALIDAR_DATOS_NACIMIENTO,"GENERO ERROR AL VALIDAR DATOS DE NACIMIENTO");
		descError.put(ERROR_VALIDAR_DATOS_EDOCIVIL,"GENERO ERROR AL VALIDAR DATOS DE ESTADO CIVIL");
		descError.put(ERROR_VALIDAR_DATOS_GRADOINSTRUCCION,"GENERO ERROR AL VALIDAR LOS DATOS DE GRADO DE INSTRUCCION DE LA PERSONA");
		descError.put(ERROR_VALIDAR_DATOS_OCUPACION,"GENERO ERROR AL VALIDAR DATOS DE LA OCUPACION DE LA PERSONA");
		descError.put(ERROR_VALIDAR_DATOS_EMPRESARIALES,"GENERO ERROR AL VALIDAR DATOS EMPRESARIALES DE LA PERSONA");
		descError.put(ERROR_VALIDAR_DATOS_RESIDENCIA,"GENERO ERROR AL VALIDAR DATOS DE RESIDENCIA");
		descError.put(ERROR_VALIDAR_DATOS_GIRONEGOCIO,"GENERO ERROR AL VALIDAR DATOS DEL GIRO DEL NEGOCIO");
		descError.put(ERROR_VALIDAR_DATOS_ENTEREGULADOR,"GENERO ERROR AL VALIDAR DATOS DEL ENTE REGULADOR");
		descError.put(ERROR_MODIFICAR_PERSONA,"GENERO ERROR AL GUARDA LOS DATOS MODIFICADOS DE LA PERSONA");
		descError.put(BUSQUEDA_DOMICILIOS_SIN_RESULTADOS,"LA BUSQUEDA DE DOMICILIOS NO REGRESO RESULTADOS");
		descError.put(ERROR_BUSCAR_DOMICILIOS,"GENERO UN ERROR LA BUSQUEDA DE DOMICILIOS");
		descError.put(ERROR_VALIDAR_DATOS_DOMICILIOS,"GENERO ERROR AL VALIDAR LOS DATOS DEL DOMICILIO");
		descError.put(ERROR_CREAR_DOMICILIO,"GENERO ERROR AL CREAR UN NUEVO DOMICILIO");
		descError.put(ERROR_REVISA_ESTATUS_ENTIDAD,"GENERO ERROR AL REVISAR EL ESTATUS DE LA PERSONA");
		descError.put(ERROR_MODIFICAR_DOMICILIO,"GENERO ERROR AL MODIFICAR EL DOMICILIO DEL CLIENTE");
		descError.put(ERROR_VALIDAR_DATOS_BAJA,"GENERO ERROR AL VALIDAR DATOS PARA BAJA DE CLIENTE");
		descError.put(ERROR_CONTADOR_DOMICILIOS_ACTIVOS,"GENERO ERROR AL BUSCAR LOS DOMICILIOS ACTIVOS DEL CLIENTE");
		descError.put(DOMICILIO_ACTIVO_NO_ENCONTRADO,"no encontro un domicilio activo para reasignarlo como principal");
		descError.put(FALLO_VALIDAR_DATOS_DESCRIPCION_ENTIDAD,"GENERO ERROR AL VALIDAR LOS DATOS DE DESCRIPCION DE LA ENTIDAD");
		descError.put(ERROR_DESCRIPCION_ENTIDAD_NOENCONTRADA,"NO SE ENCONTRO LA DESCRIPCION");
		descError.put(ERROR_ELIMINAR_DOMICILIO,"GENERO UN ERROR AL ELIMINAR EL DOMICILIO DE LA PERSONA");
		descError.put(ERROR_ELIMINAR_PERSONA,"GENERO UN ERROR AL ELIMINAR PERSONA");
		descError.put(ERROR_VALIDAR_DATOS_TELEFONO,"GENERO ERROR AL VALIDAR LOS DATOS DEL TELEFONO");
		descError.put(ERROR_CREAR_TELEFONO,"GENERO ERROR AL CREAR UN NUEVO TELEFONO");
		descError.put(BUSQUEDA_TELEFONOS_SIN_RESULTADOS,"LA BUSQUEDA DE TELEFONOS NO REGRESO RESULTADOS");
		descError.put(ERROR_BUSCAR_TELEFONOS,"GENERO UN ERROR LA BUSQUEDA DE TELEFONOS");
		descError.put(ERROR_MODIFICAR_TELEFONO,"GENERO UN ERROR AL GUARDAR LOS DATOS MODIFICADOS DEL TELEFONO DE LA PERSONA");
		descError.put(PRIMERO_SELECCIONE_TELEFONO,"PRIMERO BUSQUE Y SELECCIONE EL TELEFONO");
		descError.put(ERROR_ELIMINAR_TELEFONO,"GENERO ERROR AL ELIMINAR EL TELEFONO DE LA PERSONA");
		descError.put(TELEFONO_ACTIVO_NO_ENCONTRADO,"NO SE ENCONTRO UN TELEFONO ACTIVO PARA REASIGNARLO COMO PRINCIPAL");
		descError.put(PRIMERO_SELECCIONE_DOMICILIO,"PRIMERO BUSQUE Y SELECCIONE UN DOMICILIO");
		descError.put(BUSQUEDA_CORREOS_SIN_RESULTADOS,"LA BUSQUEDA DE CORREOS ELECTRONICOS NO REGRESO RESULTADOS");
		descError.put(ERROR_BUSCAR_CORREOS,"GENERO ERROR LA BUSQUEDA DE CORREOS ELECTRONICOS");
		descError.put(ERROR_CREAR_CORREO,"GENERO ERROR AL CREAR UN NUEVO CORREO ELECTRONICO");
		descError.put(ERROR_VALIDAR_DATOS_CORREO,"GENERO ERROR AL VALIDAR LOS DATOS DEL CORREO ELECTRONICO");
		descError.put(ERROR_MODIFICAR_CORREO,"GENERO ERROR AL GUARDAR LOS DATOS MODIFICADOS DEL CORREO ELECTRONICO");
		descError.put(ERROR_ELIMINAR_CORREO,"GENERO ERROR AL ELIMINAR EL CORREO ELECTRONICO DE LA PERSONA");
		descError.put(CORREO_ACTIVO_NO_ENCONTRADO,"NO SE ENCONTRO UN CORREO ELECTRONICO ACTIVO PARA REASIGNARLO COMO PRINCIPAL");
		descError.put(ERROR_CONTADOR_CORREOS_ACTIVOS,"GENERO ERROR AL BUSCAR LOS DOMICILIOS ACTIVOS DE LA PERSONA");
		descError.put(PRIMERO_SELECCIONE_CORREO,"PRIMERO BUSQUE Y SELECCIONE UN CORREO ELECTRONICO");
		descError.put(ERROR_VALIDAR_HOMONIMIA_NEGOCIO,"GENERO ERROR AL VALIDAR HOMONIMIA DEL NEGOCIO");
		descError.put(ERROR_CREAR_NEGOCIO,"GENERO ERROR AL CREAR UN NUEVO NEGOCIO");
		descError.put(ERROR_VALIDAR_INFORMACION_NEGOCIO,"SE ENCONTRO ERROR EN LA INFORMACION INGRESADA PARA EL NEGOCIO");
		descError.put(ERROR_CONTADOR_NEGOCIOS_ACTIVOS,"GENERO ERROR AL BUSCAR LOS NEGOCIOS ACTIVOS DE LA PERSONA");
		descError.put(ERROR_CONTADOR_TELEFONOS_ACTIVOS,"GENERO ERROR AL BUSCAR LOS TELEFONOS ACTIVOS DE LA PERSONA");
		descError.put(ERROR_ELIMINAR_NEGOCIO,"GENERO ERROR AL ELIMINAR EL NEGOCIO DE LA PERSONA");
		descError.put(ERROR_MODIFICAR_NEGOCIO,"GENERO ERROR AL GUARDAR LOS DATOS MODIFICADOS DEL NEGOCIO");
		descError.put(BUSQUEDA_NEGOCIOS_SIN_RESULTADOS,"LA BUSQUEDA DE NEGOCIOS NO REGRESO RESULTADOS");
		descError.put(ERROR_BUSCAR_NEGOCIOS,"GENERO ERROR LA BUSQUEDA DE NEGOCIOS");
		descError.put(ERROR_VALIDAR_DATOS_IDENTIFICACION,"GENERO ERROR AL VALIDAR DATOS DE LA IDENTIFICACION");
		descError.put(ERROR_CREAR_REGISTRO_PERMISO,"GENERO ERROR AL CREAR UN NUEVO REGISTRO - PERMISO DEL NEGOCIO");
		descError.put(ERROR_MODIFICAR_REGISTRO_PERMISO,"GENERO ERROR AL GUARDAR LOS DATOS MODIFICADOS DEL REGISTRO - PERMISO DEL NEGOCIO");
		descError.put(ERROR_VALIDAR_DATOS_REGISTRO_PERMISO,"GENERO ERROR AL VALIDAR DATOS DEL REGISTRO - PERMISO DEL NEGOCIO");
		descError.put(BUSQUEDA_REGISTRO_PERMISO_SIN_RESULTADOS,"LA BUSQUEDA DE REGISTROS - PERMISOS NO REGRESO RESULTADOS");
		descError.put(PRIMERO_SELECCIONE_REGISTRO_PERMISO,"SELECCIONE PRIMERO EL REGISTRO - PERMISO");
		descError.put(ERROR_ELIMINAR_IDENTIFICACION,"GENERO ERROR AL ELIMINAR LA IDENTIFICACION");
		descError.put(ERROR_CONTADOR_IDENTIFICACIONES_ACTIVOS,"GENERO ERROR AL BUSCAR LAS IDENTIFICACIONES ACTIVAS");
		descError.put(IDENTIFICACION_ACTIVO_NO_ENCONTRADO,"NO SE ENCONTRO UNA IDENTIFICACION ACTIVA PARA REASIGNAR");
		descError.put(BUSQUEDA_IDENTIFICACIONES_SIN_RESULTADOS,"LA BUSQUEDA DE IDENTIFICACIONES NO REGRESO RESULTADOS");
		descError.put(ERROR_BUSCAR_IDENTIFICACIONES,"GENERO ERROR AL BUSCAR IDENTIFICACIONES");
		descError.put(ERROR_VALIDAR_DATOS_CONTACTO,"GENERO ERROR AL VALIDAR DATOS DEL CONTACTO");
		descError.put(ERROR_CREAR_CONTACTO,"GENERO ERROR AL DAR DE ALTA UN NUEVO CONTACTO");
		descError.put(ERROR_VALIDAR_DUPLICIDAD_VINCULACION,"GENERO ERROR AL VALIDAR QUE NO EXISTA OTRO CONTACTO CON EL MISMO TIPO DE VINCULACION");
		descError.put(CONTACTO_ES_EL_MISMO,"VERIFIQUE, LA PERSONA A QUIEN SE LE ESTA ASOCIANDO ESTE CONTACTO ES EL MISMO.");
		descError.put(BUSQUEDA_CONTACTOS_SIN_RESULTADOS,"LA BUSQUEDA DE CONTACTOS NO REGRESO RESULTADOS");
		descError.put(ERROR_BUSCAR_VINCULACIONES,"GENERO ERROR AL BUSCAR VINCULACIONES");
		descError.put(BUSQUEDA_VINCULACIONES_SIN_RESULTADOS,"LA BUSQUEDA DE VINCULACIONES NO GENERO RESULTADOS");
		descError.put(PRIMERO_SELECCIONE_CONTACTO,"SELECCIONE PRIMERO EL CONTACTO");
		descError.put(ERROR_MODIFICAR_CONTACTO,"GENERO ERROR AL MODIFICAR EL CONTACTO");
		descError.put(ERROR_CONTADOR_VINCULACIONES_ACTIVOS,"GENERO ERROR AL BUSCAR LAS VINCULACIONES ACTIVAS");
		descError.put(ERROR_ELIMINAR_VINCULACION,"GENERO ERROR AL ELIMINAR LA VINCULACION");
		descError.put(ERROR_MODIFICAR_BENEFICIARIO,"GENERE ERROR AL MODIFICAR EL BENEFICIARIO");
		descError.put(PRIMERO_SELECCIONE_BENEFICIARIO,"SELECCIONE PRIMERO EL BENEFICIARIO");
		descError.put(BUSQUEDA_BENEFICIARIOS_SIN_RESULTADOS,"LA BUSQUEDA DE BENEFICIARIOS NO GENERO RESULTADOS");
		descError.put(ERROR_CREAR_BENEFICIARIO,"GENERO ERROR AL DAR DE ALTA UN NUEVO BENEFICIARIO");
		descError.put(ERROR_VALIDAR_DATOS_FAMILIAR,"GENERO ERROR AL VALIDAR DATOS DEL FAMILIAR");
		descError.put(ERROR_VALIDAR_DATOS_BENEFICIARIO,"GENERO ERROR AL VALIDAR DATOS DEL BENEFICIARIO");
		descError.put(BENEFICIARIO_ES_EL_MISMO,"VERIFIQUE, LA PERSONA A QUIEN SE LE ESTA ASOCIANDO EL BENEFICIARIO, POR QUE SON LA MISMA PERSONA");
		descError.put(FAMILIAR_ES_EL_MISMO,"VERIFIQUE, LA PERSONA A QUIEN SE LE ESTA ASOCIANDO EL FAMILIAR, SON LA MISMA PERSONA");
		descError.put(ERROR_CREAR_FAMILIAR,"GENERO ERROR AL DAR DE ALTA UN NUEVO FAMILIAR");
		descError.put(ERROR_MODIFICAR_FAMILIAR,"GENERO ERROR AL MODIFICAR EL FAMILIAR");
		descError.put(BUSQUEDA_FAMILIAR_SIN_RESULTADOS,"LA BUSQUEDA DE FAMILIARES NO GENERO RESULTADOS");
		descError.put(PRIMERO_SELECCIONE_FAMILIAR,"SELECCIONE PRIMERO AL FAMILIAR");
		descError.put(ERROR_VALIDAR_DATOS_OTRO_VINCULO,"GENERO ERROR AL VALIDAR DATOS DEL OTRO VINCULO");
		descError.put(ERROR_CREAR_OTRO_VINCULO,"GENERO ERROR AL DAR DE ALTA UN NUEVO OTRO VINCULO");
		descError.put(OTRO_VINCULO_ES_EL_MISMO,"VERIFIQUE, LA PERSONA A QUIEN SE LE ESTA ASOCIANDO EL OTRO VINCULO");
		descError.put(BUSQUEDA_OTROS_VINCULOS_SIN_RESULTADOS,"LA BUSQUEDA DE OTROS VINCULOS NO GENERO RESULTADOS");
		descError.put(PRIMERO_SELECCIONE_OTRO_VINCULO,"SELECCIONE PRIMERO EL OTRO VINCULO");
		descError.put(ERROR_MODIFICAR_OTRO_VINCULO,"GENERO ERROR AL MODIFICAR EL OTRO VINCULO");
		descError.put(VINCULACION_DUPLICADO_ENTIDAD,"VERIFIQUE LA ENTIDAD YA TIENE REGISTRADO  ESTA VINCULACION, CAPTURE OTRO");
		descError.put(BUSQUEDA_APODERADO_SIN_RESULTADOS,"LA BUSQUEDA DE APODERADOS NO REGRESO RESULTADOS");
		descError.put(PRIMERO_SELECCIONE_APODERADO,"SELECCIONE PRIMERO AL APODERADO");
		descError.put(ERROR_CREAR_APODERADO,"GENERO ERROR AL DAR DE ALTA UN NUEVO APODERADO");
		descError.put(ERROR_MODIFICAR_APODERADO,"GENERO ERROR AL MODIFICAR APODERADO");
		descError.put(APODERADO_ES_EL_MISMO,"VERIFIQUE, LA PERSONA A QUIEN SE LE ESTA ASOCIANDO EL APODERADO ES LA MISMA");
		descError.put(ERROR_VALIDAR_DATOS_APODERADO,"GENERO ERROR AL VALIDAR DATOS DEL APODERADO");
		descError.put(ERROR_VALIDAR_DATOS_PODER,"GENERO ERROR AL VALIDAR DATOS DEL PODER");
		descError.put(ERROR_CREAR_PODER,"GENERO ERROR AL DAR DE ALTA UN NUEVO PODER");
		descError.put(ERROR_ELIMINAR_PODER,"GENERO ERROR AL ELIMINAR EL PODER");
		descError.put(ERROR_MODIFICAR_PODER,"GENERO ERROR AL MODIFICAR EL PODER");
		descError.put(PRIMERO_SELECCIONE_PODER,"SELECCIONE PRIMERO EL PODER");
		descError.put(BUSQUEDA_PODER_SIN_RESULTADOS,"LA BUSQUEDA DE PODERES NO REGRESO RESULTADOS");
		descError.put(ERROR_BUSCAR_PODER,"GENERO ERROR AL BUSCAR PODERES");
		descError.put(FALLO_VALIDAR_LISTADO,"GENERO ERROR AL VALIDAR DATOS PARA GENERAR EL LISTADO");
		descError.put(FALLO_VALIDAR_LISTADO_PODERES,"GENERO ERROR AL VALIDAR LOS DATOS PARA GENERAR EL LISTADO DE PODERES");
		descError.put(ERROR_VALIDAR_LISTADO_GRUPO_ECONOMICO,"GENERO ERROR AL VALIDAR LOS DATOS PARA GENERAR EL LISTADO");
		descError.put(BUSQUEDA_GRUPO_ECONOMICO_SIN_RESULTADOS,"LA BUSQUEDA DE GRUPO ECONOMICO NO REGRESO RESULTADOS");
		descError.put(ERROR_BUSCAR_GRUPO_ECONOMICO,"GENERO ERROR AL BUSCAR DATOS DEL GRUPO ECONOMICO");
		descError.put(ERROR_VALIDAR_DATOS_FUNCIONARIO,"GENERO ERROR AL VALIDAR DATOS DEL FUNCIONARIO");
		descError.put(FUNCIONARIO_ES_EL_MISMO,"VERIFIQUE, LA PERSONA A QUIEN SE LE ESTA ASOCIANDO EL FUNCIONARIO ES LA MISMA PERSONA");
		descError.put(ERROR_CREAR_FUNCIONARIO,"GENERO ERROR AL DAR DE ALTA UN NUEVO FUNCIONARIO");
		descError.put(ERROR_CREAR_INTEGRANTE,"GENERO ERROR AL DAR DE ALTA UN NUEVO INTEGRANTE");
		descError.put(INTEGRANTE_ES_EL_MISMO,"VERIFIQUE, LA PERSONA A QUIEN SE LE ESTA ASOCIANDO EL INTEGRANTE SON LA MISMA PERSONA");
		descError.put(ERROR_VALIDAR_DATOS_INTEGRANTE,"GENERO ERROR AL VALIDAR LOS DATOS DEL INTEGRANTE");
		descError.put(ERROR_MODIFICAR_FUNCIONARIO,"GENERO ERROR AL MODIFICAR EL FUNCIONARIO");
		descError.put(ERROR_MODIFICAR_INTEGRANTE,"GENERO ERROR AL MODIFICAR EL INTEGRANTE");
		descError.put(BUSQUEDA_INTEGRANTE_SIN_RESULTADOS,"LA BUSQUEDA DE INTEGRANTES NO REGRESO RESULTADOS");
		descError.put(BUSQUEDA_FUNCIONARIO_SIN_RESULTADOS,"la busqueda de FUNCIONARIOS no regreso resultaDOS");
		descError.put(ERROR_CREAR_PERSONA_JURIDICA,"GENRO ERROR AL DAR DE ALTA UNA PERSONA JURIDICA");
		descError.put(ERROR_VALIDAR_INFORMACION_PERSONA_JURIDICA,"GENERO ERROR EN LA INFORMACION INGRESADA PARA LA PERSONA JURIDICA");
		descError.put(ERROR_ACTUALIZAR_PERSONA_JURIDICA,"GENERO UN ERROR AL ACTUALIZAR LOS DATOS DE LA PERSONA JURIDICA");
		descError.put(ERROR_VALIDAR_DATOS_ENTIDAD_EXTERNA,"GENERO UN ERROR AL VALIDAR LOS DATOS DE ENTIDAD EXTERNA");
		descError.put(ERROR_VALIDAR_HOMONIMIA_PERSONA_JURIDICA,"SE ENCONTRO ERROR AL VALIDAR LA HOMONIMIA DE LA PERSONA JURIDICA");
		descError.put(ERROR_ACTUALIZAR_PERSONA_NATURAL,"GENERO UN ERROR AL ACTUALIZAR LOS DATOS DE LA PERSONA NATURAL");
		descError.put(ERROR_BUSCAR_PERSONA_JURIDICA,"GENERO UN ERROR AL BUSCAR DATOS DE LA PERSONA JURIDICA");
		descError.put(ERROR_BUSCAR_PERSONA_NATURAL,"GENERO UN ERROR AL BUSCAR DATOS DE LA PERSONA NATURAL");
		descError.put(ERROR_BUSCAR_PERSONAS,"GENERO UN ERROR AL BUSCAR PERSONAS");
		descError.put(ERROR_MODIFICAR_PERSONA_JURIDICA,"GENERO ERROR AL MODIFICAR LA PERSONA JURIDICA");
		descError.put(BUSQUEDA_PJ_SIN_RESULTADOS,"LA BUSQUEDA DE PERSONAS JURIDICAS NO REGRESO RESULTADOS");
		descError.put(BUSQUEDA_PERSONA_SIN_RESULTADOS,"LA BUSQUEDA DE LA PERSONA NO REGRESO RESULTADOS");
		descError.put(ERROR_MODIFICAR_PERSONA_GRUPO_SOLIDARIO,"GENERO ERROR AL MODIFICAR EL GRUPO SOLIDARIO");
		descError.put(BUSQUEDA_GRUPO_SOLIDARIO_SIN_RESULTADOS,"LA BUSQUEDA DE GRUPOS SOLIDARIOS NO REGRESO RESULTADOS");
		descError.put(PRIMERO_SELECCIONE_PERSONA_GRUPO_SOLIDARIO,"PRIMERO SELECCIONE EL GRUPO SOLIDARIO");
		descError.put(ERROR_CREAR_PERSONA_GRUPO_SOLIDARIO,"GENERO ERROR AL DAR DE ALTA UN NUEVO GRUPO SOLIDARIO");
		descError.put(ERROR_ACTUALIZAR_PERSONA_GRUPO_SOLIDARIO,"GENERO UN ERROR AL ACTUALIZAR LOS DATOS DEL GRUPO SOLIDARIO");
		descError.put(ERROR_VALIDAR_HOMONIMIA_PERSONA_GRUPO_SOLIDARIO,"GENERO UN ERROR AL VALIDAR LA HOMONIMIA DEL GRUPO SOLIDARIO");
		descError.put(ERROR_VALIDAR_INFORMACION_PERSONA_GRUPO_SOLIDARIO,"GENERO ERROR AL VALIDAR LOS DATOS DEL GRUPO SOLIDARIO");
		descError.put(ERROR_BUSCAR_PERSONA_GRUPO_SOLIDARIO,"GENERO UN ERROR AL BUSCAR GRUPO SOLIDARIO");
		descError.put(BUSQUEDA_NO_GENERO_RESULTADOS,"BUSQUEDA_NO_GENERO_RESULTADOS");
		descError.put(ERROR_CREAR_IDENTIFICACION,"ERROR_CREAR_IDENTIFICACION");
		descError.put(ERROR_MODIFICAR_IDENTIFICACION,"ERROR_MODIFICAR_IDENTIFICACION");
		descError.put(SELECCIONE_CLIENTE,"Verifique, No ha seleccionado el cliente a quien actualizara sus datos actuales.");
		descError.put(otro_nombre,"verifique, la entidad ya tiene registrado  este nombre capture otro");
		descError.put(SIN_TIPO_CLIENTE,"Seleccionar el tipo de cliente.");
		descError.put(duplicidad_nombre,"Verifique, el nombre esta siendo utilizado por el cliente numero: ####, Desea continuar?");
		descError.put(CAMPO_GRADO_INSTRUCCION_INCORRECTO,"CAMPO_GRADO_INSTRUCCION_INCORRECTO");
		descError.put(CAMPO_OFICIO_PROFESION_INCORRECTO,"CAMPO_OFICIO_PROFESION_INCORRECTO");
		descError.put(CAMPO_LUGAR_NACIMIENTO_VACIO,"CAMPO_LUGAR_NACIMIENTO_VACIO");
		descError.put(CAMPO_PAIS_NACIMIENTO_INCORRECTO,"CAMPO_PAIS_NACIMIENTO_INCORRECTO");
		descError.put(CAMPO_ESTADO_CIVIL_INCORRECTO,"CAMPO_ESTADO_CIVIL_INCORRECTO");
		descError.put(CAMPO_GIRO_NEGOCIO_INCORRECTO,"CAMPO_GIRO_NEGOCIO_INCORRECTO");
		descError.put(CAMPO_OCUPACION_INCORRECTO,"CAMPO_OCUPACION_INCORRECTO");
		descError.put(CAMPO_ENTIDAD_EXTERNA_VACIO,"CAMPO_ENTIDAD_EXTERNA_VACIO");
		descError.put(CAMPO_PAIS_RESIDENCIA_INCORRECTO,"CAMPO_PAIS_RESIDENCIA_INCORRECTO");
		descError.put(CAMPO_CLIENTE_EMPRESARIAL_INCORRECTO,"CAMPO_CLIENTE_EMPRESARIAL_INCORRECTO");
		descError.put(CAMPO_ENTE_REGULADOR_INCORRECTO,"CAMPO_ENTE_REGULADOR_INCORRECTO");
		descError.put(CAMPO_FECHA_NACIMIENTO_VACIA,"CAMPO_FECHA_NACIMIENTO_VACIA");
		descError.put(SIN_IDENTIFICACION_PPAL,"No tiene identificacion principal");
		descError.put(GENERO_INVALIDO,"Verifique, genero invalido (F = femenino o M=masculino)");
		descError.put(ERROR_VALIDAR_IDENTIFICACION_PRINCIPAL,"ERROR_VALIDAR_IDENTIFICACION_PRINCIPAL");
		descError.put(NOMBRE_DUPLICADO,"El nombre que esta capturando ya esta registrado o tiene un homonimo, desea continuar?");
		descError.put(ERROR_BUSCAR_IDENTIFICACION_PRINCIPAL,"ERROR_BUSCAR_IDENTIFICACION_PRINCIPAL");
		descError.put(ERROR_ACTUALIZAR_DATOS_ACTIVIDAD_ECONOMICA,"ERROR_ACTUALIZAR_DATOS_ACTIVIDAD_ECONOMICA");
		descError.put(ERROR_ACTUALIZAR_DATOS_REGISTRALES_NOTARIALES,"ERROR_ACTUALIZAR_DATOS_REGISTRALES_NOTARIALES");
		descError.put(ERROR_ACTUALIZAR_DATOS_RESIDENCIA,"ERROR_ACTUALIZAR_DATOS_RESIDENCIA");
		descError.put(ERROR_ACTUALIZAR_DATOS_ENTE_REGULADOR,"ERROR_ACTUALIZAR_DATOS_ENTE_REGULADOR");
		descError.put(ERROR_ACTUALIZAR_DATOS_EMPRESARIALES,"ERROR_ACTUALIZAR_DATOS_EMPRESARIALES");
		descError.put(ERROR_ACTUALIZAR_DATOS_ENTIDAD_EXTRANJERA,"ERROR_ACTUALIZAR_DATOS_ENTIDAD_EXTRANJERA");
		descError.put(ERROR_ACTUALIZAR_CONYUGE,"ERROR_ACTUALIZAR_CONYUGE");
		descError.put(ERROR_ACTUALIZAR_DATOS_NACIMIENTO,"ERROR_ACTUALIZAR_DATOS_NACIMIENTO");
		descError.put(ERROR_ACTUALIZAR_ESTADO_CIVIL,"ERROR_ACTUALIZAR_ESTADO_CIVIL");
		descError.put(ERROR_ACTUALIZAR_OCUPACION,"ERROR_ACTUALIZAR_OCUPACION");
		descError.put(ERROR_ACTUALIZAR_GRADO_INSTRUCCION,"ERROR_ACTUALIZAR_GRADO_INSTRUCCION");
		descError.put(PORCENTAJE_BENEFICIO_EXCEDIDO,"Verifique, el total del porcentaje de los beneficiarios registrados y el actual no deben rebasar el 100%");
		descError.put(CAMPO_BUSQUEDA_UNICO,"CAMPO_BUSQUEDA_UNICO");
		descError.put(ERROR_CONECTAR_WS,"ERROR_CONECTAR_WS");
		descError.put(ERROR_CONSUMIR_WS,"ERROR_CONSUMIR_WS");
		descError.put(ERROR_CREAR_GRUPO,"ERROR_CREAR_GRUPO");
		descError.put(AVAL_DUPLICADO_ENTIDAD,"VERIFIQUE LA ENTIDAD, YA TIENE REGISTRADO ESTE AVAL, CAPTURE OTRO");
		descError.put(GARANTE_DUPLICADO_ENTIDAD,"VERIFIQUE LA ENTIDAD, YA TIENE REGISTRADO ESTE GARANTE, CAPTURE OTRO");
		descError.put(ERROR_PROCESAR_XML,"ERROR_PROCESAR_XML");
		descError.put(ERROR_CREAR_AVAL,"GENERO ERROR AL DAR DE ALTA UN NUEVO AVAL");
		descError.put(ERROR_AVAL_ES_EL_MISMO,"ERROR EL VINCULADO ES LA MISMA PERSONA");
		descError.put(ERROR_VALIDAR_DATOS_AVAL,"ERROR AL VALIDAR LOS DATOS DEL AVAL");
		descError.put(ERROR_VALIDAR_DATOS_GARANTE,"ERROR AL VALIDAR LOS DATOS DEL GARANTE");
		descError.put(ERROR_GARANTE_ES_EL_MISMO,"ERROR EL GARANTE ES LA MISMA PERSONA");
		descError.put(ERROR_CREAR_GARANTE,"EROR AL CREAR GARANTE");
		descError.put(ERROR_PERSONA_VINCULADA_INACTIVA,"ERROR LA PERSONA VINCULADA ESTA DADA DE BAJA");
		descError.put(ERROR_OBTENER_LISTADO_VINCULADOS,"ERROR AL OBTENER EL LISTADO DE LOS VINCULADOS");
		descError.put(ERROR_BAJA_AVAL,"ERROR AL DAR DE BAJA AVAL");
		descError.put(ERROR_BAJA_GARANTE,"ERROR AL DAR DE BAJA EL GARANTE");
		descError.put(ERROR_OBTENER_DATOS_MAESTROPERSONA,"ERROR AL OBTENER LOS DATOS DE LA PERSONA");
		descError.put(ERROR_OBTENER_DATOS_DOMICILIO_PPAL,"ERROR AL OBTENER DATOS DEL DOMICILIO PRINCIPAL");
		descError.put(ERROR_OBTENER_TIPO_IDENTIFICACION,"ERROR AL OBTENER TIPO IDENTIFICACION");
		descError.put(ERR_CONSULTA_IDE_PPAL_PERSONA,"ERROR EN CONSULTA IDENTIFICACION PRINCIPAL PERSONA");
		descError.put(SELECCIONE_PERSONA,"SELECCIONE PERSONA");
		descError.put(USUARIO_SIN_EMPRESA_ASIG,"USUARIO SIN EMPRESA ASIGNADA");
		descError.put(ERR_VALIDAR_PRESTAMOS_PERSONAS,"ERROR VALIDAR PRESTAMOS PERSONAS");
		descError.put(ERR_PRESTAMOS_PERSONAS,"ERROR EN PRESTAMOS PERSONAS");
		descError.put(ERR_VALIDA_CONS_DATOS_PERSONAS,"ERROR EN VALIDA CONSULTA DATOS PERSONA");
		descError.put(CVE_CONCEPTO_VACIA,"CLAVE DEL CONCEPTO VACIA");
		descError.put(CVE_CONCEPTO_NO_EX,"CLAVE DEL CONCEPTO NO EXISTE");
		descError.put(CONCEPTO_NO_EX,"EL CONCEPTO NO EXISTE");
		descError.put(ERR_CONSULTA_DATOS_PERSONA,"ERROR EN CONSULTA DATOS PERSONA");
		descError.put(NO_EX_CLIENTE,"NO EXISTE CLIENTE");
		descError.put(VALOR_CONCEPTO_VACIO,"VALOR DEL CONCEPTO VACIO");
		descError.put(ERR_ACTUALIZA_DATOS_PERSONA,"ERROR EN ACTUALIZA DATOS PERSONA");
		descError.put(NEGOCIO_ESTA_ASOCIADO_A_SOLICITUD,"EL NEGOCIO ESTA ASOCIADO A UNA SOLICITUD");
		descError.put(ERROR_ENTIDAD_ASOCIADA_PRESTAMO,"ERROR EXISTE ASOCIACION  A UN PRESTAMO");
		descError.put(ERROR_ENTIDAD_ASOCIADA_GARANTIAS,"ERROR EXISTE ASOCIACION A UNA GARANTIA");
		descError.put(ERROR_ENTIDAD_ASOCIADA_SOLICITUD,"ERROR EXISTE ASOCIACION  A UNA SOLICITUD");
		descError.put(ERROR_CREAR_CENTRO_TRABAJO,"EROR AL CREAR  CENTRO DE TRABAJO");
		descError.put(ERROR_VALIDAR_DATOS_CENTRO_TRABAJO,"ERROR AL VALIDAR DATOS DEL CENTRO DE TRABAJO");
		descError.put(ERROR_BUSCAR_DATOS_NEGOCIO,"ERROR AL BUSCAR DATOS NEGOCIO");
		descError.put(CENTRO_TRABAJO_NO_EXISTE,"EL CENTRO DE TRABAJO NO EXISTE");
		descError.put(ERROR_MODIFICAR_CENTRO_TRABAJO,"ERROR AL MODIFICAR CENTRO TRABAJO");
		descError.put(ERROR_CONTADOR_CENTROS_TRABAJO_ACTIVOS,"GENERO ERROR AL BUSCAR LOS CENTROS DE TRABAJO ACTIVOS DE LA PERSONA");
		descError.put(CENTRO_DE_TRABAJO_ESTA_ASOCIADO_A_SOLICITUD,"CENTRO DE TRABAJO ESTA ASOCIADO A UNA SOLICITUD");
		descError.put(ERROR_BAJA_CENTRO_TRABAJO,"ERROR AL DAR DE BAJA CENTRO TRABAJO");
		descError.put(BUSQUEDA_CENTRO_TRABAJO_SIN_RESULTADOS,"BUSQUEDA CENTRO DE TRABAJO SIN RESULTADOS");
		descError.put(SELECCIONE_CENTRO_TRABAJO,"SELECCIONE UN CENTRO DE TRABAJO");
		descError.put(ERROR_BUSQUEDA_CENTRO_TRABAJO,"ERROR AL BUSCAR CENTRO TRABAJO");
		descError.put(ERROR_BORRAR_PERSONA_ES_TITULAR_SOLICITUD,"ERROR_BORRAR_PERSONA_ES_TITULAR_SOLICITUD");
		descError.put(ERROR_BORRAR_PERSONA_ES_TITULAR_PRESTAMO,"ERROR_BORRAR_PERSONA_ES_TITULAR_PRESTAMO");
		descError.put(ERROR_BORRAR_PERSONA_ES_TITULAR_CUENTA_AHORRO,"ERROR_BORRAR_PERSONA_ES_TITULAR_CUENTA_AHORRO");
		descError.put(ERROR_BORRAR_PERSONA_ES_PROPIETARIO_GARANTIA,"ERROR_BORRAR_PERSONA_ES_PROPIETARIO_GARANTIA");
		descError.put(ERROR_BORRAR_PERSONA_ES_PROPIETARIO_DACION_PAGO,"ERROR_BORRAR_PERSONA_ES_PROPIETARIO_DACION_PAGO");
		descError.put(ERROR_BORRAR_PERSONA_ES_CONYUGE,"ERROR_BORRAR_PERSONA_ES_CONYUGE");
		descError.put(CON_OP_NO_EX_ACT_DATOS_PERSONA,"CONCEPTO DE OPERACION NO EXISTE AL ACTUALIZAR DATOS DE PERSONA");
		descError.put(EI_ACTUALIZAR_DATOS_PERSONA,"ERROR INESPERADO AL ACTUALIZAR DATOS DE PERSONA");
		descError.put(SEL_CONCEPTO_OP_ACT_DATOS_PERSONA,"SELECCIONE CONCEPTO DE OPERACIONA PARA ACTUALIZAR DATOS PERSONA");
		descError.put(EI_VALIDAR_ACTUALIZA_DATOS_PERSONA,"ERROR INESPERADO AL VALIDAR INFORMACION PARA ACTUALIZAS DATOS PERSONA");
		descError.put(ERR_VALIDAR_OBTIENE_TIPO_IDENTIFICACION_TIPO_PERSONA_PERSONA_ID_VACIO,"ERROR AL OBTENER IDENTIFICACION PERSONA ID VACIO");
		descError.put(ERR_VALIDAR_OBTIENE_TIPO_IDENTIFICACION_TIPO_PERSONA_CLAVE_ID_VACIO,"ERROR AL OBTENER IDENTIFICACION CVE DEL TIPO IDENTIFICACION VACIO");
		descError.put(ERR_VALIDAR_OBTIENE_TIPO_IDENTIFICACION_TIPO_PERSONA_VACIO,"ERROR AL OBTENER IDENTIFICACION TIPO PERSONA VACIO");
		descError.put(ERR_VALIDAR_OBTIENE_TIPO_IDENTIFICACION_TIPO_PERSONA_EMPRESA_ID_VACIO,"ERROR AL OBTENER IDENTIFICACION EMPRESA VACIA");
		descError.put(EI_VALIDAR_OBTIENE_TIPO_IDENTIFICACION_TIPO_PERSONA,"ERROR INESPERADO AL OBTENER IDENTIFICACION POR TIPO PERSONA");
		descError.put(TIPO_IDENTIFICACION_DADA_BAJA,"TIPO IDENTIFICACION DADA DE BAJA");
		descError.put(EI_OBTIENE_TIPO_IDENTIFICACION_TIPO_PERSONA,"ERROR INESPERADO EN OBTIENE TIPO IDENTIFICACION POR TIPO PERSONA");
		descError.put(ERR_VAL_BUS_PERSONA_X_CONCEPTO_VALOR_VACIO,"ERROR AL VALIDAR BUSQUEDA DE PERSONA POR CONCEPTO VALOR NO ESPECIFICADO");
		descError.put(EI_VALIDAR_BUSQUEDA_PERSONA_X_CONCEPTO,"ERROR INESPERADO AL VALIDAR BUSQUEDA DE PERSONA POR CONCEPTO");
		descError.put(EI_BUSCAR_PERSONA_CONCEPTO,"ERROR INESPERADO EN BUSCAR PERSONA POR CONCEPTO");
		descError.put(REGLA_NEGOCIO,"Regla %s");
		descError.put(CAPTURE_NOMBRE,"CAPTURE NOMBRE");
		descError.put(EI_BUSCAR_PERSONA_POR_NOMBRE,"ERROR INESPERADO AL BUSCAR PERSONA POR NOMBRE");
		descError.put(EI_ACTUALIZA_PRESTAMOS_PERSONAS,"ERROR INESPERADO EN ACTUALIZA PRESTAMOS");
		descError.put(YA_EXISTE_CT,"CENTRO DE TRABAJO YA EXISTE");
		descError.put(ERR_DUENO_MISMO_CLIENTE,"EL DUENO ES LA MISMA PERSONA SELECCIONADA");
		descError.put(FORMATO_INVALIDO,"FORMATO INVALIDO DE  IDENTIFICACION");
		descError.put(NUM_EMPLEADO_EXISTE,"EL NUMERO DE NOMINA YA ESTÁ ASIGNADO A OTRA PERSONA EN EL CENTRO DE TRABAJO");
		descError.put(EI_VALIDAR_NUMERO_EMPLEADO,"ERROR INESPERADO AL VALIDAR NUMERO DE NOMINA");
	}

}

