package net.izel.ws.seg.consultausuarios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-03-24T10:17:18.580-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "ConsultaUsuariosIfzService", 
                  wsdlLocation = "http://localhost:17081/esb/seguridad/consulta-usuarios?wsdl",
                  targetNamespace = "http://consultaUsuarios.seg.ws.izel.net/") 
public class ConsultaUsuariosIfzService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://consultaUsuarios.seg.ws.izel.net/", "ConsultaUsuariosIfzService");
    public final static QName ConsultaUsuariosIfzPort = new QName("http://consultaUsuarios.seg.ws.izel.net/", "ConsultaUsuariosIfzPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:17081/esb/seguridad/consulta-usuarios?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConsultaUsuariosIfzService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:17081/esb/seguridad/consulta-usuarios?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConsultaUsuariosIfzService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsultaUsuariosIfzService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaUsuariosIfzService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConsultaUsuariosIfzService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConsultaUsuariosIfzService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConsultaUsuariosIfzService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaUsuariosIfz
     */
    @WebEndpoint(name = "ConsultaUsuariosIfzPort")
    public ConsultaUsuariosIfz getConsultaUsuariosIfzPort() {
        return super.getPort(ConsultaUsuariosIfzPort, ConsultaUsuariosIfz.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaUsuariosIfz
     */
    @WebEndpoint(name = "ConsultaUsuariosIfzPort")
    public ConsultaUsuariosIfz getConsultaUsuariosIfzPort(WebServiceFeature... features) {
        return super.getPort(ConsultaUsuariosIfzPort, ConsultaUsuariosIfz.class, features);
    }

}
