
package org.tempuri.realvirtual.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * Verifica la estructura del cfd contra el schema
     * 
     * @param base64Cfd
     * @return
     *     returns org.tempuri.StructCfd
     */
    @WebMethod(operationName = "SchemaCfd", action = "http://tempuri.org/SchemaCfd")
    @WebResult(name = "SchemaCfdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SchemaCfd", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SchemaCfd")
    @ResponseWrapper(localName = "SchemaCfdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SchemaCfdResponse")
    public StructCfd schemaCfd(
        @WebParam(name = "base64Cfd", targetNamespace = "http://tempuri.org/")
        String base64Cfd);

    /**
     * Verifica la estructura del cfd y entrega la decodificacion
     * 
     * @param base64Cfd
     * @return
     *     returns org.tempuri.StructCfd
     */
    @WebMethod(operationName = "TestCfd", action = "http://tempuri.org/TestCfd")
    @WebResult(name = "TestCfdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TestCfd", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TestCfd")
    @ResponseWrapper(localName = "TestCfdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TestCfdResponse")
    public StructCfd testCfd(
        @WebParam(name = "base64Cfd", targetNamespace = "http://tempuri.org/")
        String base64Cfd);

    /**
     * Obtiene el timbre, regresa el tiembre y el cfdi
     * 
     * @param base64Cfd
     * @return
     *     returns org.tempuri.StructCfd
     */
    @WebMethod(operationName = "GetTicket", action = "http://tempuri.org/GetTicket")
    @WebResult(name = "GetTicketResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTicket", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTicket")
    @ResponseWrapper(localName = "GetTicketResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTicketResponse")
    public StructCfd getTicket(
        @WebParam(name = "base64Cfd", targetNamespace = "http://tempuri.org/")
        String base64Cfd);

    /**
     * Cancela el timbre
     * 
     * @param base64Cfd
     * @return
     *     returns org.tempuri.StructCancel
     */
    @WebMethod(operationName = "CancelTicket", action = "http://tempuri.org/CancelTicket")
    @WebResult(name = "CancelTicketResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelTicket", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelTicket")
    @ResponseWrapper(localName = "CancelTicketResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelTicketResponse")
    public StructCancel cancelTicket(
        @WebParam(name = "base64Cfd", targetNamespace = "http://tempuri.org/")
        String base64Cfd);

    /**
     * Cancela el timbre
     * 
     * @param base64Cfd
     * @return
     *     returns org.tempuri.StructCancelExtended
     */
    @WebMethod(operationName = "CancelTicketExtended", action = "http://tempuri.org/CancelTicketExtended")
    @WebResult(name = "CancelTicketExtendedResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelTicketExtended", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelTicketExtended")
    @ResponseWrapper(localName = "CancelTicketExtendedResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelTicketExtendedResponse")
    public StructCancelExtended cancelTicketExtended(
        @WebParam(name = "base64Cfd", targetNamespace = "http://tempuri.org/")
        String base64Cfd);

    /**
     * Obtiene el timbre y lo entrega sin el cfdi
     * 
     * @param base64Cfd
     * @return
     *     returns org.tempuri.StructCfd
     */
    @WebMethod(operationName = "GetTicketSimple", action = "http://tempuri.org/GetTicketSimple")
    @WebResult(name = "GetTicketSimpleResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTicketSimple", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTicketSimple")
    @ResponseWrapper(localName = "GetTicketSimpleResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTicketSimpleResponse")
    public StructCfd getTicketSimple(
        @WebParam(name = "base64Cfd", targetNamespace = "http://tempuri.org/")
        String base64Cfd);

    /**
     * Obtiene el timbre y lo entrega sin el cfdi
     * 
     * @param index
     * @return
     *     returns org.tempuri.StructAcuse
     */
    @WebMethod(operationName = "GetAcuse", action = "http://tempuri.org/GetAcuse")
    @WebResult(name = "GetAcuseResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAcuse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAcuse")
    @ResponseWrapper(localName = "GetAcuseResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAcuseResponse")
    public StructAcuse getAcuse(
        @WebParam(name = "index", targetNamespace = "http://tempuri.org/")
        long index);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetStatusSat", action = "http://tempuri.org/GetStatusSat")
    @WebResult(name = "GetStatusSatResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStatusSat", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStatusSat")
    @ResponseWrapper(localName = "GetStatusSatResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStatusSatResponse")
    public int getStatusSat();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod(operationName = "RetryCfdis", action = "http://tempuri.org/RetryCfdis")
    @WebResult(name = "RetryCfdisResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetryCfdis", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RetryCfdis")
    @ResponseWrapper(localName = "RetryCfdisResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RetryCfdisResponse")
    public int retryCfdis();

    /**
     * Obtiene un CFDI
     * 
     * @param evcRfcReceptor
     * @param evcTotal
     * @param evcTipoComprobante
     * @param evcFechaExpedicion
     * @param evcRfcEmisor
     * @return
     *     returns org.tempuri.ClienteUsuarioTimbre
     */
    @WebMethod(operationName = "PpoCfdTimbre_Cn", action = "http://tempuri.org/PpoCfdTimbre_Cn")
    @WebResult(name = "PpoCfdTimbre_CnResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PpoCfdTimbre_Cn", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PpoCfdTimbreCn")
    @ResponseWrapper(localName = "PpoCfdTimbre_CnResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PpoCfdTimbreCnResponse")
    public ClienteUsuarioTimbre ppoCfdTimbreCn(
        @WebParam(name = "evcTipoComprobante", targetNamespace = "http://tempuri.org/")
        String evcTipoComprobante,
        @WebParam(name = "evcRfcEmisor", targetNamespace = "http://tempuri.org/")
        String evcRfcEmisor,
        @WebParam(name = "evcRfcReceptor", targetNamespace = "http://tempuri.org/")
        String evcRfcReceptor,
        @WebParam(name = "evcFechaExpedicion", targetNamespace = "http://tempuri.org/")
        String evcFechaExpedicion,
        @WebParam(name = "evcTotal", targetNamespace = "http://tempuri.org/")
        String evcTotal);

}
