//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.18 at 11:10:04 AM MDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sat.gob.mx/implocal", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.giro.cxc.FEv33.complementos.impuestoslocales;
