package net.izel.ws.seg.funcionbuscar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-02-28T23:15:11.403-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://funcionBuscar.seg.ws.izel.net/", name = "FuncionBuscarIfz")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FuncionBuscarIfz {

    @WebResult(name = "FuncionBuscarResponse", targetNamespace = "http://funcionBuscar.seg.ws.izel.net/", partName = "parameters")
    @WebMethod
    public FuncionBuscarResponse procesar(
        @WebParam(partName = "parameters", name = "FuncionBuscarRequest", targetNamespace = "http://funcionBuscar.seg.ws.izel.net/")
        FuncionBuscarRequest parameters
    );
}
