package net.izel.ws.seg.menubuscar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-03-01T09:44:44.459-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "MenuBuscarIfzService", 
                  wsdlLocation = "http://localhost:17081/esb/seguridad/menu-buscar?wsdl",
                  targetNamespace = "http://menuBuscar.seg.ws.izel.net/") 
public class MenuBuscarIfzService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://menuBuscar.seg.ws.izel.net/", "MenuBuscarIfzService");
    public final static QName MenuBuscarIfzPort = new QName("http://menuBuscar.seg.ws.izel.net/", "MenuBuscarIfzPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:17081/esb/seguridad/menu-buscar?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MenuBuscarIfzService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:17081/esb/seguridad/menu-buscar?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MenuBuscarIfzService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MenuBuscarIfzService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MenuBuscarIfzService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MenuBuscarIfzService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MenuBuscarIfzService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MenuBuscarIfzService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns MenuBuscarIfz
     */
    @WebEndpoint(name = "MenuBuscarIfzPort")
    public MenuBuscarIfz getMenuBuscarIfzPort() {
        return super.getPort(MenuBuscarIfzPort, MenuBuscarIfz.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MenuBuscarIfz
     */
    @WebEndpoint(name = "MenuBuscarIfzPort")
    public MenuBuscarIfz getMenuBuscarIfzPort(WebServiceFeature... features) {
        return super.getPort(MenuBuscarIfzPort, MenuBuscarIfz.class, features);
    }

}
