/*
*
* Copyright (c) 2012 OPCIONES EMPRESARIALES DEL NORESTE S.A. DE C.V. S.F.P / CONDESE S.C.
* Avenida Delfines s/n Entre Marlin y Tiburon, La Paz, BCS Mexico CP 23090.
*
* Clase de definicion de constantes de errores en servicios
*
*/
package net.izel.framework.util.bp;

import java.util.HashMap;

public class Errores {

	/*OK*/
	public static final long OK = 0;

	/*ERROR INESPERADO EN LA PAGINA AL OBTENER LOS PROCESOS*/
	public static final long EI_CON_OBTENER_PROCESOS = 1;

	/*SELECCIONE SUCURSAL*/
	public static final long SELECCIONE_SUCURSAL = 2;

	/*SELECCIONE PROCESO PARA CONSULTAR TAREAS*/
	public static final long SEL_PROCESO_CONSULTAR_TAREAS = 3;

	/*ESPECIFIQUE USUARIO PARA CONSULTAR TAREAS*/
	public static final long USUARIO_VACIO_CONSULTAR_TAREAS = 4;

	/*ERROR INESPERADO AL VALIDA OBTENER TAREAS POR ESTADO*/
	public static final long EI_VALIDA_OBTENER_TAREAS_ESTADO = 5;

	/*ERROR INESPERADO AL OBTENER PROCESO INICIADO ESTADO*/
	public static final long EI_OBTENER_PROCESO_INICIADO_ESTADO = 6;

	/*ESPECIFIQUE CLAVE DE ESTADO DE LOS PROCESOS A BUSCAR*/
	public static final long CVE_EDO_PROCESO_VACIO = 7;

	/*ESPECIFIQUE EMPRESA DE LOS PROCESOS A BUSCAR*/
	public static final long EMPRESA_PROCESO_VACIA = 8;

	/*NO HAY PROCESOS INICIADOS*/
	public static final long PROCESOS_INICIADOS_VACIOS = 9;

	/*NO HAY TAREAS INICIADAS*/
	public static final long TAREAS_INICIADAS_VACIAS = 10;

	/*ERROR INESPERADO AL VERIFICAR PERFIL*/
	public static final long EI_VERIFICAR_PERFIL = 11;

	/*ERROR INESPERADO AL INICIAR PROCESO RENUEVATE*/
	public static final long EI_RENUEVATE_CONTROLLER_INICIAR_PROCESO = 12;

	/*INFORMACION REGISTRADA*/
	public static final long INFORMACION_REGISTRADA = 13;

	/*SELECCIONE PROCESO A INICIAR*/
	public static final long SEL_PROCESO_INICIAR = 14;

	/*ESPECIFIQUE USUARIO PARA INICIAR PROCESO*/
	public static final long USUARIO_VACIO_INICIAR_PROCESO = 15;

	/*ESPECIFIQUE EMPRESA PARA INICIAR PROCESO*/
	public static final long EMPRESA_VACIA_INICIAR_PROCESO = 16;

	/*ERROR INESPERADO AL VALIDAR NUEVO INICIAR PROCESO*/
	public static final long EI_VALIDA_NUEVO_PROCESO_INICIADO = 17;

	/*ERROR INESPERADO AL INICIAR UN NUEVO PROCESO*/
	public static final long EI_NUEVO_PROCESO_INICIADO = 18;

	/*EL PROCESO A INICIAR NO EXISTE*/
	public static final long PROCEO_NO_EXISTE = 19;

	/*USUARIO SIN PERFIL PARA REALIZAR OPERACION*/
	public static final long USUARIO_SIN_PERFIL = 20;

	/*EL ESTADO DEL PROCESO A INICIAR NO EXISTE*/
	public static final long EDO_PROCESOS_INICIADO_NO_EXISTE = 21;

	/*ESPECIFIQUE CLAVE DE ESTADO PROCESO A INICIAR*/
	public static final long CVE_EDO_PROCESO_INICIAR_VACIA = 22;

	/*EMPRESA REQUERIDA PARA VALIDAR CLAVE ESTADO PROCESO INICIADO*/
	public static final long EMPRESA_VACIA_VALIDA_CVE_PROCESO_INICIADO = 23;

	/*ERROR INESPERADO EN VALIDA CLAVE ESTADO PROCESO INICIADO*/
	public static final long EI_VALIDA_CLAVE_ESTADO_PROCESO_INICIADO = 24;

	/*ERROR INESPERADO AL INICIAR PROCESO*/
	public static final long EI_INICIAR_PROCESO = 25;

	/*NO EXISTE LA TAREA ASIGNADA PARA EL PROCESO*/
	public static final long NO_EXISTE_TAREA_PARA_PROCESO = 26;

	/*USUARIO VACIO PARA REALIZAR LA OPERACION*/
	public static final long USUARIO_VACIO_OPERACION = 27;

	/*ESPECIFIQUE PROCESO INICIADO PARA CREAR ATRIBUTOS*/
	public static final long NAPI_PROCESO_INICIADO_VACIO = 28;

	/*ESPECIFIQUE CLAVE ATRIBUTO*/
	public static final long CLAVE_ATRIBUTO_VACIO = 29;

	/*EMPRESA REQUERIDA PARA VALIDAR CLAVE ATRIBUTO*/
	public static final long EMPRESA_VACIA_VALIDA_CVE_ATRIBUTO = 30;

	/*ATRIBUTO NO EXISTE*/
	public static final long ATRIBUTO_NO_EXISTE = 31;

	/*ERROR INESPERADO EN VALIDA CLAVE ATRIBUTO*/
	public static final long EI_VALIDA_CLAVE_ATRIBUTO = 32;

	/*ESPECIFIQUE EMPRESA PARA CREAR ATRIBUTOS AL PROCESO INICIADO*/
	public static final long NAPI_EMPRESA_VACIO = 33;

	/*ERROR INESPERADO AL VALIDAR NUEVO ATRIBUTO PROCESO INICIADO*/
	public static final long EI_VALIDAR_NVO_ATRIBUTO_PROCESO_INICIADO = 34;

	/*ERROR INESPERADO EN NUEVO ATRIBUTO PROCESO INICIADO*/
	public static final long EI_NVO_ATRIBUTO_PROCESO_INICIADO = 35;

	/*ERROR INESPERADO AL CREAR ATRIBUTOS PROCESO*/
	public static final long EI_CREAR_ATRIBUTOS_PROCESO = 36;

	/*NO EXISTE TAREA SIGUIENTE EN CATALOGO*/
	public static final long NO_EX_TAREA_SIGUIENTE = 37;

	/*ERROR INESPERADO AL EJECUTAR TAREA*/
	public static final long EI_EJECUTAR_TAREA = 38;

	/*ESPECIFIQUE USUARIO PARA VERIFICAR PERFIL*/
	public static final long USUARIO_VACIO_VERIFICAR_PERFIL = 39;

	/*USUARIO SIN PERFIL PARA COMPLETAR LA TAREA*/
	public static final long USUARIO_SIN_PERFIL_TAREA = 40;

	/*ERROR INESPERADO AL OBTENER TAREA SIGUIENTE*/
	public static final long EI_NUEVO_OBTENER_TAREA_SIGUIENTE = 41;

	/*NO EXISTE TAREA SIGUIENTE CONFIGURADA*/
	public static final long NO_EX_TAREA_SIGUIENTE_CONFIGURADA = 42;

	/*ESPECIFIQUE PROCESO PARA OBTENER TAREA SIGUIENTE*/
	public static final long VOTS_PROCESOID_VACIO = 43;

	/*ESPECIFIQUE TAREA PARA OBTENER TAREA SIGUIENTE*/
	public static final long VOTS_TAREAID_VACIO = 44;

	/*ESPECIFIQUE EMPRESA PARA OBTENER TAREA SIGUIENTE*/
	public static final long VOTS_EMPRESAID_VACIA = 45;

	/*ERROR INESPERADO EN VALIDA OBTENER TAREA SIGUIENTE*/
	public static final long EI_VALIDA_OBTENER_TAREA_SIGUIENTE = 46;

	/*ESPECIFIQUE PROCESO INICIADO PARA CONSULTAR ATRIBUTOS*/
	public static final long CAPI_PROCESO_INICIADO_ID_VACIO = 47;

	/*EMPRESA REQUERIDA PARA CONSULTAR ATRIBUTOS*/
	public static final long CAPI_EMPRESA_VACIA = 48;

	/*ERROR INESPERADO EN CONSULTA ATRIBUTOS PROCESO INICIADO*/
	public static final long EI_CONSULTA_ATRIBUTOS_PROCESO_INICIADO = 49;

	/*ESPECIFIQUE SCRIPT A EJECUTAR PARA LA EVALUACION DE LA TAREA*/
	public static final long SCRIPT_VACIO = 50;

	/*ERROR INESPERADO AL EJECUTAR SCRIPT*/
	public static final long EI_EJECUTAR_SCRIPT = 51;

	/*ESPECIFIQUE RESULTADO A BUSCAR PARA OBTENER TAREA SIGUIENTE*/
	public static final long VOTS_RESULTADO_VACIO = 52;

	/*ESPECIFIQUE CONDICION PARA EVALUAR DECISION*/
	public static final long DECISION_VACIO = 53;

	/*ERROR INESPERADO AL EJECUTAR DECISION*/
	public static final long EI_EJECUTAR_DECISION = 54;

	/*ESPECIFIQUE PROCESO PARA EJECUTAR TAREA*/
	public static final long ET_PROCESOID_VACIO = 55;

	/*ESPECIFIQUE TAREA PARA EJECUTAR TAREA*/
	public static final long ET_TAREAID_VACIA = 56;

	/*ESPECIFIQUE EMPRESA PARA EJECUTAR TAREA*/
	public static final long ET_EMPRESAID_VACIA = 57;

	/*ESPECIFIQUE PROCESO PARA OBTENER TAREA INICIAL*/
	public static final long OTI_PROCESOID_VACIO = 58;

	/*ESPECIFIQUE EMPRESA PARA OBTENER TAREA INICIAL*/
	public static final long OTI_EMPRESAID_VACIA = 59;

	/*NO EXISTE TAREA INICIAL CONFIGURADA*/
	public static final long NO_EX_TAREA_INICIAL = 60;

	/*ERROR INESPERADO AL OBTENER TAREA INICIAL*/
	public static final long EI_OBTENER_TAREA_INICIAL = 61;

	/*ERROR INESPERADO AL CREAR TAREA EN UN PROCESO INICIADO*/
	public static final long EI_NUEVA_TAREA_PROCESO_INICIADO = 62;

	/*ESPECIFIQUE CLAVE DE ESTADO DE LA TAREA*/
	public static final long VCETI_CLAVE_EDO_VACIA = 63;

	/*EMPRESA REQUERIDA CONSULTAR ESTADO DE TAREA*/
	public static final long VCETI_EMPRESA_VACIA = 64;

	/*EL ESTADO DE LA TAREA NO EXISTE*/
	public static final long VCETI_ESTADO_NO_EXISTE = 65;

	/*ERROR INESPERADO EN VALIDA CLAVE ESTADO TAREA INICIADA*/
	public static final long EI_VALIDA_CLAVE_ESTADO_TAREA_INICIADA = 66;

	/*SELECCIONE PROCESO A INICIADO PARA INICIAR TAREA*/
	public static final long VNTPI_PROCESOINICIADOID_VACIO = 67;

	/*ESPECIFIQUE TAREA PARA INICIARLA*/
	public static final long VNTPI_TAREAID_VACIO = 68;

	/*ESPECIFIQUE IDENTIFICADOR DE USUARIO PARA INICIAR TAREA*/
	public static final long VNTPI_USUARIOID_VACIO = 69;

	/*ESPECIFIQUE USUARIO PARA INICIAR TAREA*/
	public static final long VNTPI_USUARIO_VACIO = 70;

	/*ESPECIFIQUE EMPRESA PARA INICIAR TAREA*/
	public static final long VNTPI_EMPRESAID_VACIO = 71;

	/*ERROR INESPERADO EN VALIDA NUEVA TAREA PROCESO INICIADO*/
	public static final long EI_VALIDA_NUEVA_TAREA_PROCESO_INICIADO = 72;

	/*USUARIO SIN PERFIL PARA INICIAR TAREA*/
	public static final long NTPI_SIN_PERFIL = 73;

	/*ERROR INESPERADO AL PROCESAR EL FLUJO*/
	public static final long EI_PROCESA_FLUJO = 74;

	/*ESPECIFIQUE TAREA INICIADA PARA CONSULTARLA*/
	public static final long CTAPI_TAREA_PROCESO_INICIADO_ID_VACIO = 75;

	/*EMPRESA REQUERIDA PARA CONSULTAR TAREA INICIADA*/
	public static final long CTAPI_EMPRESA_VACIA = 76;

	/*NO EXISTE TAREA INICIADA EN EL PROCESO*/
	public static final long CTAPI_NO_EX_TAREA_INICIADA = 77;

	/*ERROR INESPERADO AL CONSULTAR TAREA DE UN PROCESO INICIADO*/
	public static final long EI_CONSULTA_TAREA_PROCESO_INICIADO = 78;

	/*LA TAREA YA TIENE EL ESTADO AL QUE SE REQUIERE CAMBIAR*/
	public static final long AETI_ESTADO_ACTUALIZADO = 79;

	/*ESPECIFIQUE USUARIO PARA CAMBIAR ESTADO DE LA TAREA*/
	public static final long AETI_USUARIO_REQUERIDO = 80;

	/*ERROR INESPERADO EN ACTUALIZA ESTADO TAREA INICIADA*/
	public static final long EI_ACTUALIZA_ESTADO_TAREA_INICIADA = 81;

	/*ESPECIFIQUE PROCESO INICIADO PARA CONSULTARLO*/
	public static final long CPI_PROCESO_INICIADO_ID_VACIO = 82;

	/*EMPRESA REQUERIDA PARA CONSULTAR PROCESO INICIADO*/
	public static final long CPI_EMPRESA_VACIA = 83;

	/*NO EXISTE PROCESO INICIADO*/
	public static final long CPI_NO_EX_PROCESO_INICIADA = 84;

	/*ERROR INESPERADO AL CONSULTAR PROCESO INICIADO*/
	public static final long EI_CONSULTA_PROCESO_INICIADO = 85;

	/*EL PROCESO YA TIENE EL ESTADO AL QUE SE REQUIERE CAMBIAR*/
	public static final long AEPI_ESTADO_ACTUALIZADO = 86;

	/*ESPECIFIQUE USUARIO PARA CAMBIAR ESTADO DEL PROCESO*/
	public static final long AEPI_USUARIO_REQUERIDO = 87;

	/*ERROR INESPERADO EN ACTUALIZA ESTADO PROCESO INICIADO*/
	public static final long EI_ACTUALIZA_ESTADO_PROCESO_INICIADO = 88;

	/*ESPECIFIQUE PROCESO PARA CONSULTAR CONFIGURACION DE TAREA*/
	public static final long CCT_PROCESO_ID_VACIO = 89;

	/*ESPECIFIQUE TAREA PARA CONSULTAR CONFIGURACION*/
	public static final long CCT_TAREA_ID_VACIO = 90;

	/*EMPRESA REQUERIDA PARA CONSULTAR TAREA*/
	public static final long CCT_EMPRESA_VACIA = 91;

	/*NO EXISTE TAREA PARA EL PROCESO*/
	public static final long CCT_NO_EX_PROCESO_TAREA = 92;

	/*ERROR INESPERADO AL CONSULTAR FIGURACION TAREA*/
	public static final long EI_CONSULTA_CONFIGURACION_TAREA = 93;
	
	/*ERROR INESPERADO AL CREAR VARIABLES DEL PROCESO*/
	public static final long EI_KCONTEXT_CREAR_VARIABLES = 97;
	
	/*ERROR INESPERADO AL ACTUALIZAR VARIABLES DEL PROCESO*/
	public static final long EI_KCONTEXT_SET_VARIABLES = 98;
	
	/*ERROR INESPERADO AL OBTENER VARIABLES DEL PROCESO*/
	public static final long EI_KCONTEXT_GET_VARIABLES = 98;
	
	/*EL SUB PROCESO NO ESTA EN SEGUIMIENTO AL ACTUALIZAR PADRE*/
	public static final long APPI_ESTADO_PI_NO_S = 101;
	
	/*EL PROCESO PADRE NO ESTA EN SEGUIMIENTO */
	public static final long APPI_ESTADO_PIP_NO_S = 102;
	
	/*ERROR INESPERADO EN ACTUALIZA PADRE PROCESO INICIADO*/
	public static final long EI_ACTUALIZA_PADRE_PROCESO_INICIADO = 103;
	
	/*ERROR INESPERADO AL INICIAR SUBPROCESO*/
	public static final long EI_INICIAR_SUBPROCESO = 104;
	
	/*ESPECIFIQUE PROCESO ID PARA INICIAR SUBPROCESO*/
	public static final long ISP_PROCESO_ID_VACIO = 105;
	
	/*SUBPROCESO NO EXISTE*/
	public static final long ISP_PROCESO_ID_NO_EXISTE = 106;

	/*ERROR INESPERADO AL COPIAR ATRIBUTOS*/
	public static final long EI_COPIAR_ATRIBUTOS = 107;
	
	/*TAREA TERMINADA*/
	public static final long TAREA_TERMINADA = 108;

	/*TAREA INCONCLUSA*/
	public static final long TAREA_INCONCLUSA = 109;
	
	/*ERROR INESPERADO EN EJECUTA FIN*/
	public static final long EI_EJECUTA_FIN = 110;
	
	/*ESPECIFIQUE PROCESO INICIADO PARA OBTENER DATOS DEL SUBPROCESO*/
	public static final long ODS_PROCESO_INICIADO_ID_VACIO = 111;
	
	/*ESPECIFIQUE TAREA INICIADA PARA DATOS DEL SUBPROCESO*/
	public static final long ODS_TAREA_INICIADA_ID_VACIA = 112;
	
	/*NO EXISTE SUBPROCESO INICIADO*/
	public static final long ODS_NO_EX_SUBPROCESO_INICIADO = 113;
	
	/*ERROR INESPERADO AL OBTENER DATOS DEL SUBPROCESO*/
	public static final long EI_OBTENER_DATOS_SUBPROCESO = 114;
	
	/*ESPECIFIQUE PROCESO INICIADO PARA CANCELAR */
	public static final long CP_PROCESO_INICIADO_ID_VACIO = 118;
	
	/*ESPECIFIQUE MOTIVO BAJA PARA CANCELAR */
	public static final long CP_MOTIVO_BAJA_ID_VACIO = 119;
	
	/*ESPECIFIQUE USUARIO PARA CANCELAR */
	public static final long CP_USUARIO_ID_VACIO = 120;
	
	/*ESPECIFIQUE TAREA PARA CANCELAR */
	public static final long CP_TAREA_ID_VACIA = 121;
	
	/*ESPECIFIQUE TAREA INICIADA PARA CANCELAR */
	public static final long CP_TAREA_INICIADA_ID_VACIA = 122;
	
	/*ESPECIFIQUE PROCESO PARA CANCELAR */
	public static final long CP_PROCESO_ID_VACIO = 123; 
	
	/*ERROR INESPERADO AL CANCELAR TAREA DEL PROCESO */
	public static final long EI_CANCELAR_TAREA = 124;
	
	/*ERROR INESPERADO AL CANCELAR PROCESO */
	public static final long EI_CANCELAR_PROCESO = 125;
	
	/*ERROR INESPERADO AL OBTENER LISTADO DE MOTIVOS DE BAJA*/
	public static final long EI_LISTADO_MOTIVO_BAJA = 126;

	/*ERROR INESPERADO CONSULTA ULTIMA TAREA PROSPECTO*/
	public static final long EI_CONSULTA_ULTIMA_TAREA_PROSPECTO = 127;
	
	/*ESPECIFIQUE PROCESO INICIADO PARA CONSULTAR VALOR ATRIBUTO*/
	public static final long CVAA_PROCESO_INICIADO_ID_VACIO = 128;

	/*ESPECIFIQUE CLAVE ATRIBUTO PARA CONSULTAR SU VALOR*/
	public static final long CVAA_ATRIBUTO_VACIA = 129;

	/*ERROR INESPERADO EN CONSULTA VALOR ATRIBUTO POR ATRIBUTO*/
	public static final long EI_CONSULTA_VALOR_ATRIBUTO_POR_ATRIBUTO = 130;

	/*ERROR INESPERADO*/
	public static final long ERROR_INESPERADO = 131;

	/*CAPTURE CAMPOS REQUERIDOS*/
	public static final long CAPTURE_CAMPOS_REQUERIDOS = 132;

	/*ERROR AL OBTENER MAPA DE DATOS DE LA TAREA O PROCESO*/
	public static final long ERR_MAPA_DATOS = 133;

	/*ERROR CRITICO AL PROCESAR %s*/
	public static final long ERR_PROCESO_ANDROID = 134;
	
	/*ERROR CRITICO AL PROCESAR %s*/
	public static final long SIN_PERFIL_CANCELAR_PROCESO = 135;
	
	/*ERROR AL CREAR NUEVO TICKET*/
	public static final long EI_NUEVO_TICKET = 136;
	
	/*ERROR AL CERRAR TICKET*/
	public static final long EI_CERRAR_TICKET = 137;
	
	/*ERROR AL REASIGNAR TICKET*/
	public static final long EI_REASGINACION_TICKET = 138;
	
	/*ERROR FALTA DIGITALIZAR DOCUMENTOS*/
	public static final long ERR_DIGITALIZAR_DOCUMENTOS = 139;
	
	/*ERROR AL OBTENER LA AGENDA DE PROSPECTOS*/
	public static final long ERR_OBTENER_AGENDA = 140;
	
	/*ERROR INESPERADO AL RESPONDER TICKET*/
	public static final long EI_RESPONDER_TICKET = 141;
	
	/*VERIFIQUE NUMERO DE BENEFICIARIOS SE REQUIEREN MAS A LOS CAPTURADOS*/
	public static final long ERROR_NO_BENEFICIARIOS_MIN = 142;
	
	/*VERIFIQUE NUMERO DE BENEFICIARIOS SE EXCEDEN A LOS REQUERIDOS*/
	public static final long ERROR_NO_BENEFICIARIOS_MAX = 143;
	
	/*SE PRESENTO UN PROBLEMA AL EJECUTAR TAREA, COMUNIQUESE CON EL AREA DE SOPORTE*/
	public static final long ERROR_SOPORTE = 144;
	
	public static HashMap<Long, String> descError = new HashMap<Long, String>();

	static {
		descError.put(ERROR_SOPORTE,"SE PRESENTO UN PROBLEMA AL EJECUTAR TAREA, COMUNIQUESE CON EL AREA DE SOPORTE");
		descError.put(EI_REASGINACION_TICKET,"ERROR AL REASIGNAR TICKET");
		descError.put(EI_CERRAR_TICKET,"ERROR AL CERRAR TICKET");
		descError.put(EI_NUEVO_TICKET,"ERROR AL CREAR NUEVO TICKET");
		descError.put(OK,"OK");
		descError.put(EI_CON_OBTENER_PROCESOS,"ERROR INESPERADO EN LA PAGINA AL OBTENER LOS PROCESOS");
		descError.put(SELECCIONE_SUCURSAL,"SELECCIONE SUCURSAL");
		descError.put(SEL_PROCESO_CONSULTAR_TAREAS,"SELECCIONE PROCESO PARA CONSULTAR TAREAS");
		descError.put(USUARIO_VACIO_CONSULTAR_TAREAS,"ESPECIFIQUE USUARIO PARA CONSULTAR TAREAS");
		descError.put(EI_VALIDA_OBTENER_TAREAS_ESTADO,"ERROR INESPERADO AL VALIDA OBTENER TAREAS POR ESTADO");
		descError.put(EI_OBTENER_PROCESO_INICIADO_ESTADO,"ERROR INESPERADO AL OBTENER PROCESO INICIADO ESTADO");
		descError.put(CVE_EDO_PROCESO_VACIO,"ESPECIFIQUE CLAVE DE ESTADO DE LOS PROCESOS A BUSCAR");
		descError.put(EMPRESA_PROCESO_VACIA,"ESPECIFIQUE EMPRESA DE LOS PROCESOS A BUSCAR");
		descError.put(PROCESOS_INICIADOS_VACIOS,"NO HAY PROCESOS INICIADOS");
		descError.put(TAREAS_INICIADAS_VACIAS,"NO HAY TAREAS INICIADAS");
		descError.put(EI_VERIFICAR_PERFIL,"ERROR INESPERADO AL VERIFICAR PERFIL");
		descError.put(EI_RENUEVATE_CONTROLLER_INICIAR_PROCESO,"ERROR INESPERADO AL INICIAR PROCESO RENUEVATE");
		descError.put(INFORMACION_REGISTRADA,"INFORMACION REGISTRADA");
		descError.put(SEL_PROCESO_INICIAR,"SELECCIONE PROCESO A INICIAR");
		descError.put(USUARIO_VACIO_INICIAR_PROCESO,"ESPECIFIQUE USUARIO PARA INICIAR PROCESO");
		descError.put(EMPRESA_VACIA_INICIAR_PROCESO,"ESPECIFIQUE EMPRESA PARA INICIAR PROCESO");
		descError.put(EI_VALIDA_NUEVO_PROCESO_INICIADO,"ERROR INESPERADO AL VALIDAR NUEVO INICIAR PROCESO");
		descError.put(EI_NUEVO_PROCESO_INICIADO,"ERROR INESPERADO AL INICIAR UN NUEVO PROCESO");
		descError.put(PROCEO_NO_EXISTE,"EL PROCESO A INICIAR NO EXISTE");
		descError.put(USUARIO_SIN_PERFIL,"USUARIO SIN PERFIL PARA REALIZAR OPERACION");
		descError.put(EDO_PROCESOS_INICIADO_NO_EXISTE,"EL ESTADO DEL PROCESO A INICIAR NO EXISTE");
		descError.put(CVE_EDO_PROCESO_INICIAR_VACIA,"ESPECIFIQUE CLAVE DE ESTADO PROCESO A INICIAR");
		descError.put(EMPRESA_VACIA_VALIDA_CVE_PROCESO_INICIADO,"EMPRESA REQUERIDA PARA VALIDAR CLAVE ESTADO PROCESO INICIADO");
		descError.put(EI_VALIDA_CLAVE_ESTADO_PROCESO_INICIADO,"ERROR INESPERADO EN VALIDA CLAVE ESTADO PROCESO INICIADO");
		descError.put(EI_INICIAR_PROCESO,"ERROR INESPERADO AL INICIAR PROCESO");
		descError.put(NO_EXISTE_TAREA_PARA_PROCESO,"NO EXISTE LA TAREA ASIGNADA PARA EL PROCESO");
		descError.put(USUARIO_VACIO_OPERACION,"USUARIO VACIO PARA REALIZAR LA OPERACION");
		descError.put(NAPI_PROCESO_INICIADO_VACIO,"ESPECIFIQUE PROCESO INICIADO PARA CREAR ATRIBUTOS");
		descError.put(CLAVE_ATRIBUTO_VACIO,"ESPECIFIQUE CLAVE ATRIBUTO");
		descError.put(EMPRESA_VACIA_VALIDA_CVE_ATRIBUTO,"EMPRESA REQUERIDA PARA VALIDAR CLAVE ATRIBUTO");
		descError.put(ATRIBUTO_NO_EXISTE,"ATRIBUTO NO EXISTE");
		descError.put(EI_VALIDA_CLAVE_ATRIBUTO,"ERROR INESPERADO EN VALIDA CLAVE ATRIBUTO");
		descError.put(NAPI_EMPRESA_VACIO,"ESPECIFIQUE EMPRESA PARA CREAR ATRIBUTOS AL PROCESO INICIADO");
		descError.put(EI_VALIDAR_NVO_ATRIBUTO_PROCESO_INICIADO,"ERROR INESPERADO AL VALIDAR NUEVO ATRIBUTO PROCESO INICIADO");
		descError.put(EI_NVO_ATRIBUTO_PROCESO_INICIADO,"ERROR INESPERADO EN NUEVO ATRIBUTO PROCESO INICIADO");
		descError.put(EI_CREAR_ATRIBUTOS_PROCESO,"ERROR INESPERADO AL CREAR ATRIBUTOS PROCESO");
		descError.put(NO_EX_TAREA_SIGUIENTE,"NO EXISTE TAREA SIGUIENTE EN CATALOGO");
		descError.put(EI_EJECUTAR_TAREA,"ERROR INESPERADO AL EJECUTAR TAREA");
		descError.put(USUARIO_VACIO_VERIFICAR_PERFIL,"ESPECIFIQUE USUARIO PARA VERIFICAR PERFIL");
		descError.put(USUARIO_SIN_PERFIL_TAREA,"USUARIO SIN PERFIL PARA COMPLETAR LA TAREA");
		descError.put(EI_NUEVO_OBTENER_TAREA_SIGUIENTE,"ERROR INESPERADO AL OBTENER TAREA SIGUIENTE");
		descError.put(NO_EX_TAREA_SIGUIENTE_CONFIGURADA,"NO EXISTE TAREA SIGUIENTE CONFIGURADA");
		descError.put(VOTS_PROCESOID_VACIO,"ESPECIFIQUE PROCESO PARA OBTENER TAREA SIGUIENTE");
		descError.put(VOTS_TAREAID_VACIO,"ESPECIFIQUE TAREA PARA OBTENER TAREA SIGUIENTE");
		descError.put(VOTS_EMPRESAID_VACIA,"ESPECIFIQUE EMPRESA PARA OBTENER TAREA SIGUIENTE");
		descError.put(EI_VALIDA_OBTENER_TAREA_SIGUIENTE,"ERROR INESPERADO EN VALIDA OBTENER TAREA SIGUIENTE");
		descError.put(CAPI_PROCESO_INICIADO_ID_VACIO,"ESPECIFIQUE PROCESO INICIADO PARA CONSULTAR ATRIBUTOS");
		descError.put(CAPI_EMPRESA_VACIA,"EMPRESA REQUERIDA PARA CONSULTAR ATRIBUTOS");
		descError.put(EI_CONSULTA_ATRIBUTOS_PROCESO_INICIADO,"ERROR INESPERADO EN CONSULTA ATRIBUTOS PROCESO INICIADO");
		descError.put(SCRIPT_VACIO,"ESPECIFIQUE SCRIPT A EJECUTAR PARA LA EVALUACION DE LA TAREA");
		descError.put(EI_EJECUTAR_SCRIPT,"ERROR INESPERADO AL EJECUTAR SCRIPT");
		descError.put(VOTS_RESULTADO_VACIO,"ESPECIFIQUE RESULTADO A BUSCAR PARA OBTENER TAREA SIGUIENTE");
		descError.put(DECISION_VACIO,"ESPECIFIQUE CONDICION PARA EVALUAR DECISION");
		descError.put(EI_EJECUTAR_DECISION,"ERROR INESPERADO AL EJECUTAR DECISION");
		descError.put(ET_PROCESOID_VACIO,"ESPECIFIQUE PROCESO PARA EJECUTAR TAREA");
		descError.put(ET_TAREAID_VACIA,"ESPECIFIQUE TAREA PARA EJECUTAR TAREA");
		descError.put(ET_EMPRESAID_VACIA,"ESPECIFIQUE EMPRESA PARA EJECUTAR TAREA");
		descError.put(OTI_PROCESOID_VACIO,"ESPECIFIQUE PROCESO PARA OBTENER TAREA INICIAL");
		descError.put(OTI_EMPRESAID_VACIA,"ESPECIFIQUE EMPRESA PARA OBTENER TAREA INICIAL");
		descError.put(NO_EX_TAREA_INICIAL,"NO EXISTE TAREA INICIAL CONFIGURADA");
		descError.put(EI_OBTENER_TAREA_INICIAL,"ERROR INESPERADO AL OBTENER TAREA INICIAL");
		descError.put(EI_NUEVA_TAREA_PROCESO_INICIADO,"ERROR INESPERADO AL CREAR TAREA EN UN PROCESO INICIADO");
		descError.put(VCETI_CLAVE_EDO_VACIA,"ESPECIFIQUE CLAVE DE ESTADO DE LA TAREA");
		descError.put(VCETI_EMPRESA_VACIA,"EMPRESA REQUERIDA CONSULTAR ESTADO DE TAREA");
		descError.put(VCETI_ESTADO_NO_EXISTE,"EL ESTADO DE LA TAREA NO EXISTE");
		descError.put(EI_VALIDA_CLAVE_ESTADO_TAREA_INICIADA,"ERROR INESPERADO EN VALIDA CLAVE ESTADO TAREA INICIADA");
		descError.put(VNTPI_PROCESOINICIADOID_VACIO,"SELECCIONE PROCESO A INICIADO PARA INICIAR TAREA");
		descError.put(VNTPI_TAREAID_VACIO,"ESPECIFIQUE TAREA PARA INICIARLA");
		descError.put(VNTPI_USUARIOID_VACIO,"ESPECIFIQUE IDENTIFICADOR DE USUARIO PARA INICIAR TAREA");
		descError.put(VNTPI_USUARIO_VACIO,"ESPECIFIQUE USUARIO PARA INICIAR TAREA");
		descError.put(VNTPI_EMPRESAID_VACIO,"ESPECIFIQUE EMPRESA PARA INICIAR TAREA");
		descError.put(EI_VALIDA_NUEVA_TAREA_PROCESO_INICIADO,"ERROR INESPERADO EN VALIDA NUEVA TAREA PROCESO INICIADO");
		descError.put(NTPI_SIN_PERFIL,"USUARIO SIN PERFIL PARA INICIAR TAREA");
		descError.put(EI_PROCESA_FLUJO,"ERROR INESPERADO AL PROCESAR EL FLUJO");
		descError.put(CTAPI_TAREA_PROCESO_INICIADO_ID_VACIO,"ESPECIFIQUE TAREA INICIADA PARA CONSULTARLA");
		descError.put(CTAPI_EMPRESA_VACIA,"EMPRESA REQUERIDA PARA CONSULTAR TAREA INICIADA");
		descError.put(CTAPI_NO_EX_TAREA_INICIADA,"NO EXISTE TAREA INICIADA EN EL PROCESO");
		descError.put(EI_CONSULTA_TAREA_PROCESO_INICIADO,"ERROR INESPERADO AL CONSULTAR TAREA DE UN PROCESO INICIADO");
		descError.put(AETI_ESTADO_ACTUALIZADO,"LA TAREA YA TIENE EL ESTADO AL QUE SE REQUIERE CAMBIAR");
		descError.put(AETI_USUARIO_REQUERIDO,"ESPECIFIQUE USUARIO PARA CAMBIAR ESTADO DE LA TAREA");
		descError.put(EI_ACTUALIZA_ESTADO_TAREA_INICIADA,"ERROR INESPERADO EN ACTUALIZA ESTADO TAREA INICIADA");
		descError.put(CPI_PROCESO_INICIADO_ID_VACIO,"ESPECIFIQUE PROCESO INICIADO PARA CONSULTARLO");
		descError.put(CPI_EMPRESA_VACIA,"EMPRESA REQUERIDA PARA CONSULTAR PROCESO INICIADO");
		descError.put(CPI_NO_EX_PROCESO_INICIADA,"NO EXISTE PROCESO INICIADO");
		descError.put(EI_CONSULTA_PROCESO_INICIADO,"ERROR INESPERADO AL CONSULTAR PROCESO INICIADO");
		descError.put(AEPI_ESTADO_ACTUALIZADO,"EL PROCESO YA TIENE EL ESTADO AL QUE SE REQUIERE CAMBIAR");
		descError.put(AEPI_USUARIO_REQUERIDO,"ESPECIFIQUE USUARIO PARA CAMBIAR ESTADO DEL PROCESO");
		descError.put(EI_ACTUALIZA_ESTADO_PROCESO_INICIADO,"ERROR INESPERADO EN ACTUALIZA ESTADO PROCESO INICIADO");
		descError.put(CCT_PROCESO_ID_VACIO,"ESPECIFIQUE PROCESO PARA CONSULTAR CONFIGURACION DE TAREA");
		descError.put(CCT_TAREA_ID_VACIO,"ESPECIFIQUE TAREA PARA CONSULTAR CONFIGURACION");
		descError.put(CCT_EMPRESA_VACIA,"EMPRESA REQUERIDA PARA CONSULTAR TAREA");
		descError.put(CCT_NO_EX_PROCESO_TAREA,"NO EXISTE TAREA PARA EL PROCESO");
		descError.put(EI_CONSULTA_CONFIGURACION_TAREA,"ERROR INESPERADO AL CONSULTAR FIGURACION TAREA");
		descError.put(EI_KCONTEXT_CREAR_VARIABLES, "ERROR INESPERADO AL CREAR VARIABLES DEL PROCESO");
		descError.put(EI_KCONTEXT_SET_VARIABLES, "ERROR INESPERADO AL ACTUALIZAR VARIABLES DEL PROCESO");
		descError.put(EI_KCONTEXT_GET_VARIABLES, "EERROR INESPERADO AL OBTENER VARIABLES DEL PROCESO");
		descError.put(EI_ACTUALIZA_PADRE_PROCESO_INICIADO, "ERROR INESPERADO EN ACTUALIZA PADRE PROCESO INICIADO");
		descError.put(APPI_ESTADO_PIP_NO_S, "EL PROCESO PADRE NO ESTA EN SEGUIMIENTO");
		descError.put(APPI_ESTADO_PI_NO_S , "EL SUB PROCESO NO ESTA EN SEGUIMIENTO AL ACTUALIZAR PADRE");
		descError.put(ISP_PROCESO_ID_VACIO,"ESPECIFIQUE PROCESO ID PARA INICIAR SUBPROCESO");
		descError.put(ISP_PROCESO_ID_NO_EXISTE,"SUBPROCESO NO EXISTE");
		descError.put(EI_COPIAR_ATRIBUTOS, "ERROR INESPERADO AL CREAR ATRIBUTOS");
		descError.put(EI_INICIAR_SUBPROCESO, "ERROR INESPERADO AL INICIAR SUBPROCESO");
		descError.put(TAREA_TERMINADA,"TAREA TERMINADA");
		descError.put(TAREA_INCONCLUSA,"TAREA INCONCLUSA");
		descError.put(EI_EJECUTA_FIN,"ERROR INESPERADO EN EJECUTA FIN");
		descError.put(ODS_PROCESO_INICIADO_ID_VACIO, "ESPECIFIQUE PROCESO INICIADO PARA OBTENER DATOS DEL SUBPROCESO");
		descError.put(ODS_TAREA_INICIADA_ID_VACIA, "ESPECIFIQUE TAREA INICIADA PARA DATOS DEL SUBPROCESO");
		descError.put(ODS_TAREA_INICIADA_ID_VACIA, "ESPECIFIQUE TAREA INICIADA PARA DATOS DEL SUBPROCESO");
		descError.put(ODS_NO_EX_SUBPROCESO_INICIADO, "NO EXISTE SUBPROCESO INICIADO");
		descError.put(EI_OBTENER_DATOS_SUBPROCESO, "ERROR INESPERADO AL OBTENER DATOS DEL SUBPROCESO");
		descError.put(CP_PROCESO_INICIADO_ID_VACIO,"ESPECIFIQUE PROCESO INICIADO PARA CANCELAR");
		descError.put(CP_MOTIVO_BAJA_ID_VACIO,"ESPECIFIQUE MOTIVO BAJA PARA CANCELAR");
		descError.put(CP_TAREA_INICIADA_ID_VACIA,"ESPECIFIQUE TAREA INICIADA PARA CANCELAR");
		descError.put(CP_PROCESO_ID_VACIO,"ESPECIFIQUE PROCESO PARA CANCELAR");
		descError.put(CP_TAREA_ID_VACIA,"ESPECIFIQUE TAREA PARA CANCELAR");
		descError.put(EI_CANCELAR_TAREA,"ERROR INESPERADO AL CANCELAR TAREA DEL PROCESO");
		descError.put(EI_CANCELAR_PROCESO,"ERROR INESPERADO AL CANCELAR PROCESO");
		descError.put(EI_LISTADO_MOTIVO_BAJA,"ERROR INESPERADO AL OBTENER LISTADO DE MOTIVOS DE BAJA");
		descError.put(EI_CONSULTA_ULTIMA_TAREA_PROSPECTO,"ERROR INESPERADO CONSULTA ULTIMA TAREA PROSPECTO");
		descError.put(CVAA_PROCESO_INICIADO_ID_VACIO,"ESPECIFIQUE PROCESO INICIADO PARA CONSULTAR VALOR ATRIBUTO");
		descError.put(CVAA_ATRIBUTO_VACIA,"ESPECIFIQUE CLAVE ATRIBUTO PARA CONSULTAR SU VALOR");
		descError.put(EI_CONSULTA_VALOR_ATRIBUTO_POR_ATRIBUTO,"ERROR INESPERADO EN CONSULTA VALOR ATRIBUTO POR ATRIBUTO");
		descError.put(ERROR_INESPERADO,"ERROR INESPERADO");
		descError.put(CAPTURE_CAMPOS_REQUERIDOS,"CAMPO %s REQUERIDO");
		descError.put(ERR_MAPA_DATOS,"ERROR AL OBTENER MAPA DE DATOS DE LA TAREA O PROCESO");
		descError.put(ERR_PROCESO_ANDROID,"ERROR CRITICO AL PROCESAR %s");
		descError.put(ERR_DIGITALIZAR_DOCUMENTOS,"FALTA DIGITALIZAR DOCUMENTOS");
		descError.put(ERR_OBTENER_AGENDA,"ERROR AL OBTENER LA AGENDA DE PROSPECTOS");
		descError.put(EI_RESPONDER_TICKET,"ERROR INESPERADO AL RESPONDER TICKET");
		descError.put(SIN_PERFIL_CANCELAR_PROCESO, "USUARIO SIN PERFIL PARA CANCELAR PROCESO");
		descError.put(ERROR_NO_BENEFICIARIOS_MIN,"VERIFIQUE NUMERO DE BENEFICIARIOS SE REQUIEREN MAS A LOS CAPTURADOS");
		descError.put(ERROR_NO_BENEFICIARIOS_MAX,"VERIFIQUE NUMERO DE BENEFICIARIOS SE EXCEDEN A LOS REQUERIDOS");
	}

}

