package net.izel.ws.seg.listaUsuarios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-01-07T13:20:59.638-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://listaUsuarios.seg.ws.izel.net/", name = "ListaUsuariosIfz")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ListaUsuariosIfz {

    @WebResult(name = "ListaUsuariosResponse", targetNamespace = "http://ListaUsuarios.seg.ws.izel.net/", partName = "parameters")
    @WebMethod
    public ListaUsuariosResponse procesar(
        @WebParam(partName = "parameters", name = "ListaUsuariosRequest", targetNamespace = "http://ListaUsuarios.seg.ws.izel.net/")
        ListaUsuariosRequest parameters
    );
}
