package net.izel.ws.seg.rolmodificar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-03-01T08:59:27.589-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "RolModificarIfzService", 
                  wsdlLocation = "http://localhost:17081/esb/seguridad/rol-modificar?wsdl",
                  targetNamespace = "http://rolModificar.seg.ws.izel.net/") 
public class RolModificarIfzService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://rolModificar.seg.ws.izel.net/", "RolModificarIfzService");
    public final static QName RolModificarIfzPort = new QName("http://rolModificar.seg.ws.izel.net/", "RolModificarIfzPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:17081/esb/seguridad/rol-modificar?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RolModificarIfzService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:17081/esb/seguridad/rol-modificar?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RolModificarIfzService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RolModificarIfzService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RolModificarIfzService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RolModificarIfzService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RolModificarIfzService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RolModificarIfzService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RolModificarIfz
     */
    @WebEndpoint(name = "RolModificarIfzPort")
    public RolModificarIfz getRolModificarIfzPort() {
        return super.getPort(RolModificarIfzPort, RolModificarIfz.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RolModificarIfz
     */
    @WebEndpoint(name = "RolModificarIfzPort")
    public RolModificarIfz getRolModificarIfzPort(WebServiceFeature... features) {
        return super.getPort(RolModificarIfzPort, RolModificarIfz.class, features);
    }

}
