package net.izel.ws.seg.rolmenuguardar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-03-01T08:53:06.356-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "RolMenuGuardarIfzService", 
                  wsdlLocation = "http://localhost:17081/esb/seguridad/rol-menu-guardar?wsdl",
                  targetNamespace = "http://rolMenuGuardar.seg.ws.izel.net/") 
public class RolMenuGuardarIfzService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://rolMenuGuardar.seg.ws.izel.net/", "RolMenuGuardarIfzService");
    public final static QName RolMenuGuardarIfzPort = new QName("http://rolMenuGuardar.seg.ws.izel.net/", "RolMenuGuardarIfzPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:17081/esb/seguridad/rol-menu-guardar?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RolMenuGuardarIfzService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:17081/esb/seguridad/rol-menu-guardar?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RolMenuGuardarIfzService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RolMenuGuardarIfzService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RolMenuGuardarIfzService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RolMenuGuardarIfzService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RolMenuGuardarIfzService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RolMenuGuardarIfzService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RolMenuGuardarIfz
     */
    @WebEndpoint(name = "RolMenuGuardarIfzPort")
    public RolMenuGuardarIfz getRolMenuGuardarIfzPort() {
        return super.getPort(RolMenuGuardarIfzPort, RolMenuGuardarIfz.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RolMenuGuardarIfz
     */
    @WebEndpoint(name = "RolMenuGuardarIfzPort")
    public RolMenuGuardarIfz getRolMenuGuardarIfzPort(WebServiceFeature... features) {
        return super.getPort(RolMenuGuardarIfzPort, RolMenuGuardarIfz.class, features);
    }

}
