package net.izel.ws.seg.funcionmodificar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-03-02T23:44:25.917-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "FuncionModificarIfzService", 
                  wsdlLocation = "http://localhost:17081/esb/seguridad/funcion-modificar?wsdl",
                  targetNamespace = "http://funcionModificar.seg.ws.izel.net/") 
public class FuncionModificarIfzService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://funcionModificar.seg.ws.izel.net/", "FuncionModificarIfzService");
    public final static QName FuncionModificarIfzPort = new QName("http://funcionModificar.seg.ws.izel.net/", "FuncionModificarIfzPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:17081/esb/seguridad/funcion-modificar?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FuncionModificarIfzService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:17081/esb/seguridad/funcion-modificar?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FuncionModificarIfzService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FuncionModificarIfzService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FuncionModificarIfzService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FuncionModificarIfzService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FuncionModificarIfzService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FuncionModificarIfzService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns FuncionModificarIfz
     */
    @WebEndpoint(name = "FuncionModificarIfzPort")
    public FuncionModificarIfz getFuncionModificarIfzPort() {
        return super.getPort(FuncionModificarIfzPort, FuncionModificarIfz.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FuncionModificarIfz
     */
    @WebEndpoint(name = "FuncionModificarIfzPort")
    public FuncionModificarIfz getFuncionModificarIfzPort(WebServiceFeature... features) {
        return super.getPort(FuncionModificarIfzPort, FuncionModificarIfz.class, features);
    }

}
