package net.izel.ws.seg.rolmenuguardar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-03-01T08:53:06.296-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://rolMenuGuardar.seg.ws.izel.net/", name = "RolMenuGuardarIfz")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RolMenuGuardarIfz {

    @WebResult(name = "RolMenuGuardarResponse", targetNamespace = "http://rolMenuGuardar.seg.ws.izel.net/", partName = "parameters")
    @WebMethod
    public RolMenuGuardarResponse guardar(
        @WebParam(partName = "parameters", name = "RolMenuGuardarRequest", targetNamespace = "http://rolMenuGuardar.seg.ws.izel.net/")
        RolMenuGuardarRequest parameters
    );
}
