package net.izel.ws.seg.funcionmodificar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-03-02T23:44:25.870-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://funcionModificar.seg.ws.izel.net/", name = "FuncionModificarIfz")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FuncionModificarIfz {

    @WebResult(name = "FuncionModificarResponse", targetNamespace = "http://funcionModificar.seg.ws.izel.net/", partName = "parameters")
    @WebMethod
    public FuncionModificarResponse modificar(
        @WebParam(partName = "parameters", name = "FuncionModificarRequest", targetNamespace = "http://funcionModificar.seg.ws.izel.net/")
        FuncionModificarRequest parameters
    );
}
