package net.izel.ws.seg.login;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-02-09T14:19:58.279-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "AutentificacionIfzService", 
                  wsdlLocation = "http://localhost:9081/esb/seguridad/login?wsdl",
                  targetNamespace = "http://login.seg.ws.izel.net/") 
public class AutentificacionIfzService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://login.seg.ws.izel.net/", "AutentificacionIfzService");
    public final static QName AutentificacionIfzPort = new QName("http://login.seg.ws.izel.net/", "AutentificacionIfzPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9081/esb/seguridad/login?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AutentificacionIfzService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9081/esb/seguridad/login?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AutentificacionIfzService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AutentificacionIfzService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutentificacionIfzService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AutentificacionIfzService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AutentificacionIfzService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AutentificacionIfzService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AutentificacionIfz
     */
    @WebEndpoint(name = "AutentificacionIfzPort")
    public AutentificacionIfz getAutentificacionIfzPort() {
        return super.getPort(AutentificacionIfzPort, AutentificacionIfz.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutentificacionIfz
     */
    @WebEndpoint(name = "AutentificacionIfzPort")
    public AutentificacionIfz getAutentificacionIfzPort(WebServiceFeature... features) {
        return super.getPort(AutentificacionIfzPort, AutentificacionIfz.class, features);
    }

}
