package net.izel.ws.seg.usuarioIdBuscar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-01-02T12:45:56.513-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://usuarioIdBuscar.seg.ws.izel.net/", name = "UsuarioIdBuscarIfz")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UsuarioIdBuscarIfz {

    @WebResult(name = "UsuarioIdBuscarResponse", targetNamespace = "http://usuarioIdBuscar.seg.ws.izel.net/", partName = "parameters")
    @WebMethod
    public UsuarioIdBuscarResponse procesar(
        @WebParam(partName = "parameters", name = "UsuarioIdBuscarRequest", targetNamespace = "http://usuarioIdBuscar.seg.ws.izel.net/")
        UsuarioIdBuscarRequest parameters
    );
}
