//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.02 at 08:55:34 PM MDT 
//

@XmlSchema(
		namespace="http://www.sat.gob.mx/cfd/3", 
		elementFormDefault=XmlNsForm.QUALIFIED,
		xmlns={
				@XmlNs(namespaceURI = "http://www.sat.gob.mx/cfd/3", prefix = "cfdi"),
				@XmlNs(namespaceURI = "http://www.w3.org/2001/XMLSchema-instance",  prefix = "xsi")})
package net.giro.cxc.FEv33;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;
