package net.izel.ws.seg.funcionguardar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-03-02T23:53:30.409-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://funcionGuardar.seg.ws.izel.net/", name = "FuncionGuardarIfz")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FuncionGuardarIfz {

    @WebResult(name = "FuncionGuardarResponse", targetNamespace = "http://funcionGuardar.seg.ws.izel.net/", partName = "parameters")
    @WebMethod
    public FuncionGuardarResponse guardar(
        @WebParam(partName = "parameters", name = "FuncionGuardarRequest", targetNamespace = "http://funcionGuardar.seg.ws.izel.net/")
        FuncionGuardarRequest parameters
    );
}
