package net.izel.ws.seg.corebuscar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-03-02T10:42:56.487-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "CoreBuscarIfzService", 
                  wsdlLocation = "http://localhost:17081/esb/seguridad/core-buscar?wsdl",
                  targetNamespace = "http://coreBuscar.seg.ws.izel.net/") 
public class CoreBuscarIfzService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://coreBuscar.seg.ws.izel.net/", "CoreBuscarIfzService");
    public final static QName CoreBuscarIfzPort = new QName("http://coreBuscar.seg.ws.izel.net/", "CoreBuscarIfzPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:17081/esb/seguridad/core-buscar?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CoreBuscarIfzService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:17081/esb/seguridad/core-buscar?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CoreBuscarIfzService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CoreBuscarIfzService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CoreBuscarIfzService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CoreBuscarIfzService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CoreBuscarIfzService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CoreBuscarIfzService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CoreBuscarIfz
     */
    @WebEndpoint(name = "CoreBuscarIfzPort")
    public CoreBuscarIfz getCoreBuscarIfzPort() {
        return super.getPort(CoreBuscarIfzPort, CoreBuscarIfz.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CoreBuscarIfz
     */
    @WebEndpoint(name = "CoreBuscarIfzPort")
    public CoreBuscarIfz getCoreBuscarIfzPort(WebServiceFeature... features) {
        return super.getPort(CoreBuscarIfzPort, CoreBuscarIfz.class, features);
    }

}
