package net.izel.ws.seg.funcioneliminar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-03-02T23:58:12.565-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://funcionEliminar.seg.ws.izel.net/", name = "FuncionEliminarIfz")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FuncionEliminarIfz {

    @WebResult(name = "FuncionEliminarResponse", targetNamespace = "http://funcionEliminar.seg.ws.izel.net/", partName = "parameters")
    @WebMethod
    public FuncionEliminarResponse guardar(
        @WebParam(partName = "parameters", name = "FuncionEliminarRequest", targetNamespace = "http://funcionEliminar.seg.ws.izel.net/")
        FuncionEliminarRequest parameters
    );
}
