package net.izel.ws.seg.usuarioIdBuscar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-01-02T12:45:56.544-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "UsuarioIdBuscarIfzService", 
                  wsdlLocation = "http://localhost:9081/esb/seguridad/usuario-id-buscar?wsdl",
                  targetNamespace = "http://usuarioIdBuscar.seg.ws.izel.net/") 
public class UsuarioIdBuscarIfzService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://usuarioIdBuscar.seg.ws.izel.net/", "UsuarioIdBuscarIfzService");
    public final static QName UsuarioIdBuscarIfzPort = new QName("http://usuarioIdBuscar.seg.ws.izel.net/", "UsuarioIdBuscarIfzPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9081/esb/seguridad/usuario-id-buscar?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UsuarioIdBuscarIfzService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9081/esb/seguridad/usuario-id-buscar?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UsuarioIdBuscarIfzService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UsuarioIdBuscarIfzService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UsuarioIdBuscarIfzService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UsuarioIdBuscarIfzService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UsuarioIdBuscarIfzService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UsuarioIdBuscarIfzService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns UsuarioIdBuscarIfz
     */
    @WebEndpoint(name = "UsuarioIdBuscarIfzPort")
    public UsuarioIdBuscarIfz getUsuarioIdBuscarIfzPort() {
        return super.getPort(UsuarioIdBuscarIfzPort, UsuarioIdBuscarIfz.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UsuarioIdBuscarIfz
     */
    @WebEndpoint(name = "UsuarioIdBuscarIfzPort")
    public UsuarioIdBuscarIfz getUsuarioIdBuscarIfzPort(WebServiceFeature... features) {
        return super.getPort(UsuarioIdBuscarIfzPort, UsuarioIdBuscarIfz.class, features);
    }

}
