package net.izel.framework.util.so;

import java.util.HashMap;

public abstract class Constante {
	
	
	//TIPOS CAMBIOS DE CONDICION PRESTAMO
	public static final Long TIPO_CAMBIO_CONDICION_REFINANCIACION = 1000000000056L;		
	public static final Long TIPO_CAMBIO_CONDICION_REPROGRAMACION = 1000000000057L;	
	public static final Long TIPO_CAMBIO_CONDICION_SUBROGACION = 1000000000058L;	
	
	//TIPO PROCESO CAMBIO DE CONDICION
	public static final Long SOBRE_MISMO_PRESTAMO = 1L;		
	public static final Long CREA_NUEVO_PRESTAMO = 2L;

	//Tipos Consultas historial crediticio
	public static final Long TIPO_BURO_CRDITO = 1000000000807L;		
	public static final Long TIPO_CIRCULO_CREDITO = 1000000000808L;	
	
	// ESTATUS DEL REGISTRO
	public static final Long ALTA_ID = 100000000004L;	
	public static final Long BAJA_ID = 100000000005L;		
	// CONCEPTOS DE OPERACION SOLICITUDES
	public static final Long AUTORIZAR_HOMONIMIA_PROSPECTO = 1L;
	public static final Long REGISTRO_PROSPECTO = 2L;
	public static final Long RECHAZO_PROSPECTO = 3L;
	public static final Long PROSPECTO_REGISTRADO = 100000000002L;
	public static final Long PROSPECTO_RECHAZADO = 100000000003l;
	public static final Long PROSPECTO_AUTORIZADO = 100000000004l;
	public static final Long PROSPECTO_AUTORIZACION_HOMONIMIA = 100000000005L;
	public static final Long SOLICITUD_RECHAZADA = 100000000006L;
	public static final Long SOLICITUD_AUTORIZADA = 100000000007L;
	public static final Long SOLICITUD_COBERTURADA_CON_GARANTIA = 100000000008L;
	public static final Long LIBERACION_DE_COBERTURAS_CON_GARANTIA = 100000000009L;
	public static final Long SOLICITUD_ACREDITADA = 100000000010L;
	public static final Long REGISTRO_DE_SOLICITUD = 1000000000001L;
	public static final Long DICTAMEN_VERIFICACION_CLIENTE = 100000000011L;
	public static final Long DICTAMEN_COMITE_SUCURSAL = 100000000012L;
	public static final Long SUPERVISION_GERENTE = 100000000013L;
	//* TIPO ENTIDADES DE SOLICITUDES
	public static final Long PROSPECTO = 1L;
	public static final Long SOLICITUD = 2L;
	public static final Long COBERTURA_SOLICITUD = 3L;
	public static final Long PERSONA = 4L;	
	// ESTADOS DEL PROSPECTO
	public static final Long ESTATUS_PROSPECTO_SEGUIMIENTO = 100000000001l;
	public static final Long ESTATUS_PROSPECTO_AUTORIZADO= 100000000002L;
	public static final Long ESTATUS_PROSPECTO_RECHAZADO = 100000000003L;
	//* CONCEPTOS TRANSACCION > PUBLICO <
	public static final Long PU_PROSPECTO_REGISTRADO = 100000000040L;
	public static final Long PU_PROSPECTO_RECHAZADO = 100000000034L;
	public static final Long PU_PROSPECTO_AUTORIZADO = 100000000036L;
	public static final Long PU_PROSPECTO_AUTORIZACION_HOMONIMIA = 100000000035L;
	public static final Long PU_REGISTRO_SOLICITUD = 100000000027L;
	public static final Long PU_SOLICITUD_RECHAZADA = 100000000037L;
	public static final Long PU_SOLICITUD_AUTORIZADA = 100000000028L;
	public static final Long PU_SOLICITUD_COBERTURADA_GARANTIA = 100000000038L;
	public static final Long PU_LIBERACION_SOLICITUD_COBERTURADA_GARANTIA = 100000000039L;
	public static final Long PU_SOLICITUD_ACREDITADA = 100000000029L;
	public static final Long PU_DICTAMEN_COMITE_SUCURSAL = 100000000049L; 
	public static final Long PU_DICTAMEN_VERIFICACION_CLIENTE = 100000000048L;
	
	//*ESTADOS DE SOLICITUD*//
	public static final Long ESTATUS_SOLICITUD_ALTA = 1000000000001L;
	public static final Long ESTATUS_SOLICITUD_APROBADA = 1000000000002l;
	public static final Long ESTATUS_SOLICITUD_RECHAZADA = 1000000000003l;
	public static final Long ESTATUS_SOLICITUD_ACREDITADA = 1000000000004l;
	
	//*DICTAMEN_VERIFICACION_CLIENTE*//
	public static final Long DICTAMEN_FAVORABLE = 1000000000790l;
	public static final Long DICTAMEN_NO_FAVORABLE = 1000000000791l;
	
	//*COMPROBACION DE INGRESOS*//
	public static final Long PENSIONADO = 1000000004314L;
	public static final Long ASALARIADO = 1000000004313L;
	public static final Long ACTIVIDAD_PRODUCTIVA = 1000000004315L;
	
	public static HashMap<Long, String> descEstatus = new HashMap<Long, String>();
	
	static {
		
		descEstatus.put(ALTA_ID, "A");
		descEstatus.put(BAJA_ID, "B");
		descEstatus.put(AUTORIZAR_HOMONIMIA_PROSPECTO, "AUTORIZAR_HOMONIMIA_PROSPECTO");
		descEstatus.put(REGISTRO_PROSPECTO, "REGISTRO_PROSPECTO");
		descEstatus.put(PROSPECTO_REGISTRADO, "PROSPECTO_REGISTRADO");
		descEstatus.put(PROSPECTO_RECHAZADO, "PROSPECTO_RECHAZADO");
		descEstatus.put(PROSPECTO_AUTORIZACION_HOMONIMIA, "PROSPECTO_AUTORIZACION_HOMONIMIA");
		descEstatus.put(SOLICITUD_RECHAZADA, "SOLICITUD_RECHAZADA");
		descEstatus.put(SOLICITUD_AUTORIZADA, "SOLICITUD_AUTORIZADA");
		descEstatus.put(SOLICITUD_COBERTURADA_CON_GARANTIA, "SOLICITUD_COBERTURADA_CON_GARANTIA");
		descEstatus.put(LIBERACION_DE_COBERTURAS_CON_GARANTIA, "LIBERACION_DE_COBERTURAS_CON_GARANTIA");
		descEstatus.put(SOLICITUD_ACREDITADA, "SOLICITUD_ACREDITADA");
		descEstatus.put(REGISTRO_DE_SOLICITUD, "REGISTRO_DE_SOLICITUD");
		descEstatus.put(DICTAMEN_VERIFICACION_CLIENTE, "DICTAMEN_VERIFICACION_CLIENTE");
		descEstatus.put(DICTAMEN_COMITE_SUCURSAL, "DICTAMEN_COMITE_SUCURSAL");
		descEstatus.put(SUPERVISION_GERENTE, "SUPERVISION_GERENTE");
		descEstatus.put(PROSPECTO, "PROSPECTO");
		descEstatus.put(SOLICITUD, "SOLICITUD");
		descEstatus.put(COBERTURA_SOLICITUD, "COBERTURA_SOLICITUD");
		descEstatus.put(PERSONA, "PERSONA");
		descEstatus.put(ESTATUS_PROSPECTO_SEGUIMIENTO, "ESTATUS PROSPECTO SEGUIMIENTO");
		descEstatus.put(ESTATUS_PROSPECTO_AUTORIZADO, "ESTATUS PROSPECTO AUTORIZADO");
		descEstatus.put(ESTATUS_PROSPECTO_RECHAZADO, "ESTATUS PROSPECTO RECHAZADO");
		descEstatus.put(PU_PROSPECTO_RECHAZADO, "PU PROSPECTO RECHAZADO ");
		descEstatus.put(PU_PROSPECTO_AUTORIZADO, "PU PROSPECTO AUTORIZADO");
		descEstatus.put(PU_PROSPECTO_AUTORIZACION_HOMONIMIA, "PU PROSPECTO AUTORIZACION HOMONIMIA");
		descEstatus.put(PU_REGISTRO_SOLICITUD, "PU REGISTRO SOLICITUD");
		descEstatus.put(PU_SOLICITUD_RECHAZADA, "PU SOLICITUD RECHAZADA");
		descEstatus.put(PU_SOLICITUD_AUTORIZADA, "PU SOLICITUD AUTORIZADA");
		descEstatus.put(PU_SOLICITUD_COBERTURADA_GARANTIA, "PU SOLICITUD COBERTURADA GARANTIA");
		descEstatus.put(PU_LIBERACION_SOLICITUD_COBERTURADA_GARANTIA, "PU LIBERACION SOLICITUD COBERTURADA GARANTIA");
		descEstatus.put(PU_LIBERACION_SOLICITUD_COBERTURADA_GARANTIA, "PU LIBERACION SOLICITUD COBERTURADA GARANTIA");
		descEstatus.put(PU_DICTAMEN_COMITE_SUCURSAL, "PU DICTAMEN COMITE SUCURSAL");
		descEstatus.put(PU_DICTAMEN_VERIFICACION_CLIENTE, "PU DICTAMEN VERIFICACION CLIENTE");
		descEstatus.put(PU_SOLICITUD_ACREDITADA, "PU SOLICITUD ACREDITADA");
		descEstatus.put(ESTATUS_SOLICITUD_ALTA, "ALTA");
		descEstatus.put(ESTATUS_SOLICITUD_APROBADA, "APROBADA");
		descEstatus.put(ESTATUS_SOLICITUD_RECHAZADA, "RECHAZADA");
		descEstatus.put(ESTATUS_SOLICITUD_ACREDITADA, "ACREDITADA");
		descEstatus.put(TIPO_CAMBIO_CONDICION_REFINANCIACION, "REFINANCIACION");
		descEstatus.put(TIPO_CAMBIO_CONDICION_REPROGRAMACION, "REPROGRAMACION");
		descEstatus.put(TIPO_CAMBIO_CONDICION_SUBROGACION, "SUBROGACION");
		descEstatus.put(PENSIONADO, "PENSIONADO");
		descEstatus.put(ASALARIADO, "ASALARIADO");
		descEstatus.put(ACTIVIDAD_PRODUCTIVA, "ACTIVIDAD PRODUCTIVA");
		
	}
}
