package net.izel.ws.seg.menubuscar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-03-01T09:44:44.419-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://menuBuscar.seg.ws.izel.net/", name = "MenuBuscarIfz")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MenuBuscarIfz {

    @WebResult(name = "MenuBuscarResponse", targetNamespace = "http://menuBuscar.seg.ws.izel.net/", partName = "parameters")
    @WebMethod
    public MenuBuscarResponse procesar(
        @WebParam(partName = "parameters", name = "MenuBuscarRequest", targetNamespace = "http://menuBuscar.seg.ws.izel.net/")
        MenuBuscarRequest parameters
    );
}
