package net.izel.ws.seg.pantallaguardar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-03-01T23:28:29.509-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "PantallaGuardarIfzService", 
                  wsdlLocation = "http://localhost:17081/esb/seguridad/pantalla-guardar?wsdl",
                  targetNamespace = "http://pantallaGuardar.seg.ws.izel.net/") 
public class PantallaGuardarIfzService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://pantallaGuardar.seg.ws.izel.net/", "PantallaGuardarIfzService");
    public final static QName PantallaGuardarIfzPort = new QName("http://pantallaGuardar.seg.ws.izel.net/", "PantallaGuardarIfzPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:17081/esb/seguridad/pantalla-guardar?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PantallaGuardarIfzService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:17081/esb/seguridad/pantalla-guardar?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PantallaGuardarIfzService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PantallaGuardarIfzService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PantallaGuardarIfzService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PantallaGuardarIfzService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PantallaGuardarIfzService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PantallaGuardarIfzService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PantallaGuardarIfz
     */
    @WebEndpoint(name = "PantallaGuardarIfzPort")
    public PantallaGuardarIfz getPantallaGuardarIfzPort() {
        return super.getPort(PantallaGuardarIfzPort, PantallaGuardarIfz.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PantallaGuardarIfz
     */
    @WebEndpoint(name = "PantallaGuardarIfzPort")
    public PantallaGuardarIfz getPantallaGuardarIfzPort(WebServiceFeature... features) {
        return super.getPort(PantallaGuardarIfzPort, PantallaGuardarIfz.class, features);
    }

}
