package net.izel.ws.seg.roleliminar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-03-01T08:51:20.969-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://rolEliminar.seg.ws.izel.net/", name = "RolEliminarIfz")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RolEliminarIfz {

    @WebResult(name = "RolEliminarResponse", targetNamespace = "http://rolEliminar.seg.ws.izel.net/", partName = "parameters")
    @WebMethod
    public RolEliminarResponse guardar(
        @WebParam(partName = "parameters", name = "RolEliminarRequest", targetNamespace = "http://rolEliminar.seg.ws.izel.net/")
        RolEliminarRequest parameters
    );
}
