//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.01 at 02:20:54 PM MDT 
//

package net.giro.cxc.FEv33.complementos.nomina12;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.giro.cxc.fe.v33.complemento.nomina12 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.giro.cxc.fe.v33.complemento.nomina12
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Nomina }
     * 
     */
    public Nomina createNomina() {
        return new Nomina();
    }

    /**
     * Create an instance of {@link Incapacidades }
     * 
     */
    public Incapacidades createNominaIncapacidades() {
        return new Incapacidades();
    }

    /**
     * Create an instance of {@link OtrosPagos }
     * 
     */
    public OtrosPagos createNominaOtrosPagos() {
        return new OtrosPagos();
    }

    /**
     * Create an instance of {@link OtroPago }
     * 
     */
    public OtroPago createNominaOtrosPagosOtroPago() {
        return new OtroPago();
    }

    /**
     * Create an instance of {@link Deducciones }
     * 
     */
    public Deducciones createNominaDeducciones() {
        return new Deducciones();
    }

    /**
     * Create an instance of {@link Percepciones }
     * 
     */
    public Percepciones createNominaPercepciones() {
        return new Percepciones();
    }

    /**
     * Create an instance of {@link Percepcion }
     * 
     */
    public Percepcion createNominaPercepcionesPercepcion() {
        return new Percepcion();
    }

    /**
     * Create an instance of {@link Receptor }
     * 
     */
    public Receptor createNominaReceptor() {
        return new Receptor();
    }

    /**
     * Create an instance of {@link Emisor }
     * 
     */
    public Emisor createNominaEmisor() {
        return new Emisor();
    }

    /**
     * Create an instance of {@link Incapacidad }
     * 
     */
    public Incapacidad createNominaIncapacidadesIncapacidad() {
        return new Incapacidad();
    }

    /**
     * Create an instance of {@link SubsidioAlEmpleo }
     * 
     */
    public SubsidioAlEmpleo createNominaOtrosPagosOtroPagoSubsidioAlEmpleo() {
        return new SubsidioAlEmpleo();
    }

    /**
     * Create an instance of {@link CompensacionSaldosAFavor }
     * 
     */
    public CompensacionSaldosAFavor createNominaOtrosPagosOtroPagoCompensacionSaldosAFavor() {
        return new CompensacionSaldosAFavor();
    }

    /**
     * Create an instance of {@link Deduccion }
     * 
     */
    public Deduccion createNominaDeduccionesDeduccion() {
        return new Deduccion();
    }

    /**
     * Create an instance of {@link JubilacionPensionRetiro }
     * 
     */
    public JubilacionPensionRetiro createNominaPercepcionesJubilacionPensionRetiro() {
        return new JubilacionPensionRetiro();
    }

    /**
     * Create an instance of {@link SeparacionIndemnizacion }
     * 
     */
    public SeparacionIndemnizacion createNominaPercepcionesSeparacionIndemnizacion() {
        return new SeparacionIndemnizacion();
    }

    /**
     * Create an instance of {@link AccionesOTitulos }
     * 
     */
    public AccionesOTitulos createNominaPercepcionesPercepcionAccionesOTitulos() {
        return new AccionesOTitulos();
    }

    /**
     * Create an instance of {@link HorasExtra }
     * 
     */
    public HorasExtra createNominaPercepcionesPercepcionHorasExtra() {
        return new HorasExtra();
    }

    /**
     * Create an instance of {@link SubContratacion }
     * 
     */
    public SubContratacion createNominaReceptorSubContratacion() {
        return new SubContratacion();
    }

    /**
     * Create an instance of {@link EntidadSNCF }
     * 
     */
    public EntidadSNCF createNominaEmisorEntidadSNCF() {
        return new EntidadSNCF();
    }
}
