package net.izel.ws.seg.controlaccesousuarios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-07-21T12:11:08.843-06:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://controlAccesoUsuarios.seg.ws.izel.net/", name = "ControlAccesoUsuariosIfz")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ControlAccesoUsuariosIfz {

    @WebResult(name = "ControlAccesoUsuariosResponse", targetNamespace = "http://controlAccesoUsuarios.seg.ws.izel.net/", partName = "parameters")
    @WebMethod
    public ControlAccesoUsuariosResponse procesar(
        @WebParam(partName = "parameters", name = "ControlAccesoUsuariosRequest", targetNamespace = "http://controlAccesoUsuarios.seg.ws.izel.net/")
        ControlAccesoUsuariosRequest parameters
    );
}
