package net.izel.ws.seg.controlaccesousuarios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-07-21T12:11:08.953-06:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "ControlAccesoUsuariosIfzService", 
                  wsdlLocation = "http://localhost:9081/esb/seguridad/control-acceso-usuarios?wsdl",
                  targetNamespace = "http://controlAccesoUsuarios.seg.ws.izel.net/") 
public class ControlAccesoUsuariosIfzService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://controlAccesoUsuarios.seg.ws.izel.net/", "ControlAccesoUsuariosIfzService");
    public final static QName ControlAccesoUsuariosIfzPort = new QName("http://controlAccesoUsuarios.seg.ws.izel.net/", "ControlAccesoUsuariosIfzPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9081/esb/seguridad/control-acceso-usuarios?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ControlAccesoUsuariosIfzService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9081/esb/seguridad/control-acceso-usuarios?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ControlAccesoUsuariosIfzService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ControlAccesoUsuariosIfzService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControlAccesoUsuariosIfzService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ControlAccesoUsuariosIfzService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ControlAccesoUsuariosIfzService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ControlAccesoUsuariosIfzService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ControlAccesoUsuariosIfz
     */
    @WebEndpoint(name = "ControlAccesoUsuariosIfzPort")
    public ControlAccesoUsuariosIfz getControlAccesoUsuariosIfzPort() {
        return super.getPort(ControlAccesoUsuariosIfzPort, ControlAccesoUsuariosIfz.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControlAccesoUsuariosIfz
     */
    @WebEndpoint(name = "ControlAccesoUsuariosIfzPort")
    public ControlAccesoUsuariosIfz getControlAccesoUsuariosIfzPort(WebServiceFeature... features) {
        return super.getPort(ControlAccesoUsuariosIfzPort, ControlAccesoUsuariosIfz.class, features);
    }

}
