package net.izel.ws.seg.pantallaeliminar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-03-01T17:46:53.139-07:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://pantallaEliminar.seg.ws.izel.net/", name = "PantallaEliminarIfz")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PantallaEliminarIfz {

    @WebResult(name = "PantallaEliminarResponse", targetNamespace = "http://pantallaEliminar.seg.ws.izel.net/", partName = "parameters")
    @WebMethod
    public PantallaEliminarResponse guardar(
        @WebParam(partName = "parameters", name = "PantallaEliminarRequest", targetNamespace = "http://pantallaEliminar.seg.ws.izel.net/")
        PantallaEliminarRequest parameters
    );
}
